// Code generated by `ubx sdk gen` from azurerm_relay_hybrid_connection. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HybridConnection_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const HybridConnection_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface HybridConnectionConfig {
  id?: string | Computed<string>;
  name: string | Computed<string>;
  relayNamespaceName: string | Computed<string>;
  requiresClientAuthorization?: boolean | Computed<boolean>;
  resourceGroupName: string | Computed<string>;
  userMetadata?: string | Computed<string>;
  timeouts?: HybridConnection_Timeouts | Computed<HybridConnection_Timeouts>;
}

export interface HybridConnectionAttrs {
  id: string;
  name: string;
  relayNamespaceName: string;
  requiresClientAuthorization: boolean;
  resourceGroupName: string;
  userMetadata: string;
  timeouts: HybridConnection_Timeouts;
}

export const HybridConnection: ResourceBinding<HybridConnectionConfig, HybridConnectionAttrs> = {
  wireType: "azurerm_relay_hybrid_connection",
  fields: {
    id: "id",
    name: "name",
    relayNamespaceName: "relay_namespace_name",
    requiresClientAuthorization: "requires_client_authorization",
    resourceGroupName: "resource_group_name",
    userMetadata: "user_metadata",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: HybridConnection_TimeoutsFields,
    },
  },
};
