// Code generated by `ubx sdk gen` from azurerm_mysql_flexible_server_active_directory_administrator. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FlexibleServerActiveDirectoryAdministrator_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FlexibleServerActiveDirectoryAdministrator_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FlexibleServerActiveDirectoryAdministratorConfig {
  id?: string | Computed<string>;
  identityId: string | Computed<string>;
  login: string | Computed<string>;
  objectId: string | Computed<string>;
  serverId: string | Computed<string>;
  tenantId: string | Computed<string>;
  timeouts?: FlexibleServerActiveDirectoryAdministrator_Timeouts | Computed<FlexibleServerActiveDirectoryAdministrator_Timeouts>;
}

export interface FlexibleServerActiveDirectoryAdministratorAttrs {
  id: string;
  identityId: string;
  login: string;
  objectId: string;
  serverId: string;
  tenantId: string;
  timeouts: FlexibleServerActiveDirectoryAdministrator_Timeouts;
}

export const FlexibleServerActiveDirectoryAdministrator: ResourceBinding<FlexibleServerActiveDirectoryAdministratorConfig, FlexibleServerActiveDirectoryAdministratorAttrs> = {
  wireType: "azurerm_mysql_flexible_server_active_directory_administrator",
  fields: {
    id: "id",
    identityId: "identity_id",
    login: "login",
    objectId: "object_id",
    serverId: "server_id",
    tenantId: "tenant_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FlexibleServerActiveDirectoryAdministrator_TimeoutsFields,
    },
  },
};
