// Code generated by `ubx sdk gen` from azurerm_cosmosdb_postgresql_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PostgresqlCluster_Servers {
  fqdn: string;
  name: string;
}

export interface PostgresqlCluster_MaintenanceWindow {
  dayOfWeek: number;
  startHour: number;
  startMinute: number;
}

export interface PostgresqlCluster_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const PostgresqlCluster_MaintenanceWindowFields: FieldMap = {
  dayOfWeek: "day_of_week",
  startHour: "start_hour",
  startMinute: "start_minute",
};

const PostgresqlCluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface PostgresqlClusterConfig {
  administratorLoginPassword?: string | Computed<string>;
  citusVersion?: string | Computed<string>;
  coordinatorPublicIpAccessEnabled?: boolean | Computed<boolean>;
  coordinatorServerEdition?: string | Computed<string>;
  coordinatorStorageQuotaInMb?: number | Computed<number>;
  coordinatorVcoreCount?: number | Computed<number>;
  haEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  nodeCount: number | Computed<number>;
  nodePublicIpAccessEnabled?: boolean | Computed<boolean>;
  nodeServerEdition?: string | Computed<string>;
  nodeStorageQuotaInMb?: number | Computed<number>;
  nodeVcores?: number | Computed<number>;
  pointInTimeInUtc?: string | Computed<string>;
  preferredPrimaryZone?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  shardsOnCoordinatorEnabled?: boolean | Computed<boolean>;
  sourceLocation?: string | Computed<string>;
  sourceResourceId?: string | Computed<string>;
  sqlVersion?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  maintenanceWindow?: PostgresqlCluster_MaintenanceWindow[] | Computed<PostgresqlCluster_MaintenanceWindow[]>;
  timeouts?: PostgresqlCluster_Timeouts | Computed<PostgresqlCluster_Timeouts>;
}

export interface PostgresqlClusterAttrs {
  administratorLoginPassword: string;
  citusVersion: string;
  coordinatorPublicIpAccessEnabled: boolean;
  coordinatorServerEdition: string;
  coordinatorStorageQuotaInMb: number;
  coordinatorVcoreCount: number;
  earliestRestoreTime: string;
  haEnabled: boolean;
  id: string;
  location: string;
  name: string;
  nodeCount: number;
  nodePublicIpAccessEnabled: boolean;
  nodeServerEdition: string;
  nodeStorageQuotaInMb: number;
  nodeVcores: number;
  pointInTimeInUtc: string;
  preferredPrimaryZone: string;
  resourceGroupName: string;
  servers: PostgresqlCluster_Servers[];
  shardsOnCoordinatorEnabled: boolean;
  sourceLocation: string;
  sourceResourceId: string;
  sqlVersion: string;
  tags: Record<string, string>;
  maintenanceWindow: PostgresqlCluster_MaintenanceWindow[];
  timeouts: PostgresqlCluster_Timeouts;
}

export const PostgresqlCluster: ResourceBinding<PostgresqlClusterConfig, PostgresqlClusterAttrs> = {
  wireType: "azurerm_cosmosdb_postgresql_cluster",
  fields: {
    administratorLoginPassword: "administrator_login_password",
    citusVersion: "citus_version",
    coordinatorPublicIpAccessEnabled: "coordinator_public_ip_access_enabled",
    coordinatorServerEdition: "coordinator_server_edition",
    coordinatorStorageQuotaInMb: "coordinator_storage_quota_in_mb",
    coordinatorVcoreCount: "coordinator_vcore_count",
    haEnabled: "ha_enabled",
    id: "id",
    location: "location",
    name: "name",
    nodeCount: "node_count",
    nodePublicIpAccessEnabled: "node_public_ip_access_enabled",
    nodeServerEdition: "node_server_edition",
    nodeStorageQuotaInMb: "node_storage_quota_in_mb",
    nodeVcores: "node_vcores",
    pointInTimeInUtc: "point_in_time_in_utc",
    preferredPrimaryZone: "preferred_primary_zone",
    resourceGroupName: "resource_group_name",
    shardsOnCoordinatorEnabled: "shards_on_coordinator_enabled",
    sourceLocation: "source_location",
    sourceResourceId: "source_resource_id",
    sqlVersion: "sql_version",
    tags: "tags",
    maintenanceWindow: {
      wireName: "maintenance_window",
      kind: "list",
      fields: PostgresqlCluster_MaintenanceWindowFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: PostgresqlCluster_TimeoutsFields,
    },
  },
};
