// Code generated by `ubx sdk gen` from azurerm_cosmosdb_sql_role_definition. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SqlRoleDefinition_Permissions {
  dataActions: string[];
}

export interface SqlRoleDefinition_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const SqlRoleDefinition_PermissionsFields: FieldMap = {
  dataActions: "data_actions",
};

const SqlRoleDefinition_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface SqlRoleDefinitionConfig {
  accountName: string | Computed<string>;
  assignableScopes: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  roleDefinitionId?: string | Computed<string>;
  type?: string | Computed<string>;
  permissions?: SqlRoleDefinition_Permissions[] | Computed<SqlRoleDefinition_Permissions[]>;
  timeouts?: SqlRoleDefinition_Timeouts | Computed<SqlRoleDefinition_Timeouts>;
}

export interface SqlRoleDefinitionAttrs {
  accountName: string;
  assignableScopes: string[];
  id: string;
  name: string;
  resourceGroupName: string;
  roleDefinitionId: string;
  type: string;
  permissions: SqlRoleDefinition_Permissions[];
  timeouts: SqlRoleDefinition_Timeouts;
}

export const SqlRoleDefinition: ResourceBinding<SqlRoleDefinitionConfig, SqlRoleDefinitionAttrs> = {
  wireType: "azurerm_cosmosdb_sql_role_definition",
  fields: {
    accountName: "account_name",
    assignableScopes: "assignable_scopes",
    id: "id",
    name: "name",
    resourceGroupName: "resource_group_name",
    roleDefinitionId: "role_definition_id",
    type: "type",
    permissions: {
      wireName: "permissions",
      kind: "set",
      fields: SqlRoleDefinition_PermissionsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SqlRoleDefinition_TimeoutsFields,
    },
  },
};
