// Code generated by `ubx sdk gen` from azurerm_maintenance_assignment_virtual_machine_scale_set. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AssignmentVirtualMachineScaleSet_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const AssignmentVirtualMachineScaleSet_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface AssignmentVirtualMachineScaleSetConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  maintenanceConfigurationId: string | Computed<string>;
  virtualMachineScaleSetId: string | Computed<string>;
  timeouts?: AssignmentVirtualMachineScaleSet_Timeouts | Computed<AssignmentVirtualMachineScaleSet_Timeouts>;
}

export interface AssignmentVirtualMachineScaleSetAttrs {
  id: string;
  location: string;
  maintenanceConfigurationId: string;
  virtualMachineScaleSetId: string;
  timeouts: AssignmentVirtualMachineScaleSet_Timeouts;
}

export const AssignmentVirtualMachineScaleSet: ResourceBinding<AssignmentVirtualMachineScaleSetConfig, AssignmentVirtualMachineScaleSetAttrs> = {
  wireType: "azurerm_maintenance_assignment_virtual_machine_scale_set",
  fields: {
    id: "id",
    location: "location",
    maintenanceConfigurationId: "maintenance_configuration_id",
    virtualMachineScaleSetId: "virtual_machine_scale_set_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AssignmentVirtualMachineScaleSet_TimeoutsFields,
    },
  },
};
