// Code generated by `ubx sdk gen` from azurerm_api_management_openid_connect_provider. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagementOpenidConnectProvider_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ManagementOpenidConnectProvider_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ManagementOpenidConnectProviderConfig {
  apiManagementName: string | Computed<string>;
  clientId: string | Computed<string>;
  clientSecret: string | Computed<string>;
  description?: string | Computed<string>;
  displayName: string | Computed<string>;
  id?: string | Computed<string>;
  metadataEndpoint: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  timeouts?: ManagementOpenidConnectProvider_Timeouts | Computed<ManagementOpenidConnectProvider_Timeouts>;
}

export interface ManagementOpenidConnectProviderAttrs {
  apiManagementName: string;
  clientId: string;
  clientSecret: string;
  description: string;
  displayName: string;
  id: string;
  metadataEndpoint: string;
  name: string;
  resourceGroupName: string;
  timeouts: ManagementOpenidConnectProvider_Timeouts;
}

export const ManagementOpenidConnectProvider: ResourceBinding<ManagementOpenidConnectProviderConfig, ManagementOpenidConnectProviderAttrs> = {
  wireType: "azurerm_api_management_openid_connect_provider",
  fields: {
    apiManagementName: "api_management_name",
    clientId: "client_id",
    clientSecret: "client_secret",
    description: "description",
    displayName: "display_name",
    id: "id",
    metadataEndpoint: "metadata_endpoint",
    name: "name",
    resourceGroupName: "resource_group_name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagementOpenidConnectProvider_TimeoutsFields,
    },
  },
};
