// Code generated by `ubx sdk gen` from azurerm_api_management_subscription. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagementSubscription_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ManagementSubscription_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ManagementSubscriptionConfig {
  allowTracing?: boolean | Computed<boolean>;
  apiId?: string | Computed<string>;
  apiManagementName: string | Computed<string>;
  displayName: string | Computed<string>;
  id?: string | Computed<string>;
  primaryKey?: string | Computed<string>;
  productId?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  secondaryKey?: string | Computed<string>;
  state?: string | Computed<string>;
  subscriptionId?: string | Computed<string>;
  userId?: string | Computed<string>;
  timeouts?: ManagementSubscription_Timeouts | Computed<ManagementSubscription_Timeouts>;
}

export interface ManagementSubscriptionAttrs {
  allowTracing: boolean;
  apiId: string;
  apiManagementName: string;
  displayName: string;
  id: string;
  primaryKey: string;
  productId: string;
  resourceGroupName: string;
  secondaryKey: string;
  state: string;
  subscriptionId: string;
  userId: string;
  timeouts: ManagementSubscription_Timeouts;
}

export const ManagementSubscription: ResourceBinding<ManagementSubscriptionConfig, ManagementSubscriptionAttrs> = {
  wireType: "azurerm_api_management_subscription",
  fields: {
    allowTracing: "allow_tracing",
    apiId: "api_id",
    apiManagementName: "api_management_name",
    displayName: "display_name",
    id: "id",
    primaryKey: "primary_key",
    productId: "product_id",
    resourceGroupName: "resource_group_name",
    secondaryKey: "secondary_key",
    state: "state",
    subscriptionId: "subscription_id",
    userId: "user_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagementSubscription_TimeoutsFields,
    },
  },
};
