// Code generated by `ubx sdk gen` from azurerm_api_management_policy_fragment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagementPolicyFragment_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ManagementPolicyFragment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ManagementPolicyFragmentConfig {
  apiManagementId: string | Computed<string>;
  description?: string | Computed<string>;
  format?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  value: string | Computed<string>;
  timeouts?: ManagementPolicyFragment_Timeouts | Computed<ManagementPolicyFragment_Timeouts>;
}

export interface ManagementPolicyFragmentAttrs {
  apiManagementId: string;
  description: string;
  format: string;
  id: string;
  name: string;
  value: string;
  timeouts: ManagementPolicyFragment_Timeouts;
}

export const ManagementPolicyFragment: ResourceBinding<ManagementPolicyFragmentConfig, ManagementPolicyFragmentAttrs> = {
  wireType: "azurerm_api_management_policy_fragment",
  fields: {
    apiManagementId: "api_management_id",
    description: "description",
    format: "format",
    id: "id",
    name: "name",
    value: "value",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagementPolicyFragment_TimeoutsFields,
    },
  },
};
