// Code generated by `ubx sdk gen` from azurerm_api_management_workspace_certificate. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagementWorkspaceCertificate_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ManagementWorkspaceCertificate_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ManagementWorkspaceCertificateConfig {
  apiManagementWorkspaceId: string | Computed<string>;
  certificateDataBase64?: string | Computed<string>;
  id?: string | Computed<string>;
  keyVaultSecretId?: string | Computed<string>;
  name: string | Computed<string>;
  password?: string | Computed<string>;
  userAssignedIdentityClientId?: string | Computed<string>;
  timeouts?: ManagementWorkspaceCertificate_Timeouts | Computed<ManagementWorkspaceCertificate_Timeouts>;
}

export interface ManagementWorkspaceCertificateAttrs {
  apiManagementWorkspaceId: string;
  certificateDataBase64: string;
  expiration: string;
  id: string;
  keyVaultSecretId: string;
  name: string;
  password: string;
  subject: string;
  thumbprint: string;
  userAssignedIdentityClientId: string;
  timeouts: ManagementWorkspaceCertificate_Timeouts;
}

export const ManagementWorkspaceCertificate: ResourceBinding<ManagementWorkspaceCertificateConfig, ManagementWorkspaceCertificateAttrs> = {
  wireType: "azurerm_api_management_workspace_certificate",
  fields: {
    apiManagementWorkspaceId: "api_management_workspace_id",
    certificateDataBase64: "certificate_data_base64",
    id: "id",
    keyVaultSecretId: "key_vault_secret_id",
    name: "name",
    password: "password",
    userAssignedIdentityClientId: "user_assigned_identity_client_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagementWorkspaceCertificate_TimeoutsFields,
    },
  },
};
