// Code generated by `ubx sdk gen` from azurerm_application_insights_smart_detection_rule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface InsightsSmartDetectionRule_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const InsightsSmartDetectionRule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface InsightsSmartDetectionRuleConfig {
  additionalEmailRecipients?: string[] | Computed<string[]>;
  applicationInsightsId: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  sendEmailsToSubscriptionOwners?: boolean | Computed<boolean>;
  timeouts?: InsightsSmartDetectionRule_Timeouts | Computed<InsightsSmartDetectionRule_Timeouts>;
}

export interface InsightsSmartDetectionRuleAttrs {
  additionalEmailRecipients: string[];
  applicationInsightsId: string;
  enabled: boolean;
  id: string;
  name: string;
  sendEmailsToSubscriptionOwners: boolean;
  timeouts: InsightsSmartDetectionRule_Timeouts;
}

export const InsightsSmartDetectionRule: ResourceBinding<InsightsSmartDetectionRuleConfig, InsightsSmartDetectionRuleAttrs> = {
  wireType: "azurerm_application_insights_smart_detection_rule",
  fields: {
    additionalEmailRecipients: "additional_email_recipients",
    applicationInsightsId: "application_insights_id",
    enabled: "enabled",
    id: "id",
    name: "name",
    sendEmailsToSubscriptionOwners: "send_emails_to_subscription_owners",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: InsightsSmartDetectionRule_TimeoutsFields,
    },
  },
};
