// Code generated by `ubx sdk gen` from azurerm_resource_group_policy_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface GroupPolicyAssignment_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface GroupPolicyAssignment_NonComplianceMessage {
  content: string;
  policyDefinitionReferenceId: string;
}

export interface GroupPolicyAssignment_Overrides_Selectors {
  in: string[];
  kind: string;
  notIn: string[];
}

export interface GroupPolicyAssignment_Overrides {
  value: string;
  selectors: GroupPolicyAssignment_Overrides_Selectors[];
}

export interface GroupPolicyAssignment_ResourceSelectors {
  name: string;
  selectors: GroupPolicyAssignment_Overrides_Selectors[];
}

export interface GroupPolicyAssignment_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const GroupPolicyAssignment_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const GroupPolicyAssignment_NonComplianceMessageFields: FieldMap = {
  content: "content",
  policyDefinitionReferenceId: "policy_definition_reference_id",
};

const GroupPolicyAssignment_Overrides_SelectorsFields: FieldMap = {
  in: "in",
  kind: "kind",
  notIn: "not_in",
};

const GroupPolicyAssignment_OverridesFields: FieldMap = {
  value: "value",
  selectors: {
    wireName: "selectors",
    kind: "list",
    fields: GroupPolicyAssignment_Overrides_SelectorsFields,
  },
};

const GroupPolicyAssignment_ResourceSelectorsFields: FieldMap = {
  name: "name",
  selectors: {
    wireName: "selectors",
    kind: "list",
    fields: GroupPolicyAssignment_Overrides_SelectorsFields,
  },
};

const GroupPolicyAssignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface GroupPolicyAssignmentConfig {
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  enforce?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  metadata?: string | Computed<string>;
  name: string | Computed<string>;
  notScopes?: string[] | Computed<string[]>;
  parameters?: string | Computed<string>;
  policyDefinitionId: string | Computed<string>;
  resourceGroupId: string | Computed<string>;
  identity?: GroupPolicyAssignment_Identity[] | Computed<GroupPolicyAssignment_Identity[]>;
  nonComplianceMessage?: GroupPolicyAssignment_NonComplianceMessage[] | Computed<GroupPolicyAssignment_NonComplianceMessage[]>;
  overrides?: GroupPolicyAssignment_Overrides[] | Computed<GroupPolicyAssignment_Overrides[]>;
  resourceSelectors?: GroupPolicyAssignment_ResourceSelectors[] | Computed<GroupPolicyAssignment_ResourceSelectors[]>;
  timeouts?: GroupPolicyAssignment_Timeouts | Computed<GroupPolicyAssignment_Timeouts>;
}

export interface GroupPolicyAssignmentAttrs {
  description: string;
  displayName: string;
  enforce: boolean;
  id: string;
  location: string;
  metadata: string;
  name: string;
  notScopes: string[];
  parameters: string;
  policyDefinitionId: string;
  resourceGroupId: string;
  identity: GroupPolicyAssignment_Identity[];
  nonComplianceMessage: GroupPolicyAssignment_NonComplianceMessage[];
  overrides: GroupPolicyAssignment_Overrides[];
  resourceSelectors: GroupPolicyAssignment_ResourceSelectors[];
  timeouts: GroupPolicyAssignment_Timeouts;
}

export const GroupPolicyAssignment: ResourceBinding<GroupPolicyAssignmentConfig, GroupPolicyAssignmentAttrs> = {
  wireType: "azurerm_resource_group_policy_assignment",
  fields: {
    description: "description",
    displayName: "display_name",
    enforce: "enforce",
    id: "id",
    location: "location",
    metadata: "metadata",
    name: "name",
    notScopes: "not_scopes",
    parameters: "parameters",
    policyDefinitionId: "policy_definition_id",
    resourceGroupId: "resource_group_id",
    identity: {
      wireName: "identity",
      kind: "list",
      fields: GroupPolicyAssignment_IdentityFields,
    },
    nonComplianceMessage: {
      wireName: "non_compliance_message",
      kind: "list",
      fields: GroupPolicyAssignment_NonComplianceMessageFields,
    },
    overrides: {
      wireName: "overrides",
      kind: "list",
      fields: GroupPolicyAssignment_OverridesFields,
    },
    resourceSelectors: {
      wireName: "resource_selectors",
      kind: "list",
      fields: GroupPolicyAssignment_ResourceSelectorsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: GroupPolicyAssignment_TimeoutsFields,
    },
  },
};
