// Code generated by `ubx sdk gen` from azurerm_postgresql_flexible_server_firewall_rule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FlexibleServerFirewallRule_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FlexibleServerFirewallRule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FlexibleServerFirewallRuleConfig {
  endIpAddress: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  serverId: string | Computed<string>;
  startIpAddress: string | Computed<string>;
  timeouts?: FlexibleServerFirewallRule_Timeouts | Computed<FlexibleServerFirewallRule_Timeouts>;
}

export interface FlexibleServerFirewallRuleAttrs {
  endIpAddress: string;
  id: string;
  name: string;
  serverId: string;
  startIpAddress: string;
  timeouts: FlexibleServerFirewallRule_Timeouts;
}

export const FlexibleServerFirewallRule: ResourceBinding<FlexibleServerFirewallRuleConfig, FlexibleServerFirewallRuleAttrs> = {
  wireType: "azurerm_postgresql_flexible_server_firewall_rule",
  fields: {
    endIpAddress: "end_ip_address",
    id: "id",
    name: "name",
    serverId: "server_id",
    startIpAddress: "start_ip_address",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FlexibleServerFirewallRule_TimeoutsFields,
    },
  },
};
