// Code generated by `ubx sdk gen` from azurerm_netapp_account. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Account_ActiveDirectory {
  aesEncryptionEnabled: boolean;
  dnsServers: string[];
  domain: string;
  kerberosAdName: string;
  kerberosKdcIp: string;
  ldapOverTlsEnabled: boolean;
  ldapSigningEnabled: boolean;
  localNfsUsersWithLdapAllowed: boolean;
  organizationalUnit: string;
  password: string;
  serverRootCaCertificate: string;
  siteName: string;
  smbServerName: string;
  username: string;
}

export interface Account_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface Account_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Account_ActiveDirectoryFields: FieldMap = {
  aesEncryptionEnabled: "aes_encryption_enabled",
  dnsServers: "dns_servers",
  domain: "domain",
  kerberosAdName: "kerberos_ad_name",
  kerberosKdcIp: "kerberos_kdc_ip",
  ldapOverTlsEnabled: "ldap_over_tls_enabled",
  ldapSigningEnabled: "ldap_signing_enabled",
  localNfsUsersWithLdapAllowed: "local_nfs_users_with_ldap_allowed",
  organizationalUnit: "organizational_unit",
  password: "password",
  serverRootCaCertificate: "server_root_ca_certificate",
  siteName: "site_name",
  smbServerName: "smb_server_name",
  username: "username",
};

const Account_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const Account_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AccountConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  activeDirectory?: Account_ActiveDirectory[] | Computed<Account_ActiveDirectory[]>;
  identity?: Account_Identity[] | Computed<Account_Identity[]>;
  timeouts?: Account_Timeouts | Computed<Account_Timeouts>;
}

export interface AccountAttrs {
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  activeDirectory: Account_ActiveDirectory[];
  identity: Account_Identity[];
  timeouts: Account_Timeouts;
}

export const Account: ResourceBinding<AccountConfig, AccountAttrs> = {
  wireType: "azurerm_netapp_account",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    activeDirectory: {
      wireName: "active_directory",
      kind: "list",
      fields: Account_ActiveDirectoryFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: Account_IdentityFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Account_TimeoutsFields,
    },
  },
};
