// Code generated by `ubx sdk gen` from azurerm_logic_app_integration_account_assembly. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AppIntegrationAccountAssembly_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AppIntegrationAccountAssembly_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AppIntegrationAccountAssemblyConfig {
  assemblyName: string | Computed<string>;
  assemblyVersion?: string | Computed<string>;
  content?: string | Computed<string>;
  contentLinkUri?: string | Computed<string>;
  id?: string | Computed<string>;
  integrationAccountName: string | Computed<string>;
  metadata?: Record<string, string> | Computed<Record<string, string>>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  timeouts?: AppIntegrationAccountAssembly_Timeouts | Computed<AppIntegrationAccountAssembly_Timeouts>;
}

export interface AppIntegrationAccountAssemblyAttrs {
  assemblyName: string;
  assemblyVersion: string;
  content: string;
  contentLinkUri: string;
  id: string;
  integrationAccountName: string;
  metadata: Record<string, string>;
  name: string;
  resourceGroupName: string;
  timeouts: AppIntegrationAccountAssembly_Timeouts;
}

export const AppIntegrationAccountAssembly: ResourceBinding<AppIntegrationAccountAssemblyConfig, AppIntegrationAccountAssemblyAttrs> = {
  wireType: "azurerm_logic_app_integration_account_assembly",
  fields: {
    assemblyName: "assembly_name",
    assemblyVersion: "assembly_version",
    content: "content",
    contentLinkUri: "content_link_uri",
    id: "id",
    integrationAccountName: "integration_account_name",
    metadata: "metadata",
    name: "name",
    resourceGroupName: "resource_group_name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AppIntegrationAccountAssembly_TimeoutsFields,
    },
  },
};
