// Code generated by `ubx sdk gen` from azurerm_logic_app_standard. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AppStandard_SiteCredential {
  password: string;
  username: string;
}

export interface AppStandard_ConnectionString {
  name: string;
  type: string;
  value: string;
}

export interface AppStandard_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface AppStandard_SiteConfig_Cors {
  allowedOrigins: string[];
  supportCredentials: boolean;
}

export interface AppStandard_SiteConfig_IpRestriction_Headers {
  xAzureFdid: string[];
  xFdHealthProbe: string[];
  xForwardedFor: string[];
  xForwardedHost: string[];
}

export interface AppStandard_SiteConfig_IpRestriction {
  action: string;
  description: string;
  headers: AppStandard_SiteConfig_IpRestriction_Headers[];
  ipAddress: string;
  name: string;
  priority: number;
  serviceTag: string;
  virtualNetworkSubnetId: string;
}

export interface AppStandard_SiteConfig {
  alwaysOn: boolean;
  appScaleLimit: number;
  autoSwapSlotName: string;
  dotnetFrameworkVersion: string;
  elasticInstanceMinimum: number;
  ftpsState: string;
  healthCheckPath: string;
  http2Enabled: boolean;
  ipRestrictionDefaultAction: string;
  linuxFxVersion: string;
  minTlsVersion: string;
  preWarmedInstanceCount: number;
  runtimeScaleMonitoringEnabled: boolean;
  scmIpRestrictionDefaultAction: string;
  scmMinTlsVersion: string;
  scmType: string;
  scmUseMainIpRestriction: boolean;
  use32BitWorkerProcess: boolean;
  vnetRouteAllEnabled: boolean;
  websocketsEnabled: boolean;
  cors: AppStandard_SiteConfig_Cors[];
  ipRestriction: AppStandard_SiteConfig_IpRestriction[];
  scmIpRestriction: AppStandard_SiteConfig_IpRestriction[];
}

export interface AppStandard_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AppStandard_ConnectionStringFields: FieldMap = {
  name: "name",
  type: "type",
  value: "value",
};

const AppStandard_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const AppStandard_SiteConfig_CorsFields: FieldMap = {
  allowedOrigins: "allowed_origins",
  supportCredentials: "support_credentials",
};

const AppStandard_SiteConfig_IpRestriction_HeadersFields: FieldMap = {
  xAzureFdid: "x_azure_fdid",
  xFdHealthProbe: "x_fd_health_probe",
  xForwardedFor: "x_forwarded_for",
  xForwardedHost: "x_forwarded_host",
};

const AppStandard_SiteConfig_IpRestrictionFields: FieldMap = {
  action: "action",
  description: "description",
  headers: {
    wireName: "headers",
    kind: "list",
    fields: AppStandard_SiteConfig_IpRestriction_HeadersFields,
  },
  ipAddress: "ip_address",
  name: "name",
  priority: "priority",
  serviceTag: "service_tag",
  virtualNetworkSubnetId: "virtual_network_subnet_id",
};

const AppStandard_SiteConfigFields: FieldMap = {
  alwaysOn: "always_on",
  appScaleLimit: "app_scale_limit",
  autoSwapSlotName: "auto_swap_slot_name",
  dotnetFrameworkVersion: "dotnet_framework_version",
  elasticInstanceMinimum: "elastic_instance_minimum",
  ftpsState: "ftps_state",
  healthCheckPath: "health_check_path",
  http2Enabled: "http2_enabled",
  ipRestrictionDefaultAction: "ip_restriction_default_action",
  linuxFxVersion: "linux_fx_version",
  minTlsVersion: "min_tls_version",
  preWarmedInstanceCount: "pre_warmed_instance_count",
  runtimeScaleMonitoringEnabled: "runtime_scale_monitoring_enabled",
  scmIpRestrictionDefaultAction: "scm_ip_restriction_default_action",
  scmMinTlsVersion: "scm_min_tls_version",
  scmType: "scm_type",
  scmUseMainIpRestriction: "scm_use_main_ip_restriction",
  use32BitWorkerProcess: "use_32_bit_worker_process",
  vnetRouteAllEnabled: "vnet_route_all_enabled",
  websocketsEnabled: "websockets_enabled",
  cors: {
    wireName: "cors",
    kind: "list",
    fields: AppStandard_SiteConfig_CorsFields,
  },
  ipRestriction: {
    wireName: "ip_restriction",
    kind: "list",
    fields: AppStandard_SiteConfig_IpRestrictionFields,
  },
  scmIpRestriction: {
    wireName: "scm_ip_restriction",
    kind: "list",
    fields: AppStandard_SiteConfig_IpRestrictionFields,
  },
};

const AppStandard_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AppStandardConfig {
  appServicePlanId: string | Computed<string>;
  appSettings?: Record<string, string> | Computed<Record<string, string>>;
  bundleVersion?: string | Computed<string>;
  clientAffinityEnabled?: boolean | Computed<boolean>;
  clientCertificateMode?: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  ftpPublishBasicAuthenticationEnabled?: boolean | Computed<boolean>;
  httpsOnly?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  keyVaultReferenceIdentityId?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  publicNetworkAccess?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  scmPublishBasicAuthenticationEnabled?: boolean | Computed<boolean>;
  storageAccountAccessKey?: string | Computed<string>;
  storageAccountName?: string | Computed<string>;
  storageAccountShareName?: string | Computed<string>;
  storageKeyVaultSecretId?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  useExtensionBundle?: boolean | Computed<boolean>;
  version?: string | Computed<string>;
  virtualNetworkSubnetId?: string | Computed<string>;
  vnetContentShareEnabled?: boolean | Computed<boolean>;
  connectionString?: AppStandard_ConnectionString[] | Computed<AppStandard_ConnectionString[]>;
  identity?: AppStandard_Identity[] | Computed<AppStandard_Identity[]>;
  siteConfig?: AppStandard_SiteConfig[] | Computed<AppStandard_SiteConfig[]>;
  timeouts?: AppStandard_Timeouts | Computed<AppStandard_Timeouts>;
}

export interface AppStandardAttrs {
  appServicePlanId: string;
  appSettings: Record<string, string>;
  bundleVersion: string;
  clientAffinityEnabled: boolean;
  clientCertificateMode: string;
  customDomainVerificationId: string;
  defaultHostname: string;
  enabled: boolean;
  ftpPublishBasicAuthenticationEnabled: boolean;
  httpsOnly: boolean;
  id: string;
  keyVaultReferenceIdentityId: string;
  kind: string;
  location: string;
  name: string;
  outboundIpAddresses: string;
  possibleOutboundIpAddresses: string;
  publicNetworkAccess: string;
  resourceGroupName: string;
  scmPublishBasicAuthenticationEnabled: boolean;
  siteCredential: AppStandard_SiteCredential[];
  storageAccountAccessKey: string;
  storageAccountName: string;
  storageAccountShareName: string;
  storageKeyVaultSecretId: string;
  tags: Record<string, string>;
  useExtensionBundle: boolean;
  version: string;
  virtualNetworkSubnetId: string;
  vnetContentShareEnabled: boolean;
  connectionString: AppStandard_ConnectionString[];
  identity: AppStandard_Identity[];
  siteConfig: AppStandard_SiteConfig[];
  timeouts: AppStandard_Timeouts;
}

export const AppStandard: ResourceBinding<AppStandardConfig, AppStandardAttrs> = {
  wireType: "azurerm_logic_app_standard",
  fields: {
    appServicePlanId: "app_service_plan_id",
    appSettings: "app_settings",
    bundleVersion: "bundle_version",
    clientAffinityEnabled: "client_affinity_enabled",
    clientCertificateMode: "client_certificate_mode",
    enabled: "enabled",
    ftpPublishBasicAuthenticationEnabled: "ftp_publish_basic_authentication_enabled",
    httpsOnly: "https_only",
    id: "id",
    keyVaultReferenceIdentityId: "key_vault_reference_identity_id",
    location: "location",
    name: "name",
    publicNetworkAccess: "public_network_access",
    resourceGroupName: "resource_group_name",
    scmPublishBasicAuthenticationEnabled: "scm_publish_basic_authentication_enabled",
    storageAccountAccessKey: "storage_account_access_key",
    storageAccountName: "storage_account_name",
    storageAccountShareName: "storage_account_share_name",
    storageKeyVaultSecretId: "storage_key_vault_secret_id",
    tags: "tags",
    useExtensionBundle: "use_extension_bundle",
    version: "version",
    virtualNetworkSubnetId: "virtual_network_subnet_id",
    vnetContentShareEnabled: "vnet_content_share_enabled",
    connectionString: {
      wireName: "connection_string",
      kind: "set",
      fields: AppStandard_ConnectionStringFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: AppStandard_IdentityFields,
    },
    siteConfig: {
      wireName: "site_config",
      kind: "list",
      fields: AppStandard_SiteConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AppStandard_TimeoutsFields,
    },
  },
};
