// Code generated by `ubx sdk gen` from azurerm_hdinsight_hadoop_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HadoopCluster_ComponentVersion {
  hadoop: string;
}

export interface HadoopCluster_ComputeIsolation {
  computeIsolationEnabled: boolean;
  hostSku: string;
}

export interface HadoopCluster_DiskEncryption {
  encryptionAlgorithm: string;
  encryptionAtHostEnabled: boolean;
  keyVaultKeyId: string;
  keyVaultManagedIdentityId: string;
}

export interface HadoopCluster_Extension {
  logAnalyticsWorkspaceId: string;
  primaryKey: string;
}

export interface HadoopCluster_Gateway {
  password: string;
  username: string;
}

export interface HadoopCluster_Metastores_Ambari {
  databaseName: string;
  password: string;
  server: string;
  username: string;
}

export interface HadoopCluster_Metastores {
  ambari: HadoopCluster_Metastores_Ambari[];
  hive: HadoopCluster_Metastores_Ambari[];
  oozie: HadoopCluster_Metastores_Ambari[];
}

export interface HadoopCluster_Network {
  connectionDirection: string;
  privateLinkEnabled: boolean;
}

export interface HadoopCluster_PrivateLinkConfiguration_IpConfiguration {
  name: string;
  primary: boolean;
  privateIpAddress: string;
  privateIpAllocationMethod: string;
  subnetId: string;
}

export interface HadoopCluster_PrivateLinkConfiguration {
  groupId: string;
  name: string;
  ipConfiguration: HadoopCluster_PrivateLinkConfiguration_IpConfiguration[];
}

export interface HadoopCluster_Roles_EdgeNode_HttpsEndpoints {
  accessModes: string[];
  destinationPort: number;
  disableGatewayAuth: boolean;
  privateIpAddress: string;
  subDomainSuffix: string;
}

export interface HadoopCluster_Roles_EdgeNode_InstallScriptAction {
  name: string;
  parameters: string;
  uri: string;
}

export interface HadoopCluster_Roles_EdgeNode {
  targetInstanceCount: number;
  vmSize: string;
  httpsEndpoints: HadoopCluster_Roles_EdgeNode_HttpsEndpoints[];
  installScriptAction: HadoopCluster_Roles_EdgeNode_InstallScriptAction[];
  uninstallScriptActions: HadoopCluster_Roles_EdgeNode_InstallScriptAction[];
}

export interface HadoopCluster_Roles_HeadNode {
  password: string;
  sshKeys: string[];
  subnetId: string;
  username: string;
  virtualNetworkId: string;
  vmSize: string;
  scriptActions: HadoopCluster_Roles_EdgeNode_InstallScriptAction[];
}

export interface HadoopCluster_Roles_WorkerNode_Autoscale_Capacity {
  maxInstanceCount: number;
  minInstanceCount: number;
}

export interface HadoopCluster_Roles_WorkerNode_Autoscale_Recurrence_Schedule {
  days: string[];
  targetInstanceCount: number;
  time: string;
}

export interface HadoopCluster_Roles_WorkerNode_Autoscale_Recurrence {
  timezone: string;
  schedule: HadoopCluster_Roles_WorkerNode_Autoscale_Recurrence_Schedule[];
}

export interface HadoopCluster_Roles_WorkerNode_Autoscale {
  capacity: HadoopCluster_Roles_WorkerNode_Autoscale_Capacity[];
  recurrence: HadoopCluster_Roles_WorkerNode_Autoscale_Recurrence[];
}

export interface HadoopCluster_Roles_WorkerNode {
  password: string;
  sshKeys: string[];
  subnetId: string;
  targetInstanceCount: number;
  username: string;
  virtualNetworkId: string;
  vmSize: string;
  autoscale: HadoopCluster_Roles_WorkerNode_Autoscale[];
  scriptActions: HadoopCluster_Roles_EdgeNode_InstallScriptAction[];
}

export interface HadoopCluster_Roles {
  edgeNode: HadoopCluster_Roles_EdgeNode[];
  headNode: HadoopCluster_Roles_HeadNode[];
  workerNode: HadoopCluster_Roles_WorkerNode[];
  zookeeperNode: HadoopCluster_Roles_HeadNode[];
}

export interface HadoopCluster_SecurityProfile {
  aaddsResourceId: string;
  clusterUsersGroupDns: string[];
  domainName: string;
  domainUserPassword: string;
  domainUsername: string;
  ldapsUrls: string[];
  msiResourceId: string;
}

export interface HadoopCluster_StorageAccount {
  isDefault: boolean;
  storageAccountId: string;
  storageAccountKey: string;
  storageContainerUrl: string;
}

export interface HadoopCluster_StorageAccountGen2 {
  filesystemId: string;
  isDefault: boolean;
  storageAccountId: string;
  userAssignedIdentityId: string;
}

export interface HadoopCluster_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const HadoopCluster_ComponentVersionFields: FieldMap = {
  hadoop: "hadoop",
};

const HadoopCluster_ComputeIsolationFields: FieldMap = {
  computeIsolationEnabled: "compute_isolation_enabled",
  hostSku: "host_sku",
};

const HadoopCluster_DiskEncryptionFields: FieldMap = {
  encryptionAlgorithm: "encryption_algorithm",
  encryptionAtHostEnabled: "encryption_at_host_enabled",
  keyVaultKeyId: "key_vault_key_id",
  keyVaultManagedIdentityId: "key_vault_managed_identity_id",
};

const HadoopCluster_ExtensionFields: FieldMap = {
  logAnalyticsWorkspaceId: "log_analytics_workspace_id",
  primaryKey: "primary_key",
};

const HadoopCluster_GatewayFields: FieldMap = {
  password: "password",
  username: "username",
};

const HadoopCluster_Metastores_AmbariFields: FieldMap = {
  databaseName: "database_name",
  password: "password",
  server: "server",
  username: "username",
};

const HadoopCluster_MetastoresFields: FieldMap = {
  ambari: {
    wireName: "ambari",
    kind: "list",
    fields: HadoopCluster_Metastores_AmbariFields,
  },
  hive: {
    wireName: "hive",
    kind: "list",
    fields: HadoopCluster_Metastores_AmbariFields,
  },
  oozie: {
    wireName: "oozie",
    kind: "list",
    fields: HadoopCluster_Metastores_AmbariFields,
  },
};

const HadoopCluster_NetworkFields: FieldMap = {
  connectionDirection: "connection_direction",
  privateLinkEnabled: "private_link_enabled",
};

const HadoopCluster_PrivateLinkConfiguration_IpConfigurationFields: FieldMap = {
  name: "name",
  primary: "primary",
  privateIpAddress: "private_ip_address",
  privateIpAllocationMethod: "private_ip_allocation_method",
  subnetId: "subnet_id",
};

const HadoopCluster_PrivateLinkConfigurationFields: FieldMap = {
  groupId: "group_id",
  name: "name",
  ipConfiguration: {
    wireName: "ip_configuration",
    kind: "list",
    fields: HadoopCluster_PrivateLinkConfiguration_IpConfigurationFields,
  },
};

const HadoopCluster_Roles_EdgeNode_HttpsEndpointsFields: FieldMap = {
  accessModes: "access_modes",
  destinationPort: "destination_port",
  disableGatewayAuth: "disable_gateway_auth",
  privateIpAddress: "private_ip_address",
  subDomainSuffix: "sub_domain_suffix",
};

const HadoopCluster_Roles_EdgeNode_InstallScriptActionFields: FieldMap = {
  name: "name",
  parameters: "parameters",
  uri: "uri",
};

const HadoopCluster_Roles_EdgeNodeFields: FieldMap = {
  targetInstanceCount: "target_instance_count",
  vmSize: "vm_size",
  httpsEndpoints: {
    wireName: "https_endpoints",
    kind: "list",
    fields: HadoopCluster_Roles_EdgeNode_HttpsEndpointsFields,
  },
  installScriptAction: {
    wireName: "install_script_action",
    kind: "list",
    fields: HadoopCluster_Roles_EdgeNode_InstallScriptActionFields,
  },
  uninstallScriptActions: {
    wireName: "uninstall_script_actions",
    kind: "list",
    fields: HadoopCluster_Roles_EdgeNode_InstallScriptActionFields,
  },
};

const HadoopCluster_Roles_HeadNodeFields: FieldMap = {
  password: "password",
  sshKeys: "ssh_keys",
  subnetId: "subnet_id",
  username: "username",
  virtualNetworkId: "virtual_network_id",
  vmSize: "vm_size",
  scriptActions: {
    wireName: "script_actions",
    kind: "list",
    fields: HadoopCluster_Roles_EdgeNode_InstallScriptActionFields,
  },
};

const HadoopCluster_Roles_WorkerNode_Autoscale_CapacityFields: FieldMap = {
  maxInstanceCount: "max_instance_count",
  minInstanceCount: "min_instance_count",
};

const HadoopCluster_Roles_WorkerNode_Autoscale_Recurrence_ScheduleFields: FieldMap = {
  days: "days",
  targetInstanceCount: "target_instance_count",
  time: "time",
};

const HadoopCluster_Roles_WorkerNode_Autoscale_RecurrenceFields: FieldMap = {
  timezone: "timezone",
  schedule: {
    wireName: "schedule",
    kind: "list",
    fields: HadoopCluster_Roles_WorkerNode_Autoscale_Recurrence_ScheduleFields,
  },
};

const HadoopCluster_Roles_WorkerNode_AutoscaleFields: FieldMap = {
  capacity: {
    wireName: "capacity",
    kind: "list",
    fields: HadoopCluster_Roles_WorkerNode_Autoscale_CapacityFields,
  },
  recurrence: {
    wireName: "recurrence",
    kind: "list",
    fields: HadoopCluster_Roles_WorkerNode_Autoscale_RecurrenceFields,
  },
};

const HadoopCluster_Roles_WorkerNodeFields: FieldMap = {
  password: "password",
  sshKeys: "ssh_keys",
  subnetId: "subnet_id",
  targetInstanceCount: "target_instance_count",
  username: "username",
  virtualNetworkId: "virtual_network_id",
  vmSize: "vm_size",
  autoscale: {
    wireName: "autoscale",
    kind: "list",
    fields: HadoopCluster_Roles_WorkerNode_AutoscaleFields,
  },
  scriptActions: {
    wireName: "script_actions",
    kind: "list",
    fields: HadoopCluster_Roles_EdgeNode_InstallScriptActionFields,
  },
};

const HadoopCluster_RolesFields: FieldMap = {
  edgeNode: {
    wireName: "edge_node",
    kind: "list",
    fields: HadoopCluster_Roles_EdgeNodeFields,
  },
  headNode: {
    wireName: "head_node",
    kind: "list",
    fields: HadoopCluster_Roles_HeadNodeFields,
  },
  workerNode: {
    wireName: "worker_node",
    kind: "list",
    fields: HadoopCluster_Roles_WorkerNodeFields,
  },
  zookeeperNode: {
    wireName: "zookeeper_node",
    kind: "list",
    fields: HadoopCluster_Roles_HeadNodeFields,
  },
};

const HadoopCluster_SecurityProfileFields: FieldMap = {
  aaddsResourceId: "aadds_resource_id",
  clusterUsersGroupDns: "cluster_users_group_dns",
  domainName: "domain_name",
  domainUserPassword: "domain_user_password",
  domainUsername: "domain_username",
  ldapsUrls: "ldaps_urls",
  msiResourceId: "msi_resource_id",
};

const HadoopCluster_StorageAccountFields: FieldMap = {
  isDefault: "is_default",
  storageAccountId: "storage_account_id",
  storageAccountKey: "storage_account_key",
  storageContainerUrl: "storage_container_url",
};

const HadoopCluster_StorageAccountGen2Fields: FieldMap = {
  filesystemId: "filesystem_id",
  isDefault: "is_default",
  storageAccountId: "storage_account_id",
  userAssignedIdentityId: "user_assigned_identity_id",
};

const HadoopCluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface HadoopClusterConfig {
  clusterVersion: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  tier: string | Computed<string>;
  tlsMinVersion: string | Computed<string>;
  componentVersion?: HadoopCluster_ComponentVersion[] | Computed<HadoopCluster_ComponentVersion[]>;
  computeIsolation?: HadoopCluster_ComputeIsolation[] | Computed<HadoopCluster_ComputeIsolation[]>;
  diskEncryption?: HadoopCluster_DiskEncryption[] | Computed<HadoopCluster_DiskEncryption[]>;
  extension?: HadoopCluster_Extension[] | Computed<HadoopCluster_Extension[]>;
  gateway?: HadoopCluster_Gateway[] | Computed<HadoopCluster_Gateway[]>;
  metastores?: HadoopCluster_Metastores[] | Computed<HadoopCluster_Metastores[]>;
  monitor?: HadoopCluster_Extension[] | Computed<HadoopCluster_Extension[]>;
  network?: HadoopCluster_Network[] | Computed<HadoopCluster_Network[]>;
  privateLinkConfiguration?: HadoopCluster_PrivateLinkConfiguration[] | Computed<HadoopCluster_PrivateLinkConfiguration[]>;
  roles?: HadoopCluster_Roles[] | Computed<HadoopCluster_Roles[]>;
  securityProfile?: HadoopCluster_SecurityProfile[] | Computed<HadoopCluster_SecurityProfile[]>;
  storageAccount?: HadoopCluster_StorageAccount[] | Computed<HadoopCluster_StorageAccount[]>;
  storageAccountGen2?: HadoopCluster_StorageAccountGen2[] | Computed<HadoopCluster_StorageAccountGen2[]>;
  timeouts?: HadoopCluster_Timeouts | Computed<HadoopCluster_Timeouts>;
}

export interface HadoopClusterAttrs {
  clusterVersion: string;
  httpsEndpoint: string;
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  sshEndpoint: string;
  tags: Record<string, string>;
  tier: string;
  tlsMinVersion: string;
  componentVersion: HadoopCluster_ComponentVersion[];
  computeIsolation: HadoopCluster_ComputeIsolation[];
  diskEncryption: HadoopCluster_DiskEncryption[];
  extension: HadoopCluster_Extension[];
  gateway: HadoopCluster_Gateway[];
  metastores: HadoopCluster_Metastores[];
  monitor: HadoopCluster_Extension[];
  network: HadoopCluster_Network[];
  privateLinkConfiguration: HadoopCluster_PrivateLinkConfiguration[];
  roles: HadoopCluster_Roles[];
  securityProfile: HadoopCluster_SecurityProfile[];
  storageAccount: HadoopCluster_StorageAccount[];
  storageAccountGen2: HadoopCluster_StorageAccountGen2[];
  timeouts: HadoopCluster_Timeouts;
}

export const HadoopCluster: ResourceBinding<HadoopClusterConfig, HadoopClusterAttrs> = {
  wireType: "azurerm_hdinsight_hadoop_cluster",
  fields: {
    clusterVersion: "cluster_version",
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    tier: "tier",
    tlsMinVersion: "tls_min_version",
    componentVersion: {
      wireName: "component_version",
      kind: "list",
      fields: HadoopCluster_ComponentVersionFields,
    },
    computeIsolation: {
      wireName: "compute_isolation",
      kind: "list",
      fields: HadoopCluster_ComputeIsolationFields,
    },
    diskEncryption: {
      wireName: "disk_encryption",
      kind: "list",
      fields: HadoopCluster_DiskEncryptionFields,
    },
    extension: {
      wireName: "extension",
      kind: "list",
      fields: HadoopCluster_ExtensionFields,
    },
    gateway: {
      wireName: "gateway",
      kind: "list",
      fields: HadoopCluster_GatewayFields,
    },
    metastores: {
      wireName: "metastores",
      kind: "list",
      fields: HadoopCluster_MetastoresFields,
    },
    monitor: {
      wireName: "monitor",
      kind: "list",
      fields: HadoopCluster_ExtensionFields,
    },
    network: {
      wireName: "network",
      kind: "list",
      fields: HadoopCluster_NetworkFields,
    },
    privateLinkConfiguration: {
      wireName: "private_link_configuration",
      kind: "list",
      fields: HadoopCluster_PrivateLinkConfigurationFields,
    },
    roles: {
      wireName: "roles",
      kind: "list",
      fields: HadoopCluster_RolesFields,
    },
    securityProfile: {
      wireName: "security_profile",
      kind: "list",
      fields: HadoopCluster_SecurityProfileFields,
    },
    storageAccount: {
      wireName: "storage_account",
      kind: "list",
      fields: HadoopCluster_StorageAccountFields,
    },
    storageAccountGen2: {
      wireName: "storage_account_gen2",
      kind: "list",
      fields: HadoopCluster_StorageAccountGen2Fields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: HadoopCluster_TimeoutsFields,
    },
  },
};
