// Code generated by `ubx sdk gen` from azurerm_key_vault_managed_hardware_security_module_key_rotation_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface VaultManagedHardwareSecurityModuleKeyRotationPolicy_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const VaultManagedHardwareSecurityModuleKeyRotationPolicy_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface VaultManagedHardwareSecurityModuleKeyRotationPolicyConfig {
  expireAfter: string | Computed<string>;
  id?: string | Computed<string>;
  managedHsmKeyId: string | Computed<string>;
  timeAfterCreation?: string | Computed<string>;
  timeBeforeExpiry?: string | Computed<string>;
  timeouts?: VaultManagedHardwareSecurityModuleKeyRotationPolicy_Timeouts | Computed<VaultManagedHardwareSecurityModuleKeyRotationPolicy_Timeouts>;
}

export interface VaultManagedHardwareSecurityModuleKeyRotationPolicyAttrs {
  expireAfter: string;
  id: string;
  managedHsmKeyId: string;
  timeAfterCreation: string;
  timeBeforeExpiry: string;
  timeouts: VaultManagedHardwareSecurityModuleKeyRotationPolicy_Timeouts;
}

export const VaultManagedHardwareSecurityModuleKeyRotationPolicy: ResourceBinding<VaultManagedHardwareSecurityModuleKeyRotationPolicyConfig, VaultManagedHardwareSecurityModuleKeyRotationPolicyAttrs> = {
  wireType: "azurerm_key_vault_managed_hardware_security_module_key_rotation_policy",
  fields: {
    expireAfter: "expire_after",
    id: "id",
    managedHsmKeyId: "managed_hsm_key_id",
    timeAfterCreation: "time_after_creation",
    timeBeforeExpiry: "time_before_expiry",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: VaultManagedHardwareSecurityModuleKeyRotationPolicy_TimeoutsFields,
    },
  },
};
