// Code generated by `ubx sdk gen` from azurerm_key_vault_certificate_contacts. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface VaultCertificateContacts_Contact {
  email: string;
  name: string;
  phone: string;
}

export interface VaultCertificateContacts_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const VaultCertificateContacts_ContactFields: FieldMap = {
  email: "email",
  name: "name",
  phone: "phone",
};

const VaultCertificateContacts_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface VaultCertificateContactsConfig {
  id?: string | Computed<string>;
  keyVaultId: string | Computed<string>;
  contact?: VaultCertificateContacts_Contact[] | Computed<VaultCertificateContacts_Contact[]>;
  timeouts?: VaultCertificateContacts_Timeouts | Computed<VaultCertificateContacts_Timeouts>;
}

export interface VaultCertificateContactsAttrs {
  id: string;
  keyVaultId: string;
  contact: VaultCertificateContacts_Contact[];
  timeouts: VaultCertificateContacts_Timeouts;
}

export const VaultCertificateContacts: ResourceBinding<VaultCertificateContactsConfig, VaultCertificateContactsAttrs> = {
  wireType: "azurerm_key_vault_certificate_contacts",
  fields: {
    id: "id",
    keyVaultId: "key_vault_id",
    contact: {
      wireName: "contact",
      kind: "set",
      fields: VaultCertificateContacts_ContactFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: VaultCertificateContacts_TimeoutsFields,
    },
  },
};
