// Code generated by `ubx sdk gen` from azurerm_key_vault_managed_storage_account. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface VaultManagedStorageAccount_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const VaultManagedStorageAccount_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface VaultManagedStorageAccountConfig {
  id?: string | Computed<string>;
  keyVaultId: string | Computed<string>;
  name: string | Computed<string>;
  regenerateKeyAutomatically?: boolean | Computed<boolean>;
  regenerationPeriod?: string | Computed<string>;
  storageAccountId: string | Computed<string>;
  storageAccountKey: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: VaultManagedStorageAccount_Timeouts | Computed<VaultManagedStorageAccount_Timeouts>;
}

export interface VaultManagedStorageAccountAttrs {
  id: string;
  keyVaultId: string;
  name: string;
  regenerateKeyAutomatically: boolean;
  regenerationPeriod: string;
  storageAccountId: string;
  storageAccountKey: string;
  tags: Record<string, string>;
  timeouts: VaultManagedStorageAccount_Timeouts;
}

export const VaultManagedStorageAccount: ResourceBinding<VaultManagedStorageAccountConfig, VaultManagedStorageAccountAttrs> = {
  wireType: "azurerm_key_vault_managed_storage_account",
  fields: {
    id: "id",
    keyVaultId: "key_vault_id",
    name: "name",
    regenerateKeyAutomatically: "regenerate_key_automatically",
    regenerationPeriod: "regeneration_period",
    storageAccountId: "storage_account_id",
    storageAccountKey: "storage_account_key",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: VaultManagedStorageAccount_TimeoutsFields,
    },
  },
};
