// Code generated by `ubx sdk gen` from azurerm_key_vault_managed_hardware_security_module. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface VaultManagedHardwareSecurityModule_NetworkAcls {
  bypass: string;
  defaultAction: string;
}

export interface VaultManagedHardwareSecurityModule_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const VaultManagedHardwareSecurityModule_NetworkAclsFields: FieldMap = {
  bypass: "bypass",
  defaultAction: "default_action",
};

const VaultManagedHardwareSecurityModule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface VaultManagedHardwareSecurityModuleConfig {
  adminObjectIds: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  publicNetworkAccessEnabled?: boolean | Computed<boolean>;
  purgeProtectionEnabled?: boolean | Computed<boolean>;
  resourceGroupName: string | Computed<string>;
  securityDomainKeyVaultCertificateIds?: string[] | Computed<string[]>;
  securityDomainQuorum?: number | Computed<number>;
  skuName: string | Computed<string>;
  softDeleteRetentionDays?: number | Computed<number>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  tenantId: string | Computed<string>;
  networkAcls?: VaultManagedHardwareSecurityModule_NetworkAcls[] | Computed<VaultManagedHardwareSecurityModule_NetworkAcls[]>;
  timeouts?: VaultManagedHardwareSecurityModule_Timeouts | Computed<VaultManagedHardwareSecurityModule_Timeouts>;
}

export interface VaultManagedHardwareSecurityModuleAttrs {
  adminObjectIds: string[];
  hsmUri: string;
  id: string;
  location: string;
  name: string;
  publicNetworkAccessEnabled: boolean;
  purgeProtectionEnabled: boolean;
  resourceGroupName: string;
  securityDomainEncryptedData: string;
  securityDomainKeyVaultCertificateIds: string[];
  securityDomainQuorum: number;
  skuName: string;
  softDeleteRetentionDays: number;
  tags: Record<string, string>;
  tenantId: string;
  networkAcls: VaultManagedHardwareSecurityModule_NetworkAcls[];
  timeouts: VaultManagedHardwareSecurityModule_Timeouts;
}

export const VaultManagedHardwareSecurityModule: ResourceBinding<VaultManagedHardwareSecurityModuleConfig, VaultManagedHardwareSecurityModuleAttrs> = {
  wireType: "azurerm_key_vault_managed_hardware_security_module",
  fields: {
    adminObjectIds: "admin_object_ids",
    id: "id",
    location: "location",
    name: "name",
    publicNetworkAccessEnabled: "public_network_access_enabled",
    purgeProtectionEnabled: "purge_protection_enabled",
    resourceGroupName: "resource_group_name",
    securityDomainKeyVaultCertificateIds: "security_domain_key_vault_certificate_ids",
    securityDomainQuorum: "security_domain_quorum",
    skuName: "sku_name",
    softDeleteRetentionDays: "soft_delete_retention_days",
    tags: "tags",
    tenantId: "tenant_id",
    networkAcls: {
      wireName: "network_acls",
      kind: "list",
      fields: VaultManagedHardwareSecurityModule_NetworkAclsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: VaultManagedHardwareSecurityModule_TimeoutsFields,
    },
  },
};
