// Code generated by `ubx sdk gen` from azurerm_trusted_signing_account. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SigningAccount_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const SigningAccount_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface SigningAccountConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  skuName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: SigningAccount_Timeouts | Computed<SigningAccount_Timeouts>;
}

export interface SigningAccountAttrs {
  accountUri: string;
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  skuName: string;
  tags: Record<string, string>;
  timeouts: SigningAccount_Timeouts;
}

export const SigningAccount: ResourceBinding<SigningAccountConfig, SigningAccountAttrs> = {
  wireType: "azurerm_trusted_signing_account",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    skuName: "sku_name",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SigningAccount_TimeoutsFields,
    },
  },
};
