// Code generated by `ubx sdk gen` from azurerm_iothub_endpoint_servicebus_queue. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EndpointServicebusQueue_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const EndpointServicebusQueue_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface EndpointServicebusQueueConfig {
  authenticationType?: string | Computed<string>;
  connectionString?: string | Computed<string>;
  endpointUri?: string | Computed<string>;
  entityPath?: string | Computed<string>;
  id?: string | Computed<string>;
  identityId?: string | Computed<string>;
  iothubId: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  subscriptionId?: string | Computed<string>;
  timeouts?: EndpointServicebusQueue_Timeouts | Computed<EndpointServicebusQueue_Timeouts>;
}

export interface EndpointServicebusQueueAttrs {
  authenticationType: string;
  connectionString: string;
  endpointUri: string;
  entityPath: string;
  id: string;
  identityId: string;
  iothubId: string;
  name: string;
  resourceGroupName: string;
  subscriptionId: string;
  timeouts: EndpointServicebusQueue_Timeouts;
}

export const EndpointServicebusQueue: ResourceBinding<EndpointServicebusQueueConfig, EndpointServicebusQueueAttrs> = {
  wireType: "azurerm_iothub_endpoint_servicebus_queue",
  fields: {
    authenticationType: "authentication_type",
    connectionString: "connection_string",
    endpointUri: "endpoint_uri",
    entityPath: "entity_path",
    id: "id",
    identityId: "identity_id",
    iothubId: "iothub_id",
    name: "name",
    resourceGroupName: "resource_group_name",
    subscriptionId: "subscription_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: EndpointServicebusQueue_TimeoutsFields,
    },
  },
};
