// Code generated by `ubx sdk gen` from azurerm_iothub_endpoint_storage_container. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EndpointStorageContainer_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const EndpointStorageContainer_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface EndpointStorageContainerConfig {
  authenticationType?: string | Computed<string>;
  batchFrequencyInSeconds?: number | Computed<number>;
  connectionString?: string | Computed<string>;
  containerName: string | Computed<string>;
  encoding?: string | Computed<string>;
  endpointUri?: string | Computed<string>;
  fileNameFormat?: string | Computed<string>;
  id?: string | Computed<string>;
  identityId?: string | Computed<string>;
  iothubId: string | Computed<string>;
  maxChunkSizeInBytes?: number | Computed<number>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  subscriptionId?: string | Computed<string>;
  timeouts?: EndpointStorageContainer_Timeouts | Computed<EndpointStorageContainer_Timeouts>;
}

export interface EndpointStorageContainerAttrs {
  authenticationType: string;
  batchFrequencyInSeconds: number;
  connectionString: string;
  containerName: string;
  encoding: string;
  endpointUri: string;
  fileNameFormat: string;
  id: string;
  identityId: string;
  iothubId: string;
  maxChunkSizeInBytes: number;
  name: string;
  resourceGroupName: string;
  subscriptionId: string;
  timeouts: EndpointStorageContainer_Timeouts;
}

export const EndpointStorageContainer: ResourceBinding<EndpointStorageContainerConfig, EndpointStorageContainerAttrs> = {
  wireType: "azurerm_iothub_endpoint_storage_container",
  fields: {
    authenticationType: "authentication_type",
    batchFrequencyInSeconds: "batch_frequency_in_seconds",
    connectionString: "connection_string",
    containerName: "container_name",
    encoding: "encoding",
    endpointUri: "endpoint_uri",
    fileNameFormat: "file_name_format",
    id: "id",
    identityId: "identity_id",
    iothubId: "iothub_id",
    maxChunkSizeInBytes: "max_chunk_size_in_bytes",
    name: "name",
    resourceGroupName: "resource_group_name",
    subscriptionId: "subscription_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: EndpointStorageContainer_TimeoutsFields,
    },
  },
};
