// Code generated by `ubx sdk gen` from azurerm_iothub_endpoint_cosmosdb_account. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EndpointCosmosdbAccount_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const EndpointCosmosdbAccount_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface EndpointCosmosdbAccountConfig {
  authenticationType?: string | Computed<string>;
  containerName: string | Computed<string>;
  databaseName: string | Computed<string>;
  endpointUri: string | Computed<string>;
  id?: string | Computed<string>;
  identityId?: string | Computed<string>;
  iothubId: string | Computed<string>;
  name: string | Computed<string>;
  partitionKeyName?: string | Computed<string>;
  partitionKeyTemplate?: string | Computed<string>;
  primaryKey?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  secondaryKey?: string | Computed<string>;
  subscriptionId?: string | Computed<string>;
  timeouts?: EndpointCosmosdbAccount_Timeouts | Computed<EndpointCosmosdbAccount_Timeouts>;
}

export interface EndpointCosmosdbAccountAttrs {
  authenticationType: string;
  containerName: string;
  databaseName: string;
  endpointUri: string;
  id: string;
  identityId: string;
  iothubId: string;
  name: string;
  partitionKeyName: string;
  partitionKeyTemplate: string;
  primaryKey: string;
  resourceGroupName: string;
  secondaryKey: string;
  subscriptionId: string;
  timeouts: EndpointCosmosdbAccount_Timeouts;
}

export const EndpointCosmosdbAccount: ResourceBinding<EndpointCosmosdbAccountConfig, EndpointCosmosdbAccountAttrs> = {
  wireType: "azurerm_iothub_endpoint_cosmosdb_account",
  fields: {
    authenticationType: "authentication_type",
    containerName: "container_name",
    databaseName: "database_name",
    endpointUri: "endpoint_uri",
    id: "id",
    identityId: "identity_id",
    iothubId: "iothub_id",
    name: "name",
    partitionKeyName: "partition_key_name",
    partitionKeyTemplate: "partition_key_template",
    primaryKey: "primary_key",
    resourceGroupName: "resource_group_name",
    secondaryKey: "secondary_key",
    subscriptionId: "subscription_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: EndpointCosmosdbAccount_TimeoutsFields,
    },
  },
};
