// Code generated by `ubx sdk gen` from azurerm_iothub_route. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Route_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Route_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface RouteConfig {
  condition?: string | Computed<string>;
  enabled: boolean | Computed<boolean>;
  endpointNames: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  iothubName: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  source: string | Computed<string>;
  timeouts?: Route_Timeouts | Computed<Route_Timeouts>;
}

export interface RouteAttrs {
  condition: string;
  enabled: boolean;
  endpointNames: string[];
  id: string;
  iothubName: string;
  name: string;
  resourceGroupName: string;
  source: string;
  timeouts: Route_Timeouts;
}

export const Route: ResourceBinding<RouteConfig, RouteAttrs> = {
  wireType: "azurerm_iothub_route",
  fields: {
    condition: "condition",
    enabled: "enabled",
    endpointNames: "endpoint_names",
    id: "id",
    iothubName: "iothub_name",
    name: "name",
    resourceGroupName: "resource_group_name",
    source: "source",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Route_TimeoutsFields,
    },
  },
};
