// Code generated by `ubx sdk gen` from azurerm_palo_alto_next_generation_firewall_virtual_network_local_rulestack. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat_BackendConfig {
  port: number;
  publicIpAddress: string;
}

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat_FrontendConfig {
  port: number;
  publicIpAddressId: string;
}

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat {
  name: string;
  protocol: string;
  backendConfig: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat_BackendConfig[];
  frontendConfig: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat_FrontendConfig[];
}

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DnsSettings {
  azureDnsServers: string[];
  dnsServers: string[];
  useAzureDns: boolean;
}

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfile_VnetConfiguration {
  ipOfTrustForUserDefinedRoutes: string;
  trustedSubnetId: string;
  untrustedSubnetId: string;
  virtualNetworkId: string;
}

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfile {
  egressNatIpAddressIds: string[];
  egressNatIpAddresses: string[];
  publicIpAddressIds: string[];
  publicIpAddresses: string[];
  trustedAddressRanges: string[];
  vnetConfiguration: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfile_VnetConfiguration[];
}

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestack_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat_BackendConfigFields: FieldMap = {
  port: "port",
  publicIpAddress: "public_ip_address",
};

const AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat_FrontendConfigFields: FieldMap = {
  port: "port",
  publicIpAddressId: "public_ip_address_id",
};

const AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNatFields: FieldMap = {
  name: "name",
  protocol: "protocol",
  backendConfig: {
    wireName: "backend_config",
    kind: "list",
    fields: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat_BackendConfigFields,
  },
  frontendConfig: {
    wireName: "frontend_config",
    kind: "list",
    fields: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat_FrontendConfigFields,
  },
};

const AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DnsSettingsFields: FieldMap = {
  azureDnsServers: "azure_dns_servers",
  dnsServers: "dns_servers",
  useAzureDns: "use_azure_dns",
};

const AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfile_VnetConfigurationFields: FieldMap = {
  ipOfTrustForUserDefinedRoutes: "ip_of_trust_for_user_defined_routes",
  trustedSubnetId: "trusted_subnet_id",
  untrustedSubnetId: "untrusted_subnet_id",
  virtualNetworkId: "virtual_network_id",
};

const AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfileFields: FieldMap = {
  egressNatIpAddressIds: "egress_nat_ip_address_ids",
  egressNatIpAddresses: "egress_nat_ip_addresses",
  publicIpAddressIds: "public_ip_address_ids",
  publicIpAddresses: "public_ip_addresses",
  trustedAddressRanges: "trusted_address_ranges",
  vnetConfiguration: {
    wireName: "vnet_configuration",
    kind: "list",
    fields: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfile_VnetConfigurationFields,
  },
};

const AltoNextGenerationFirewallVirtualNetworkLocalRulestack_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestackConfig {
  id?: string | Computed<string>;
  marketplaceOfferId?: string | Computed<string>;
  name: string | Computed<string>;
  planId?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  rulestackId: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  destinationNat?: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat[] | Computed<AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat[]>;
  dnsSettings?: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DnsSettings[] | Computed<AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DnsSettings[]>;
  networkProfile?: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfile[] | Computed<AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfile[]>;
  timeouts?: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_Timeouts | Computed<AltoNextGenerationFirewallVirtualNetworkLocalRulestack_Timeouts>;
}

export interface AltoNextGenerationFirewallVirtualNetworkLocalRulestackAttrs {
  id: string;
  marketplaceOfferId: string;
  name: string;
  planId: string;
  resourceGroupName: string;
  rulestackId: string;
  tags: Record<string, string>;
  destinationNat: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNat[];
  dnsSettings: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DnsSettings[];
  networkProfile: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfile[];
  timeouts: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_Timeouts;
}

export const AltoNextGenerationFirewallVirtualNetworkLocalRulestack: ResourceBinding<AltoNextGenerationFirewallVirtualNetworkLocalRulestackConfig, AltoNextGenerationFirewallVirtualNetworkLocalRulestackAttrs> = {
  wireType: "azurerm_palo_alto_next_generation_firewall_virtual_network_local_rulestack",
  fields: {
    id: "id",
    marketplaceOfferId: "marketplace_offer_id",
    name: "name",
    planId: "plan_id",
    resourceGroupName: "resource_group_name",
    rulestackId: "rulestack_id",
    tags: "tags",
    destinationNat: {
      wireName: "destination_nat",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DestinationNatFields,
    },
    dnsSettings: {
      wireName: "dns_settings",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_DnsSettingsFields,
    },
    networkProfile: {
      wireName: "network_profile",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_NetworkProfileFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AltoNextGenerationFirewallVirtualNetworkLocalRulestack_TimeoutsFields,
    },
  },
};
