// Code generated by `ubx sdk gen` from azurerm_palo_alto_next_generation_firewall_virtual_hub_strata_cloud_manager. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat_BackendConfig {
  port: number;
  publicIpAddress: string;
}

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat_FrontendConfig {
  port: number;
  publicIpAddressId: string;
}

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat {
  name: string;
  protocol: string;
  backendConfig: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat_BackendConfig[];
  frontendConfig: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat_FrontendConfig[];
}

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManager_DnsSettings {
  azureDnsServers: string[];
  dnsServers: string[];
  useAzureDns: boolean;
}

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManager_Identity {
  identityIds: string[];
  type: string;
}

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManager_NetworkProfile {
  egressNatIpAddressIds: string[];
  egressNatIpAddresses: string[];
  ipOfTrustForUserDefinedRoutes: string;
  networkVirtualApplianceId: string;
  publicIpAddressIds: string[];
  publicIpAddresses: string[];
  trustedAddressRanges: string[];
  trustedSubnetId: string;
  untrustedSubnetId: string;
  virtualHubId: string;
}

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManager_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat_BackendConfigFields: FieldMap = {
  port: "port",
  publicIpAddress: "public_ip_address",
};

const AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat_FrontendConfigFields: FieldMap = {
  port: "port",
  publicIpAddressId: "public_ip_address_id",
};

const AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNatFields: FieldMap = {
  name: "name",
  protocol: "protocol",
  backendConfig: {
    wireName: "backend_config",
    kind: "list",
    fields: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat_BackendConfigFields,
  },
  frontendConfig: {
    wireName: "frontend_config",
    kind: "list",
    fields: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat_FrontendConfigFields,
  },
};

const AltoNextGenerationFirewallVirtualHubStrataCloudManager_DnsSettingsFields: FieldMap = {
  azureDnsServers: "azure_dns_servers",
  dnsServers: "dns_servers",
  useAzureDns: "use_azure_dns",
};

const AltoNextGenerationFirewallVirtualHubStrataCloudManager_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  type: "type",
};

const AltoNextGenerationFirewallVirtualHubStrataCloudManager_NetworkProfileFields: FieldMap = {
  egressNatIpAddressIds: "egress_nat_ip_address_ids",
  egressNatIpAddresses: "egress_nat_ip_addresses",
  ipOfTrustForUserDefinedRoutes: "ip_of_trust_for_user_defined_routes",
  networkVirtualApplianceId: "network_virtual_appliance_id",
  publicIpAddressIds: "public_ip_address_ids",
  publicIpAddresses: "public_ip_addresses",
  trustedAddressRanges: "trusted_address_ranges",
  trustedSubnetId: "trusted_subnet_id",
  untrustedSubnetId: "untrusted_subnet_id",
  virtualHubId: "virtual_hub_id",
};

const AltoNextGenerationFirewallVirtualHubStrataCloudManager_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManagerConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  marketplaceOfferId?: string | Computed<string>;
  name: string | Computed<string>;
  planId?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  strataCloudManagerTenantName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  destinationNat?: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat[] | Computed<AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat[]>;
  dnsSettings?: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DnsSettings[] | Computed<AltoNextGenerationFirewallVirtualHubStrataCloudManager_DnsSettings[]>;
  identity?: AltoNextGenerationFirewallVirtualHubStrataCloudManager_Identity[] | Computed<AltoNextGenerationFirewallVirtualHubStrataCloudManager_Identity[]>;
  networkProfile?: AltoNextGenerationFirewallVirtualHubStrataCloudManager_NetworkProfile[] | Computed<AltoNextGenerationFirewallVirtualHubStrataCloudManager_NetworkProfile[]>;
  timeouts?: AltoNextGenerationFirewallVirtualHubStrataCloudManager_Timeouts | Computed<AltoNextGenerationFirewallVirtualHubStrataCloudManager_Timeouts>;
}

export interface AltoNextGenerationFirewallVirtualHubStrataCloudManagerAttrs {
  id: string;
  location: string;
  marketplaceOfferId: string;
  name: string;
  planId: string;
  resourceGroupName: string;
  strataCloudManagerTenantName: string;
  tags: Record<string, string>;
  destinationNat: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNat[];
  dnsSettings: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DnsSettings[];
  identity: AltoNextGenerationFirewallVirtualHubStrataCloudManager_Identity[];
  networkProfile: AltoNextGenerationFirewallVirtualHubStrataCloudManager_NetworkProfile[];
  timeouts: AltoNextGenerationFirewallVirtualHubStrataCloudManager_Timeouts;
}

export const AltoNextGenerationFirewallVirtualHubStrataCloudManager: ResourceBinding<AltoNextGenerationFirewallVirtualHubStrataCloudManagerConfig, AltoNextGenerationFirewallVirtualHubStrataCloudManagerAttrs> = {
  wireType: "azurerm_palo_alto_next_generation_firewall_virtual_hub_strata_cloud_manager",
  fields: {
    id: "id",
    location: "location",
    marketplaceOfferId: "marketplace_offer_id",
    name: "name",
    planId: "plan_id",
    resourceGroupName: "resource_group_name",
    strataCloudManagerTenantName: "strata_cloud_manager_tenant_name",
    tags: "tags",
    destinationNat: {
      wireName: "destination_nat",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DestinationNatFields,
    },
    dnsSettings: {
      wireName: "dns_settings",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualHubStrataCloudManager_DnsSettingsFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualHubStrataCloudManager_IdentityFields,
    },
    networkProfile: {
      wireName: "network_profile",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualHubStrataCloudManager_NetworkProfileFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AltoNextGenerationFirewallVirtualHubStrataCloudManager_TimeoutsFields,
    },
  },
};
