// Code generated by `ubx sdk gen` from azurerm_palo_alto_next_generation_firewall_virtual_network_strata_cloud_manager. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_BackendConfig {
  port: number;
  publicIpAddress: string;
}

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_FrontendConfig {
  port: number;
  publicIpAddressId: string;
}

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat {
  name: string;
  protocol: string;
  backendConfig: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_BackendConfig[];
  frontendConfig: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_FrontendConfig[];
}

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettings {
  azureDnsServers: string[];
  dnsServers: string[];
  useAzureDns: boolean;
}

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Identity {
  identityIds: string[];
  type: string;
}

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile_VnetConfiguration {
  ipOfTrustForUserDefinedRoutes: string;
  trustedSubnetId: string;
  untrustedSubnetId: string;
  virtualNetworkId: string;
}

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile {
  egressNatIpAddressIds: string[];
  egressNatIpAddresses: string[];
  publicIpAddressIds: string[];
  publicIpAddresses: string[];
  trustedAddressRanges: string[];
  vnetConfiguration: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile_VnetConfiguration[];
}

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_BackendConfigFields: FieldMap = {
  port: "port",
  publicIpAddress: "public_ip_address",
};

const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_FrontendConfigFields: FieldMap = {
  port: "port",
  publicIpAddressId: "public_ip_address_id",
};

const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNatFields: FieldMap = {
  name: "name",
  protocol: "protocol",
  backendConfig: {
    wireName: "backend_config",
    kind: "list",
    fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_BackendConfigFields,
  },
  frontendConfig: {
    wireName: "frontend_config",
    kind: "list",
    fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_FrontendConfigFields,
  },
};

const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettingsFields: FieldMap = {
  azureDnsServers: "azure_dns_servers",
  dnsServers: "dns_servers",
  useAzureDns: "use_azure_dns",
};

const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  type: "type",
};

const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile_VnetConfigurationFields: FieldMap = {
  ipOfTrustForUserDefinedRoutes: "ip_of_trust_for_user_defined_routes",
  trustedSubnetId: "trusted_subnet_id",
  untrustedSubnetId: "untrusted_subnet_id",
  virtualNetworkId: "virtual_network_id",
};

const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfileFields: FieldMap = {
  egressNatIpAddressIds: "egress_nat_ip_address_ids",
  egressNatIpAddresses: "egress_nat_ip_addresses",
  publicIpAddressIds: "public_ip_address_ids",
  publicIpAddresses: "public_ip_addresses",
  trustedAddressRanges: "trusted_address_ranges",
  vnetConfiguration: {
    wireName: "vnet_configuration",
    kind: "list",
    fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile_VnetConfigurationFields,
  },
};

const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManagerConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  marketplaceOfferId?: string | Computed<string>;
  name: string | Computed<string>;
  planId?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  strataCloudManagerTenantName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  destinationNat?: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat[] | Computed<AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat[]>;
  dnsSettings?: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettings[] | Computed<AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettings[]>;
  identity?: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Identity[] | Computed<AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Identity[]>;
  networkProfile?: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile[] | Computed<AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile[]>;
  timeouts?: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Timeouts | Computed<AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Timeouts>;
}

export interface AltoNextGenerationFirewallVirtualNetworkStrataCloudManagerAttrs {
  id: string;
  location: string;
  marketplaceOfferId: string;
  name: string;
  planId: string;
  resourceGroupName: string;
  strataCloudManagerTenantName: string;
  tags: Record<string, string>;
  destinationNat: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat[];
  dnsSettings: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettings[];
  identity: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Identity[];
  networkProfile: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile[];
  timeouts: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Timeouts;
}

export const AltoNextGenerationFirewallVirtualNetworkStrataCloudManager: ResourceBinding<AltoNextGenerationFirewallVirtualNetworkStrataCloudManagerConfig, AltoNextGenerationFirewallVirtualNetworkStrataCloudManagerAttrs> = {
  wireType: "azurerm_palo_alto_next_generation_firewall_virtual_network_strata_cloud_manager",
  fields: {
    id: "id",
    location: "location",
    marketplaceOfferId: "marketplace_offer_id",
    name: "name",
    planId: "plan_id",
    resourceGroupName: "resource_group_name",
    strataCloudManagerTenantName: "strata_cloud_manager_tenant_name",
    tags: "tags",
    destinationNat: {
      wireName: "destination_nat",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNatFields,
    },
    dnsSettings: {
      wireName: "dns_settings",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettingsFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_IdentityFields,
    },
    networkProfile: {
      wireName: "network_profile",
      kind: "list",
      fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfileFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_TimeoutsFields,
    },
  },
};
