// Code generated by `ubx sdk gen` from azurerm_palo_alto_local_rulestack_fqdn_list. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AltoLocalRulestackFqdnList_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AltoLocalRulestackFqdnList_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AltoLocalRulestackFqdnListConfig {
  auditComment?: string | Computed<string>;
  description?: string | Computed<string>;
  fullyQualifiedDomainNames: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  rulestackId: string | Computed<string>;
  timeouts?: AltoLocalRulestackFqdnList_Timeouts | Computed<AltoLocalRulestackFqdnList_Timeouts>;
}

export interface AltoLocalRulestackFqdnListAttrs {
  auditComment: string;
  description: string;
  fullyQualifiedDomainNames: string[];
  id: string;
  name: string;
  rulestackId: string;
  timeouts: AltoLocalRulestackFqdnList_Timeouts;
}

export const AltoLocalRulestackFqdnList: ResourceBinding<AltoLocalRulestackFqdnListConfig, AltoLocalRulestackFqdnListAttrs> = {
  wireType: "azurerm_palo_alto_local_rulestack_fqdn_list",
  fields: {
    auditComment: "audit_comment",
    description: "description",
    fullyQualifiedDomainNames: "fully_qualified_domain_names",
    id: "id",
    name: "name",
    rulestackId: "rulestack_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AltoLocalRulestackFqdnList_TimeoutsFields,
    },
  },
};
