// Code generated by `ubx sdk gen` from azurerm_confidential_ledger. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Ledger_AzureadBasedServicePrincipal {
  ledgerRoleName: string;
  principalId: string;
  tenantId: string;
}

export interface Ledger_CertificateBasedSecurityPrincipal {
  ledgerRoleName: string;
  pemPublicKey: string;
}

export interface Ledger_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Ledger_AzureadBasedServicePrincipalFields: FieldMap = {
  ledgerRoleName: "ledger_role_name",
  principalId: "principal_id",
  tenantId: "tenant_id",
};

const Ledger_CertificateBasedSecurityPrincipalFields: FieldMap = {
  ledgerRoleName: "ledger_role_name",
  pemPublicKey: "pem_public_key",
};

const Ledger_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface LedgerConfig {
  id?: string | Computed<string>;
  ledgerType: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  azureadBasedServicePrincipal?: Ledger_AzureadBasedServicePrincipal[] | Computed<Ledger_AzureadBasedServicePrincipal[]>;
  certificateBasedSecurityPrincipal?: Ledger_CertificateBasedSecurityPrincipal[] | Computed<Ledger_CertificateBasedSecurityPrincipal[]>;
  timeouts?: Ledger_Timeouts | Computed<Ledger_Timeouts>;
}

export interface LedgerAttrs {
  id: string;
  identityServiceEndpoint: string;
  ledgerEndpoint: string;
  ledgerType: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  azureadBasedServicePrincipal: Ledger_AzureadBasedServicePrincipal[];
  certificateBasedSecurityPrincipal: Ledger_CertificateBasedSecurityPrincipal[];
  timeouts: Ledger_Timeouts;
}

export const Ledger: ResourceBinding<LedgerConfig, LedgerAttrs> = {
  wireType: "azurerm_confidential_ledger",
  fields: {
    id: "id",
    ledgerType: "ledger_type",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    azureadBasedServicePrincipal: {
      wireName: "azuread_based_service_principal",
      kind: "list",
      fields: Ledger_AzureadBasedServicePrincipalFields,
    },
    certificateBasedSecurityPrincipal: {
      wireName: "certificate_based_security_principal",
      kind: "list",
      fields: Ledger_CertificateBasedSecurityPrincipalFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Ledger_TimeoutsFields,
    },
  },
};
