// Code generated by `ubx sdk gen` from azurerm_kusto_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Cluster_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface Cluster_LanguageExtension {
  image: string;
  name: string;
}

export interface Cluster_OptimizedAutoScale {
  maximumInstances: number;
  minimumInstances: number;
}

export interface Cluster_Sku {
  capacity: number;
  name: string;
}

export interface Cluster_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Cluster_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const Cluster_LanguageExtensionFields: FieldMap = {
  image: "image",
  name: "name",
};

const Cluster_OptimizedAutoScaleFields: FieldMap = {
  maximumInstances: "maximum_instances",
  minimumInstances: "minimum_instances",
};

const Cluster_SkuFields: FieldMap = {
  capacity: "capacity",
  name: "name",
};

const Cluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ClusterConfig {
  allowedFqdns?: string[] | Computed<string[]>;
  allowedIpRanges?: string[] | Computed<string[]>;
  autoStopEnabled?: boolean | Computed<boolean>;
  diskEncryptionEnabled?: boolean | Computed<boolean>;
  doubleEncryptionEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  outboundNetworkAccessRestricted?: boolean | Computed<boolean>;
  publicIpType?: string | Computed<string>;
  publicNetworkAccessEnabled?: boolean | Computed<boolean>;
  purgeEnabled?: boolean | Computed<boolean>;
  resourceGroupName: string | Computed<string>;
  streamingIngestionEnabled?: boolean | Computed<boolean>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  trustedExternalTenants?: string[] | Computed<string[]>;
  zones?: string[] | Computed<string[]>;
  identity?: Cluster_Identity[] | Computed<Cluster_Identity[]>;
  languageExtension?: Cluster_LanguageExtension[] | Computed<Cluster_LanguageExtension[]>;
  optimizedAutoScale?: Cluster_OptimizedAutoScale[] | Computed<Cluster_OptimizedAutoScale[]>;
  sku?: Cluster_Sku[] | Computed<Cluster_Sku[]>;
  timeouts?: Cluster_Timeouts | Computed<Cluster_Timeouts>;
}

export interface ClusterAttrs {
  allowedFqdns: string[];
  allowedIpRanges: string[];
  autoStopEnabled: boolean;
  dataIngestionUri: string;
  diskEncryptionEnabled: boolean;
  doubleEncryptionEnabled: boolean;
  id: string;
  location: string;
  name: string;
  outboundNetworkAccessRestricted: boolean;
  publicIpType: string;
  publicNetworkAccessEnabled: boolean;
  purgeEnabled: boolean;
  resourceGroupName: string;
  streamingIngestionEnabled: boolean;
  tags: Record<string, string>;
  trustedExternalTenants: string[];
  uri: string;
  zones: string[];
  identity: Cluster_Identity[];
  languageExtension: Cluster_LanguageExtension[];
  optimizedAutoScale: Cluster_OptimizedAutoScale[];
  sku: Cluster_Sku[];
  timeouts: Cluster_Timeouts;
}

export const Cluster: ResourceBinding<ClusterConfig, ClusterAttrs> = {
  wireType: "azurerm_kusto_cluster",
  fields: {
    allowedFqdns: "allowed_fqdns",
    allowedIpRanges: "allowed_ip_ranges",
    autoStopEnabled: "auto_stop_enabled",
    diskEncryptionEnabled: "disk_encryption_enabled",
    doubleEncryptionEnabled: "double_encryption_enabled",
    id: "id",
    location: "location",
    name: "name",
    outboundNetworkAccessRestricted: "outbound_network_access_restricted",
    publicIpType: "public_ip_type",
    publicNetworkAccessEnabled: "public_network_access_enabled",
    purgeEnabled: "purge_enabled",
    resourceGroupName: "resource_group_name",
    streamingIngestionEnabled: "streaming_ingestion_enabled",
    tags: "tags",
    trustedExternalTenants: "trusted_external_tenants",
    zones: "zones",
    identity: {
      wireName: "identity",
      kind: "list",
      fields: Cluster_IdentityFields,
    },
    languageExtension: {
      wireName: "language_extension",
      kind: "list",
      fields: Cluster_LanguageExtensionFields,
    },
    optimizedAutoScale: {
      wireName: "optimized_auto_scale",
      kind: "list",
      fields: Cluster_OptimizedAutoScaleFields,
    },
    sku: {
      wireName: "sku",
      kind: "list",
      fields: Cluster_SkuFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Cluster_TimeoutsFields,
    },
  },
};
