// Code generated by `ubx sdk gen` from azurerm_kusto_cluster_managed_private_endpoint. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ClusterManagedPrivateEndpoint_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ClusterManagedPrivateEndpoint_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ClusterManagedPrivateEndpointConfig {
  clusterName: string | Computed<string>;
  groupId: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  privateLinkResourceId: string | Computed<string>;
  privateLinkResourceRegion?: string | Computed<string>;
  requestMessage?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  timeouts?: ClusterManagedPrivateEndpoint_Timeouts | Computed<ClusterManagedPrivateEndpoint_Timeouts>;
}

export interface ClusterManagedPrivateEndpointAttrs {
  clusterName: string;
  groupId: string;
  id: string;
  name: string;
  privateLinkResourceId: string;
  privateLinkResourceRegion: string;
  requestMessage: string;
  resourceGroupName: string;
  timeouts: ClusterManagedPrivateEndpoint_Timeouts;
}

export const ClusterManagedPrivateEndpoint: ResourceBinding<ClusterManagedPrivateEndpointConfig, ClusterManagedPrivateEndpointAttrs> = {
  wireType: "azurerm_kusto_cluster_managed_private_endpoint",
  fields: {
    clusterName: "cluster_name",
    groupId: "group_id",
    id: "id",
    name: "name",
    privateLinkResourceId: "private_link_resource_id",
    privateLinkResourceRegion: "private_link_resource_region",
    requestMessage: "request_message",
    resourceGroupName: "resource_group_name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ClusterManagedPrivateEndpoint_TimeoutsFields,
    },
  },
};
