// Code generated by `ubx sdk gen` from azurerm_batch_job. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Job_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Job_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface JobConfig {
  batchPoolId: string | Computed<string>;
  commonEnvironmentProperties?: Record<string, string> | Computed<Record<string, string>>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  priority?: number | Computed<number>;
  taskRetryMaximum?: number | Computed<number>;
  timeouts?: Job_Timeouts | Computed<Job_Timeouts>;
}

export interface JobAttrs {
  batchPoolId: string;
  commonEnvironmentProperties: Record<string, string>;
  displayName: string;
  id: string;
  name: string;
  priority: number;
  taskRetryMaximum: number;
  timeouts: Job_Timeouts;
}

export const Job: ResourceBinding<JobConfig, JobAttrs> = {
  wireType: "azurerm_batch_job",
  fields: {
    batchPoolId: "batch_pool_id",
    commonEnvironmentProperties: "common_environment_properties",
    displayName: "display_name",
    id: "id",
    name: "name",
    priority: "priority",
    taskRetryMaximum: "task_retry_maximum",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Job_TimeoutsFields,
    },
  },
};
