// Code generated by `ubx sdk gen` from azurerm_batch_pool. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Pool_AutoScale {
  evaluationInterval: string;
  formula: string;
}

export interface Pool_ContainerConfiguration_ContainerRegistries {
  password: string;
  registryServer: string;
  userAssignedIdentityId: string;
  userName: string;
}

export interface Pool_ContainerConfiguration {
  containerImageNames: string[];
  containerRegistries: Pool_ContainerConfiguration_ContainerRegistries[];
  type: string;
}

export interface Pool_DataDisks {
  caching: string;
  diskSizeGb: number;
  lun: number;
  storageAccountType: string;
}

export interface Pool_DiskEncryption {
  diskEncryptionTarget: string;
}

export interface Pool_Extensions {
  autoUpgradeMinorVersion: boolean;
  automaticUpgradeEnabled: boolean;
  name: string;
  protectedSettings: string;
  provisionAfterExtensions: string[];
  publisher: string;
  settingsJson: string;
  type: string;
  typeHandlerVersion: string;
}

export interface Pool_FixedScale {
  nodeDeallocationMethod: string;
  resizeTimeout: string;
  targetDedicatedNodes: number;
  targetLowPriorityNodes: number;
}

export interface Pool_Identity {
  identityIds: string[];
  type: string;
}

export interface Pool_Mount_AzureBlobFileSystem {
  accountKey: string;
  accountName: string;
  blobfuseOptions: string;
  containerName: string;
  identityId: string;
  relativeMountPath: string;
  sasKey: string;
}

export interface Pool_Mount_AzureFileShare {
  accountKey: string;
  accountName: string;
  azureFileUrl: string;
  mountOptions: string;
  relativeMountPath: string;
}

export interface Pool_Mount_CifsMount {
  mountOptions: string;
  password: string;
  relativeMountPath: string;
  source: string;
  userName: string;
}

export interface Pool_Mount_NfsMount {
  mountOptions: string;
  relativeMountPath: string;
  source: string;
}

export interface Pool_Mount {
  azureBlobFileSystem: Pool_Mount_AzureBlobFileSystem[];
  azureFileShare: Pool_Mount_AzureFileShare[];
  cifsMount: Pool_Mount_CifsMount[];
  nfsMount: Pool_Mount_NfsMount[];
}

export interface Pool_NetworkConfiguration_EndpointConfiguration_NetworkSecurityGroupRules {
  access: string;
  priority: number;
  sourceAddressPrefix: string;
  sourcePortRanges: string[];
}

export interface Pool_NetworkConfiguration_EndpointConfiguration {
  backendPort: number;
  frontendPortRange: string;
  name: string;
  protocol: string;
  networkSecurityGroupRules: Pool_NetworkConfiguration_EndpointConfiguration_NetworkSecurityGroupRules[];
}

export interface Pool_NetworkConfiguration {
  acceleratedNetworkingEnabled: boolean;
  dynamicVnetAssignmentScope: string;
  publicAddressProvisioningType: string;
  publicIps: string[];
  subnetId: string;
  endpointConfiguration: Pool_NetworkConfiguration_EndpointConfiguration[];
}

export interface Pool_NodePlacement {
  policy: string;
}

export interface Pool_SecurityProfile {
  hostEncryptionEnabled: boolean;
  secureBootEnabled: boolean;
  securityType: string;
  vtpmEnabled: boolean;
}

export interface Pool_StartTask_Container {
  imageName: string;
  runOptions: string;
  workingDirectory: string;
  registry: Pool_ContainerConfiguration_ContainerRegistries[];
}

export interface Pool_StartTask_ResourceFile {
  autoStorageContainerName: string;
  blobPrefix: string;
  fileMode: string;
  filePath: string;
  httpUrl: string;
  storageContainerUrl: string;
  userAssignedIdentityId: string;
}

export interface Pool_StartTask_UserIdentity_AutoUser {
  elevationLevel: string;
  scope: string;
}

export interface Pool_StartTask_UserIdentity {
  userName: string;
  autoUser: Pool_StartTask_UserIdentity_AutoUser[];
}

export interface Pool_StartTask {
  commandLine: string;
  commonEnvironmentProperties: Record<string, string>;
  taskRetryMaximum: number;
  waitForSuccess: boolean;
  container: Pool_StartTask_Container[];
  resourceFile: Pool_StartTask_ResourceFile[];
  userIdentity: Pool_StartTask_UserIdentity[];
}

export interface Pool_StorageImageReference {
  id: string;
  offer: string;
  publisher: string;
  sku: string;
  version: string;
}

export interface Pool_TaskSchedulingPolicy {
  nodeFillType: string;
}

export interface Pool_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

export interface Pool_UserAccounts_LinuxUserConfiguration {
  gid: number;
  sshPrivateKey: string;
  uid: number;
}

export interface Pool_UserAccounts_WindowsUserConfiguration {
  loginMode: string;
}

export interface Pool_UserAccounts {
  elevationLevel: string;
  name: string;
  password: string;
  linuxUserConfiguration: Pool_UserAccounts_LinuxUserConfiguration[];
  windowsUserConfiguration: Pool_UserAccounts_WindowsUserConfiguration[];
}

export interface Pool_Windows {
  enableAutomaticUpdates: boolean;
}

const Pool_AutoScaleFields: FieldMap = {
  evaluationInterval: "evaluation_interval",
  formula: "formula",
};

const Pool_ContainerConfiguration_ContainerRegistriesFields: FieldMap = {
  password: "password",
  registryServer: "registry_server",
  userAssignedIdentityId: "user_assigned_identity_id",
  userName: "user_name",
};

const Pool_ContainerConfigurationFields: FieldMap = {
  containerImageNames: "container_image_names",
  containerRegistries: {
    wireName: "container_registries",
    kind: "list",
    fields: Pool_ContainerConfiguration_ContainerRegistriesFields,
  },
  type: "type",
};

const Pool_DataDisksFields: FieldMap = {
  caching: "caching",
  diskSizeGb: "disk_size_gb",
  lun: "lun",
  storageAccountType: "storage_account_type",
};

const Pool_DiskEncryptionFields: FieldMap = {
  diskEncryptionTarget: "disk_encryption_target",
};

const Pool_ExtensionsFields: FieldMap = {
  autoUpgradeMinorVersion: "auto_upgrade_minor_version",
  automaticUpgradeEnabled: "automatic_upgrade_enabled",
  name: "name",
  protectedSettings: "protected_settings",
  provisionAfterExtensions: "provision_after_extensions",
  publisher: "publisher",
  settingsJson: "settings_json",
  type: "type",
  typeHandlerVersion: "type_handler_version",
};

const Pool_FixedScaleFields: FieldMap = {
  nodeDeallocationMethod: "node_deallocation_method",
  resizeTimeout: "resize_timeout",
  targetDedicatedNodes: "target_dedicated_nodes",
  targetLowPriorityNodes: "target_low_priority_nodes",
};

const Pool_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  type: "type",
};

const Pool_Mount_AzureBlobFileSystemFields: FieldMap = {
  accountKey: "account_key",
  accountName: "account_name",
  blobfuseOptions: "blobfuse_options",
  containerName: "container_name",
  identityId: "identity_id",
  relativeMountPath: "relative_mount_path",
  sasKey: "sas_key",
};

const Pool_Mount_AzureFileShareFields: FieldMap = {
  accountKey: "account_key",
  accountName: "account_name",
  azureFileUrl: "azure_file_url",
  mountOptions: "mount_options",
  relativeMountPath: "relative_mount_path",
};

const Pool_Mount_CifsMountFields: FieldMap = {
  mountOptions: "mount_options",
  password: "password",
  relativeMountPath: "relative_mount_path",
  source: "source",
  userName: "user_name",
};

const Pool_Mount_NfsMountFields: FieldMap = {
  mountOptions: "mount_options",
  relativeMountPath: "relative_mount_path",
  source: "source",
};

const Pool_MountFields: FieldMap = {
  azureBlobFileSystem: {
    wireName: "azure_blob_file_system",
    kind: "list",
    fields: Pool_Mount_AzureBlobFileSystemFields,
  },
  azureFileShare: {
    wireName: "azure_file_share",
    kind: "list",
    fields: Pool_Mount_AzureFileShareFields,
  },
  cifsMount: {
    wireName: "cifs_mount",
    kind: "list",
    fields: Pool_Mount_CifsMountFields,
  },
  nfsMount: {
    wireName: "nfs_mount",
    kind: "list",
    fields: Pool_Mount_NfsMountFields,
  },
};

const Pool_NetworkConfiguration_EndpointConfiguration_NetworkSecurityGroupRulesFields: FieldMap = {
  access: "access",
  priority: "priority",
  sourceAddressPrefix: "source_address_prefix",
  sourcePortRanges: "source_port_ranges",
};

const Pool_NetworkConfiguration_EndpointConfigurationFields: FieldMap = {
  backendPort: "backend_port",
  frontendPortRange: "frontend_port_range",
  name: "name",
  protocol: "protocol",
  networkSecurityGroupRules: {
    wireName: "network_security_group_rules",
    kind: "list",
    fields: Pool_NetworkConfiguration_EndpointConfiguration_NetworkSecurityGroupRulesFields,
  },
};

const Pool_NetworkConfigurationFields: FieldMap = {
  acceleratedNetworkingEnabled: "accelerated_networking_enabled",
  dynamicVnetAssignmentScope: "dynamic_vnet_assignment_scope",
  publicAddressProvisioningType: "public_address_provisioning_type",
  publicIps: "public_ips",
  subnetId: "subnet_id",
  endpointConfiguration: {
    wireName: "endpoint_configuration",
    kind: "list",
    fields: Pool_NetworkConfiguration_EndpointConfigurationFields,
  },
};

const Pool_NodePlacementFields: FieldMap = {
  policy: "policy",
};

const Pool_SecurityProfileFields: FieldMap = {
  hostEncryptionEnabled: "host_encryption_enabled",
  secureBootEnabled: "secure_boot_enabled",
  securityType: "security_type",
  vtpmEnabled: "vtpm_enabled",
};

const Pool_StartTask_ContainerFields: FieldMap = {
  imageName: "image_name",
  runOptions: "run_options",
  workingDirectory: "working_directory",
  registry: {
    wireName: "registry",
    kind: "list",
    fields: Pool_ContainerConfiguration_ContainerRegistriesFields,
  },
};

const Pool_StartTask_ResourceFileFields: FieldMap = {
  autoStorageContainerName: "auto_storage_container_name",
  blobPrefix: "blob_prefix",
  fileMode: "file_mode",
  filePath: "file_path",
  httpUrl: "http_url",
  storageContainerUrl: "storage_container_url",
  userAssignedIdentityId: "user_assigned_identity_id",
};

const Pool_StartTask_UserIdentity_AutoUserFields: FieldMap = {
  elevationLevel: "elevation_level",
  scope: "scope",
};

const Pool_StartTask_UserIdentityFields: FieldMap = {
  userName: "user_name",
  autoUser: {
    wireName: "auto_user",
    kind: "list",
    fields: Pool_StartTask_UserIdentity_AutoUserFields,
  },
};

const Pool_StartTaskFields: FieldMap = {
  commandLine: "command_line",
  commonEnvironmentProperties: "common_environment_properties",
  taskRetryMaximum: "task_retry_maximum",
  waitForSuccess: "wait_for_success",
  container: {
    wireName: "container",
    kind: "list",
    fields: Pool_StartTask_ContainerFields,
  },
  resourceFile: {
    wireName: "resource_file",
    kind: "list",
    fields: Pool_StartTask_ResourceFileFields,
  },
  userIdentity: {
    wireName: "user_identity",
    kind: "list",
    fields: Pool_StartTask_UserIdentityFields,
  },
};

const Pool_StorageImageReferenceFields: FieldMap = {
  id: "id",
  offer: "offer",
  publisher: "publisher",
  sku: "sku",
  version: "version",
};

const Pool_TaskSchedulingPolicyFields: FieldMap = {
  nodeFillType: "node_fill_type",
};

const Pool_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

const Pool_UserAccounts_LinuxUserConfigurationFields: FieldMap = {
  gid: "gid",
  sshPrivateKey: "ssh_private_key",
  uid: "uid",
};

const Pool_UserAccounts_WindowsUserConfigurationFields: FieldMap = {
  loginMode: "login_mode",
};

const Pool_UserAccountsFields: FieldMap = {
  elevationLevel: "elevation_level",
  name: "name",
  password: "password",
  linuxUserConfiguration: {
    wireName: "linux_user_configuration",
    kind: "list",
    fields: Pool_UserAccounts_LinuxUserConfigurationFields,
  },
  windowsUserConfiguration: {
    wireName: "windows_user_configuration",
    kind: "list",
    fields: Pool_UserAccounts_WindowsUserConfigurationFields,
  },
};

const Pool_WindowsFields: FieldMap = {
  enableAutomaticUpdates: "enable_automatic_updates",
};

export interface PoolConfig {
  accountName: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  interNodeCommunication?: string | Computed<string>;
  licenseType?: string | Computed<string>;
  maxTasksPerNode?: number | Computed<number>;
  metadata?: Record<string, string> | Computed<Record<string, string>>;
  name: string | Computed<string>;
  nodeAgentSkuId: string | Computed<string>;
  osDiskPlacement?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  stopPendingResizeOperation?: boolean | Computed<boolean>;
  targetNodeCommunicationMode?: string | Computed<string>;
  vmSize: string | Computed<string>;
  autoScale?: Pool_AutoScale[] | Computed<Pool_AutoScale[]>;
  containerConfiguration?: Pool_ContainerConfiguration[] | Computed<Pool_ContainerConfiguration[]>;
  dataDisks?: Pool_DataDisks[] | Computed<Pool_DataDisks[]>;
  diskEncryption?: Pool_DiskEncryption[] | Computed<Pool_DiskEncryption[]>;
  extensions?: Pool_Extensions[] | Computed<Pool_Extensions[]>;
  fixedScale?: Pool_FixedScale[] | Computed<Pool_FixedScale[]>;
  identity?: Pool_Identity[] | Computed<Pool_Identity[]>;
  mount?: Pool_Mount[] | Computed<Pool_Mount[]>;
  networkConfiguration?: Pool_NetworkConfiguration[] | Computed<Pool_NetworkConfiguration[]>;
  nodePlacement?: Pool_NodePlacement[] | Computed<Pool_NodePlacement[]>;
  securityProfile?: Pool_SecurityProfile[] | Computed<Pool_SecurityProfile[]>;
  startTask?: Pool_StartTask[] | Computed<Pool_StartTask[]>;
  storageImageReference?: Pool_StorageImageReference[] | Computed<Pool_StorageImageReference[]>;
  taskSchedulingPolicy?: Pool_TaskSchedulingPolicy[] | Computed<Pool_TaskSchedulingPolicy[]>;
  timeouts?: Pool_Timeouts | Computed<Pool_Timeouts>;
  userAccounts?: Pool_UserAccounts[] | Computed<Pool_UserAccounts[]>;
  windows?: Pool_Windows[] | Computed<Pool_Windows[]>;
}

export interface PoolAttrs {
  accountName: string;
  displayName: string;
  id: string;
  interNodeCommunication: string;
  licenseType: string;
  maxTasksPerNode: number;
  metadata: Record<string, string>;
  name: string;
  nodeAgentSkuId: string;
  osDiskPlacement: string;
  resourceGroupName: string;
  stopPendingResizeOperation: boolean;
  targetNodeCommunicationMode: string;
  vmSize: string;
  autoScale: Pool_AutoScale[];
  containerConfiguration: Pool_ContainerConfiguration[];
  dataDisks: Pool_DataDisks[];
  diskEncryption: Pool_DiskEncryption[];
  extensions: Pool_Extensions[];
  fixedScale: Pool_FixedScale[];
  identity: Pool_Identity[];
  mount: Pool_Mount[];
  networkConfiguration: Pool_NetworkConfiguration[];
  nodePlacement: Pool_NodePlacement[];
  securityProfile: Pool_SecurityProfile[];
  startTask: Pool_StartTask[];
  storageImageReference: Pool_StorageImageReference[];
  taskSchedulingPolicy: Pool_TaskSchedulingPolicy[];
  timeouts: Pool_Timeouts;
  userAccounts: Pool_UserAccounts[];
  windows: Pool_Windows[];
}

export const Pool: ResourceBinding<PoolConfig, PoolAttrs> = {
  wireType: "azurerm_batch_pool",
  fields: {
    accountName: "account_name",
    displayName: "display_name",
    id: "id",
    interNodeCommunication: "inter_node_communication",
    licenseType: "license_type",
    maxTasksPerNode: "max_tasks_per_node",
    metadata: "metadata",
    name: "name",
    nodeAgentSkuId: "node_agent_sku_id",
    osDiskPlacement: "os_disk_placement",
    resourceGroupName: "resource_group_name",
    stopPendingResizeOperation: "stop_pending_resize_operation",
    targetNodeCommunicationMode: "target_node_communication_mode",
    vmSize: "vm_size",
    autoScale: {
      wireName: "auto_scale",
      kind: "list",
      fields: Pool_AutoScaleFields,
    },
    containerConfiguration: {
      wireName: "container_configuration",
      kind: "list",
      fields: Pool_ContainerConfigurationFields,
    },
    dataDisks: {
      wireName: "data_disks",
      kind: "list",
      fields: Pool_DataDisksFields,
    },
    diskEncryption: {
      wireName: "disk_encryption",
      kind: "list",
      fields: Pool_DiskEncryptionFields,
    },
    extensions: {
      wireName: "extensions",
      kind: "list",
      fields: Pool_ExtensionsFields,
    },
    fixedScale: {
      wireName: "fixed_scale",
      kind: "list",
      fields: Pool_FixedScaleFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: Pool_IdentityFields,
    },
    mount: {
      wireName: "mount",
      kind: "list",
      fields: Pool_MountFields,
    },
    networkConfiguration: {
      wireName: "network_configuration",
      kind: "list",
      fields: Pool_NetworkConfigurationFields,
    },
    nodePlacement: {
      wireName: "node_placement",
      kind: "list",
      fields: Pool_NodePlacementFields,
    },
    securityProfile: {
      wireName: "security_profile",
      kind: "list",
      fields: Pool_SecurityProfileFields,
    },
    startTask: {
      wireName: "start_task",
      kind: "list",
      fields: Pool_StartTaskFields,
    },
    storageImageReference: {
      wireName: "storage_image_reference",
      kind: "list",
      fields: Pool_StorageImageReferenceFields,
    },
    taskSchedulingPolicy: {
      wireName: "task_scheduling_policy",
      kind: "list",
      fields: Pool_TaskSchedulingPolicyFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Pool_TimeoutsFields,
    },
    userAccounts: {
      wireName: "user_accounts",
      kind: "list",
      fields: Pool_UserAccountsFields,
    },
    windows: {
      wireName: "windows",
      kind: "list",
      fields: Pool_WindowsFields,
    },
  },
};
