// Code generated by `ubx sdk gen` from azurerm_stream_analytics_output_function. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AnalyticsOutputFunction_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AnalyticsOutputFunction_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AnalyticsOutputFunctionConfig {
  apiKey: string | Computed<string>;
  batchMaxCount?: number | Computed<number>;
  batchMaxInBytes?: number | Computed<number>;
  functionApp: string | Computed<string>;
  functionName: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  streamAnalyticsJobName: string | Computed<string>;
  timeouts?: AnalyticsOutputFunction_Timeouts | Computed<AnalyticsOutputFunction_Timeouts>;
}

export interface AnalyticsOutputFunctionAttrs {
  apiKey: string;
  batchMaxCount: number;
  batchMaxInBytes: number;
  functionApp: string;
  functionName: string;
  id: string;
  name: string;
  resourceGroupName: string;
  streamAnalyticsJobName: string;
  timeouts: AnalyticsOutputFunction_Timeouts;
}

export const AnalyticsOutputFunction: ResourceBinding<AnalyticsOutputFunctionConfig, AnalyticsOutputFunctionAttrs> = {
  wireType: "azurerm_stream_analytics_output_function",
  fields: {
    apiKey: "api_key",
    batchMaxCount: "batch_max_count",
    batchMaxInBytes: "batch_max_in_bytes",
    functionApp: "function_app",
    functionName: "function_name",
    id: "id",
    name: "name",
    resourceGroupName: "resource_group_name",
    streamAnalyticsJobName: "stream_analytics_job_name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AnalyticsOutputFunction_TimeoutsFields,
    },
  },
};
