// Code generated by `ubx sdk gen` from azurerm_stream_analytics_output_table. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AnalyticsOutputTable_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AnalyticsOutputTable_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AnalyticsOutputTableConfig {
  batchSize: number | Computed<number>;
  columnsToRemove?: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  partitionKey: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  rowKey: string | Computed<string>;
  storageAccountKey: string | Computed<string>;
  storageAccountName: string | Computed<string>;
  streamAnalyticsJobName: string | Computed<string>;
  table: string | Computed<string>;
  timeouts?: AnalyticsOutputTable_Timeouts | Computed<AnalyticsOutputTable_Timeouts>;
}

export interface AnalyticsOutputTableAttrs {
  batchSize: number;
  columnsToRemove: string[];
  id: string;
  name: string;
  partitionKey: string;
  resourceGroupName: string;
  rowKey: string;
  storageAccountKey: string;
  storageAccountName: string;
  streamAnalyticsJobName: string;
  table: string;
  timeouts: AnalyticsOutputTable_Timeouts;
}

export const AnalyticsOutputTable: ResourceBinding<AnalyticsOutputTableConfig, AnalyticsOutputTableAttrs> = {
  wireType: "azurerm_stream_analytics_output_table",
  fields: {
    batchSize: "batch_size",
    columnsToRemove: "columns_to_remove",
    id: "id",
    name: "name",
    partitionKey: "partition_key",
    resourceGroupName: "resource_group_name",
    rowKey: "row_key",
    storageAccountKey: "storage_account_key",
    storageAccountName: "storage_account_name",
    streamAnalyticsJobName: "stream_analytics_job_name",
    table: "table",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AnalyticsOutputTable_TimeoutsFields,
    },
  },
};
