// Code generated by `ubx sdk gen` from azurerm_stream_analytics_output_synapse. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AnalyticsOutputSynapse_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AnalyticsOutputSynapse_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AnalyticsOutputSynapseConfig {
  database: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  password: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  server: string | Computed<string>;
  streamAnalyticsJobName: string | Computed<string>;
  table: string | Computed<string>;
  user: string | Computed<string>;
  timeouts?: AnalyticsOutputSynapse_Timeouts | Computed<AnalyticsOutputSynapse_Timeouts>;
}

export interface AnalyticsOutputSynapseAttrs {
  database: string;
  id: string;
  name: string;
  password: string;
  resourceGroupName: string;
  server: string;
  streamAnalyticsJobName: string;
  table: string;
  user: string;
  timeouts: AnalyticsOutputSynapse_Timeouts;
}

export const AnalyticsOutputSynapse: ResourceBinding<AnalyticsOutputSynapseConfig, AnalyticsOutputSynapseAttrs> = {
  wireType: "azurerm_stream_analytics_output_synapse",
  fields: {
    database: "database",
    id: "id",
    name: "name",
    password: "password",
    resourceGroupName: "resource_group_name",
    server: "server",
    streamAnalyticsJobName: "stream_analytics_job_name",
    table: "table",
    user: "user",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AnalyticsOutputSynapse_TimeoutsFields,
    },
  },
};
