// Code generated by `ubx sdk gen` from azurerm_stream_analytics_output_cosmosdb. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AnalyticsOutputCosmosdb_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AnalyticsOutputCosmosdb_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AnalyticsOutputCosmosdbConfig {
  authenticationMode?: string | Computed<string>;
  containerName: string | Computed<string>;
  cosmosdbAccountKey: string | Computed<string>;
  cosmosdbSqlDatabaseId: string | Computed<string>;
  documentId?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  partitionKey?: string | Computed<string>;
  streamAnalyticsJobId: string | Computed<string>;
  timeouts?: AnalyticsOutputCosmosdb_Timeouts | Computed<AnalyticsOutputCosmosdb_Timeouts>;
}

export interface AnalyticsOutputCosmosdbAttrs {
  authenticationMode: string;
  containerName: string;
  cosmosdbAccountKey: string;
  cosmosdbSqlDatabaseId: string;
  documentId: string;
  id: string;
  name: string;
  partitionKey: string;
  streamAnalyticsJobId: string;
  timeouts: AnalyticsOutputCosmosdb_Timeouts;
}

export const AnalyticsOutputCosmosdb: ResourceBinding<AnalyticsOutputCosmosdbConfig, AnalyticsOutputCosmosdbAttrs> = {
  wireType: "azurerm_stream_analytics_output_cosmosdb",
  fields: {
    authenticationMode: "authentication_mode",
    containerName: "container_name",
    cosmosdbAccountKey: "cosmosdb_account_key",
    cosmosdbSqlDatabaseId: "cosmosdb_sql_database_id",
    documentId: "document_id",
    id: "id",
    name: "name",
    partitionKey: "partition_key",
    streamAnalyticsJobId: "stream_analytics_job_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AnalyticsOutputCosmosdb_TimeoutsFields,
    },
  },
};
