// Code generated by `ubx sdk gen` from azurerm_oracle_autonomous_database_backup. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AutonomousDatabaseBackup_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AutonomousDatabaseBackup_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AutonomousDatabaseBackupConfig {
  autonomousDatabaseId: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  retentionPeriodInDays: number | Computed<number>;
  type?: string | Computed<string>;
  timeouts?: AutonomousDatabaseBackup_Timeouts | Computed<AutonomousDatabaseBackup_Timeouts>;
}

export interface AutonomousDatabaseBackupAttrs {
  autonomousDatabaseId: string;
  id: string;
  name: string;
  retentionPeriodInDays: number;
  type: string;
  timeouts: AutonomousDatabaseBackup_Timeouts;
}

export const AutonomousDatabaseBackup: ResourceBinding<AutonomousDatabaseBackupConfig, AutonomousDatabaseBackupAttrs> = {
  wireType: "azurerm_oracle_autonomous_database_backup",
  fields: {
    autonomousDatabaseId: "autonomous_database_id",
    id: "id",
    name: "name",
    retentionPeriodInDays: "retention_period_in_days",
    type: "type",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AutonomousDatabaseBackup_TimeoutsFields,
    },
  },
};
