// Code generated by `ubx sdk gen` from azurerm_oracle_exascale_database_storage_vault. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ExascaleDatabaseStorageVault_HighCapacityDatabaseStorage {
  availableSizeInGb: number;
  totalSizeInGb: number;
}

export interface ExascaleDatabaseStorageVault_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ExascaleDatabaseStorageVault_HighCapacityDatabaseStorageFields: FieldMap = {
  availableSizeInGb: "available_size_in_gb",
  totalSizeInGb: "total_size_in_gb",
};

const ExascaleDatabaseStorageVault_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ExascaleDatabaseStorageVaultConfig {
  additionalFlashCachePercentage: number | Computed<number>;
  description?: string | Computed<string>;
  displayName: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeZone?: string | Computed<string>;
  zones: string[] | Computed<string[]>;
  highCapacityDatabaseStorage?: ExascaleDatabaseStorageVault_HighCapacityDatabaseStorage[] | Computed<ExascaleDatabaseStorageVault_HighCapacityDatabaseStorage[]>;
  timeouts?: ExascaleDatabaseStorageVault_Timeouts | Computed<ExascaleDatabaseStorageVault_Timeouts>;
}

export interface ExascaleDatabaseStorageVaultAttrs {
  additionalFlashCachePercentage: number;
  description: string;
  displayName: string;
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  timeZone: string;
  zones: string[];
  highCapacityDatabaseStorage: ExascaleDatabaseStorageVault_HighCapacityDatabaseStorage[];
  timeouts: ExascaleDatabaseStorageVault_Timeouts;
}

export const ExascaleDatabaseStorageVault: ResourceBinding<ExascaleDatabaseStorageVaultConfig, ExascaleDatabaseStorageVaultAttrs> = {
  wireType: "azurerm_oracle_exascale_database_storage_vault",
  fields: {
    additionalFlashCachePercentage: "additional_flash_cache_percentage",
    description: "description",
    displayName: "display_name",
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    timeZone: "time_zone",
    zones: "zones",
    highCapacityDatabaseStorage: {
      wireName: "high_capacity_database_storage",
      kind: "list",
      fields: ExascaleDatabaseStorageVault_HighCapacityDatabaseStorageFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ExascaleDatabaseStorageVault_TimeoutsFields,
    },
  },
};
