// Code generated by `ubx sdk gen` from azurerm_dedicated_hardware_security_module. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HardwareSecurityModule_ManagementNetworkProfile {
  networkInterfacePrivateIpAddresses: string[];
  subnetId: string;
}

export interface HardwareSecurityModule_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const HardwareSecurityModule_ManagementNetworkProfileFields: FieldMap = {
  networkInterfacePrivateIpAddresses: "network_interface_private_ip_addresses",
  subnetId: "subnet_id",
};

const HardwareSecurityModule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface HardwareSecurityModuleConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  skuName: string | Computed<string>;
  stampId?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  zones?: string[] | Computed<string[]>;
  managementNetworkProfile?: HardwareSecurityModule_ManagementNetworkProfile[] | Computed<HardwareSecurityModule_ManagementNetworkProfile[]>;
  networkProfile?: HardwareSecurityModule_ManagementNetworkProfile[] | Computed<HardwareSecurityModule_ManagementNetworkProfile[]>;
  timeouts?: HardwareSecurityModule_Timeouts | Computed<HardwareSecurityModule_Timeouts>;
}

export interface HardwareSecurityModuleAttrs {
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  skuName: string;
  stampId: string;
  tags: Record<string, string>;
  zones: string[];
  managementNetworkProfile: HardwareSecurityModule_ManagementNetworkProfile[];
  networkProfile: HardwareSecurityModule_ManagementNetworkProfile[];
  timeouts: HardwareSecurityModule_Timeouts;
}

export const HardwareSecurityModule: ResourceBinding<HardwareSecurityModuleConfig, HardwareSecurityModuleAttrs> = {
  wireType: "azurerm_dedicated_hardware_security_module",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    skuName: "sku_name",
    stampId: "stamp_id",
    tags: "tags",
    zones: "zones",
    managementNetworkProfile: {
      wireName: "management_network_profile",
      kind: "list",
      fields: HardwareSecurityModule_ManagementNetworkProfileFields,
    },
    networkProfile: {
      wireName: "network_profile",
      kind: "list",
      fields: HardwareSecurityModule_ManagementNetworkProfileFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: HardwareSecurityModule_TimeoutsFields,
    },
  },
};
