// Code generated by `ubx sdk gen` from azurerm_stack_hci_extension. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HciExtension_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const HciExtension_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface HciExtensionConfig {
  arcSettingId: string | Computed<string>;
  autoUpgradeMinorVersionEnabled?: boolean | Computed<boolean>;
  automaticUpgradeEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  protectedSettings?: string | Computed<string>;
  publisher: string | Computed<string>;
  settings?: string | Computed<string>;
  type: string | Computed<string>;
  typeHandlerVersion?: string | Computed<string>;
  timeouts?: HciExtension_Timeouts | Computed<HciExtension_Timeouts>;
}

export interface HciExtensionAttrs {
  arcSettingId: string;
  autoUpgradeMinorVersionEnabled: boolean;
  automaticUpgradeEnabled: boolean;
  id: string;
  name: string;
  protectedSettings: string;
  publisher: string;
  settings: string;
  type: string;
  typeHandlerVersion: string;
  timeouts: HciExtension_Timeouts;
}

export const HciExtension: ResourceBinding<HciExtensionConfig, HciExtensionAttrs> = {
  wireType: "azurerm_stack_hci_extension",
  fields: {
    arcSettingId: "arc_setting_id",
    autoUpgradeMinorVersionEnabled: "auto_upgrade_minor_version_enabled",
    automaticUpgradeEnabled: "automatic_upgrade_enabled",
    id: "id",
    name: "name",
    protectedSettings: "protected_settings",
    publisher: "publisher",
    settings: "settings",
    type: "type",
    typeHandlerVersion: "type_handler_version",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: HciExtension_TimeoutsFields,
    },
  },
};
