// Code generated by `ubx sdk gen` from azurerm_stack_hci_deployment_setting. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HciDeploymentSetting_ScaleUnit_Cluster {
  azureServiceEndpoint: string;
  cloudAccountName: string;
  name: string;
  witnessPath: string;
  witnessType: string;
}

export interface HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_AdapterPropertyOverride {
  jumboPacket: string;
  networkDirect: string;
  networkDirectTechnology: string;
}

export interface HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_QosPolicyOverride {
  bandwidthPercentageSmb: string;
  priorityValue8021ActionCluster: string;
  priorityValue8021ActionSmb: string;
}

export interface HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_VirtualSwitchConfigurationOverride {
  enableIov: string;
  loadBalancingAlgorithm: string;
}

export interface HciDeploymentSetting_ScaleUnit_HostNetwork_Intent {
  adapter: string[];
  adapterPropertyOverrideEnabled: boolean;
  name: string;
  qosPolicyOverrideEnabled: boolean;
  trafficType: string[];
  virtualSwitchConfigurationOverrideEnabled: boolean;
  adapterPropertyOverride: HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_AdapterPropertyOverride[];
  qosPolicyOverride: HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_QosPolicyOverride[];
  virtualSwitchConfigurationOverride: HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_VirtualSwitchConfigurationOverride[];
}

export interface HciDeploymentSetting_ScaleUnit_HostNetwork_StorageNetwork {
  name: string;
  networkAdapterName: string;
  vlanId: string;
}

export interface HciDeploymentSetting_ScaleUnit_HostNetwork {
  storageAutoIpEnabled: boolean;
  storageConnectivitySwitchlessEnabled: boolean;
  intent: HciDeploymentSetting_ScaleUnit_HostNetwork_Intent[];
  storageNetwork: HciDeploymentSetting_ScaleUnit_HostNetwork_StorageNetwork[];
}

export interface HciDeploymentSetting_ScaleUnit_InfrastructureNetwork_IpPool {
  endingAddress: string;
  startingAddress: string;
}

export interface HciDeploymentSetting_ScaleUnit_InfrastructureNetwork {
  dhcpEnabled: boolean;
  dnsServer: string[];
  gateway: string;
  subnetMask: string;
  ipPool: HciDeploymentSetting_ScaleUnit_InfrastructureNetwork_IpPool[];
}

export interface HciDeploymentSetting_ScaleUnit_OptionalService {
  customLocation: string;
}

export interface HciDeploymentSetting_ScaleUnit_PhysicalNode {
  ipv4Address: string;
  name: string;
}

export interface HciDeploymentSetting_ScaleUnit_Storage {
  configurationMode: string;
}

export interface HciDeploymentSetting_ScaleUnit {
  activeDirectoryOrganizationalUnitPath: string;
  bitlockerBootVolumeEnabled: boolean;
  bitlockerDataVolumeEnabled: boolean;
  credentialGuardEnabled: boolean;
  domainFqdn: string;
  driftControlEnabled: boolean;
  drtmProtectionEnabled: boolean;
  episodicDataUploadEnabled: boolean;
  euLocationEnabled: boolean;
  hvciProtectionEnabled: boolean;
  namePrefix: string;
  secretsLocation: string;
  sideChannelMitigationEnabled: boolean;
  smbClusterEncryptionEnabled: boolean;
  smbSigningEnabled: boolean;
  streamingDataClientEnabled: boolean;
  wdacEnabled: boolean;
  cluster: HciDeploymentSetting_ScaleUnit_Cluster[];
  hostNetwork: HciDeploymentSetting_ScaleUnit_HostNetwork[];
  infrastructureNetwork: HciDeploymentSetting_ScaleUnit_InfrastructureNetwork[];
  optionalService: HciDeploymentSetting_ScaleUnit_OptionalService[];
  physicalNode: HciDeploymentSetting_ScaleUnit_PhysicalNode[];
  storage: HciDeploymentSetting_ScaleUnit_Storage[];
}

export interface HciDeploymentSetting_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const HciDeploymentSetting_ScaleUnit_ClusterFields: FieldMap = {
  azureServiceEndpoint: "azure_service_endpoint",
  cloudAccountName: "cloud_account_name",
  name: "name",
  witnessPath: "witness_path",
  witnessType: "witness_type",
};

const HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_AdapterPropertyOverrideFields: FieldMap = {
  jumboPacket: "jumbo_packet",
  networkDirect: "network_direct",
  networkDirectTechnology: "network_direct_technology",
};

const HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_QosPolicyOverrideFields: FieldMap = {
  bandwidthPercentageSmb: "bandwidth_percentage_smb",
  priorityValue8021ActionCluster: "priority_value8021_action_cluster",
  priorityValue8021ActionSmb: "priority_value8021_action_smb",
};

const HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_VirtualSwitchConfigurationOverrideFields: FieldMap = {
  enableIov: "enable_iov",
  loadBalancingAlgorithm: "load_balancing_algorithm",
};

const HciDeploymentSetting_ScaleUnit_HostNetwork_IntentFields: FieldMap = {
  adapter: "adapter",
  adapterPropertyOverrideEnabled: "adapter_property_override_enabled",
  name: "name",
  qosPolicyOverrideEnabled: "qos_policy_override_enabled",
  trafficType: "traffic_type",
  virtualSwitchConfigurationOverrideEnabled: "virtual_switch_configuration_override_enabled",
  adapterPropertyOverride: {
    wireName: "adapter_property_override",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_AdapterPropertyOverrideFields,
  },
  qosPolicyOverride: {
    wireName: "qos_policy_override",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_QosPolicyOverrideFields,
  },
  virtualSwitchConfigurationOverride: {
    wireName: "virtual_switch_configuration_override",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_VirtualSwitchConfigurationOverrideFields,
  },
};

const HciDeploymentSetting_ScaleUnit_HostNetwork_StorageNetworkFields: FieldMap = {
  name: "name",
  networkAdapterName: "network_adapter_name",
  vlanId: "vlan_id",
};

const HciDeploymentSetting_ScaleUnit_HostNetworkFields: FieldMap = {
  storageAutoIpEnabled: "storage_auto_ip_enabled",
  storageConnectivitySwitchlessEnabled: "storage_connectivity_switchless_enabled",
  intent: {
    wireName: "intent",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_HostNetwork_IntentFields,
  },
  storageNetwork: {
    wireName: "storage_network",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_HostNetwork_StorageNetworkFields,
  },
};

const HciDeploymentSetting_ScaleUnit_InfrastructureNetwork_IpPoolFields: FieldMap = {
  endingAddress: "ending_address",
  startingAddress: "starting_address",
};

const HciDeploymentSetting_ScaleUnit_InfrastructureNetworkFields: FieldMap = {
  dhcpEnabled: "dhcp_enabled",
  dnsServer: "dns_server",
  gateway: "gateway",
  subnetMask: "subnet_mask",
  ipPool: {
    wireName: "ip_pool",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_InfrastructureNetwork_IpPoolFields,
  },
};

const HciDeploymentSetting_ScaleUnit_OptionalServiceFields: FieldMap = {
  customLocation: "custom_location",
};

const HciDeploymentSetting_ScaleUnit_PhysicalNodeFields: FieldMap = {
  ipv4Address: "ipv4_address",
  name: "name",
};

const HciDeploymentSetting_ScaleUnit_StorageFields: FieldMap = {
  configurationMode: "configuration_mode",
};

const HciDeploymentSetting_ScaleUnitFields: FieldMap = {
  activeDirectoryOrganizationalUnitPath: "active_directory_organizational_unit_path",
  bitlockerBootVolumeEnabled: "bitlocker_boot_volume_enabled",
  bitlockerDataVolumeEnabled: "bitlocker_data_volume_enabled",
  credentialGuardEnabled: "credential_guard_enabled",
  domainFqdn: "domain_fqdn",
  driftControlEnabled: "drift_control_enabled",
  drtmProtectionEnabled: "drtm_protection_enabled",
  episodicDataUploadEnabled: "episodic_data_upload_enabled",
  euLocationEnabled: "eu_location_enabled",
  hvciProtectionEnabled: "hvci_protection_enabled",
  namePrefix: "name_prefix",
  secretsLocation: "secrets_location",
  sideChannelMitigationEnabled: "side_channel_mitigation_enabled",
  smbClusterEncryptionEnabled: "smb_cluster_encryption_enabled",
  smbSigningEnabled: "smb_signing_enabled",
  streamingDataClientEnabled: "streaming_data_client_enabled",
  wdacEnabled: "wdac_enabled",
  cluster: {
    wireName: "cluster",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_ClusterFields,
  },
  hostNetwork: {
    wireName: "host_network",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_HostNetworkFields,
  },
  infrastructureNetwork: {
    wireName: "infrastructure_network",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_InfrastructureNetworkFields,
  },
  optionalService: {
    wireName: "optional_service",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_OptionalServiceFields,
  },
  physicalNode: {
    wireName: "physical_node",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_PhysicalNodeFields,
  },
  storage: {
    wireName: "storage",
    kind: "list",
    fields: HciDeploymentSetting_ScaleUnit_StorageFields,
  },
};

const HciDeploymentSetting_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface HciDeploymentSettingConfig {
  arcResourceIds: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  stackHciClusterId: string | Computed<string>;
  version: string | Computed<string>;
  scaleUnit?: HciDeploymentSetting_ScaleUnit[] | Computed<HciDeploymentSetting_ScaleUnit[]>;
  timeouts?: HciDeploymentSetting_Timeouts | Computed<HciDeploymentSetting_Timeouts>;
}

export interface HciDeploymentSettingAttrs {
  arcResourceIds: string[];
  id: string;
  stackHciClusterId: string;
  version: string;
  scaleUnit: HciDeploymentSetting_ScaleUnit[];
  timeouts: HciDeploymentSetting_Timeouts;
}

export const HciDeploymentSetting: ResourceBinding<HciDeploymentSettingConfig, HciDeploymentSettingAttrs> = {
  wireType: "azurerm_stack_hci_deployment_setting",
  fields: {
    arcResourceIds: "arc_resource_ids",
    id: "id",
    stackHciClusterId: "stack_hci_cluster_id",
    version: "version",
    scaleUnit: {
      wireName: "scale_unit",
      kind: "list",
      fields: HciDeploymentSetting_ScaleUnitFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: HciDeploymentSetting_TimeoutsFields,
    },
  },
};
