// Code generated by `ubx sdk gen` from azurerm_workloads_sap_three_tier_virtual_instance. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SapThreeTierVirtualInstance_Identity {
  identityIds: string[];
  type: string;
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration_Image {
  offer: string;
  publisher: string;
  sku: string;
  version: string;
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration_OsProfile {
  adminUsername: string;
  sshPrivateKey: string;
  sshPublicKey: string;
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration {
  virtualMachineSize: string;
  image: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration_Image[];
  osProfile: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration_OsProfile[];
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration {
  instanceCount: number;
  subnetId: string;
  virtualMachineConfiguration: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration[];
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_DatabaseServerConfiguration_DiskVolumeConfiguration {
  numberOfDisks: number;
  sizeInGb: number;
  skuName: string;
  volumeName: string;
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_DatabaseServerConfiguration {
  databaseType: string;
  instanceCount: number;
  subnetId: string;
  diskVolumeConfiguration: SapThreeTierVirtualInstance_ThreeTierConfiguration_DatabaseServerConfiguration_DiskVolumeConfiguration[];
  virtualMachineConfiguration: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration[];
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachine_DataDisk {
  names: string[];
  volumeName: string;
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachine {
  hostName: string;
  networkInterfaceNames: string[];
  osDiskName: string;
  virtualMachineName: string;
  dataDisk: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachine_DataDisk[];
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer {
  availabilitySetName: string;
  virtualMachine: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachine[];
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServer_LoadBalancer {
  backendPoolNames: string[];
  frontendIpConfigurationNames: string[];
  healthProbeNames: string[];
  name: string;
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServer {
  availabilitySetName: string;
  loadBalancer: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServer_LoadBalancer[];
  virtualMachine: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachine[];
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_SharedStorage {
  accountName: string;
  privateEndpointName: string;
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames {
  applicationServer: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer[];
  centralServer: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServer[];
  databaseServer: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServer[];
  sharedStorage: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_SharedStorage[];
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration_TransportCreateAndMount {
  resourceGroupId: string;
  storageAccountName: string;
}

export interface SapThreeTierVirtualInstance_ThreeTierConfiguration {
  appResourceGroupName: string;
  highAvailabilityType: string;
  secondaryIpEnabled: boolean;
  applicationServerConfiguration: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration[];
  centralServerConfiguration: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration[];
  databaseServerConfiguration: SapThreeTierVirtualInstance_ThreeTierConfiguration_DatabaseServerConfiguration[];
  resourceNames: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames[];
  transportCreateAndMount: SapThreeTierVirtualInstance_ThreeTierConfiguration_TransportCreateAndMount[];
}

export interface SapThreeTierVirtualInstance_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const SapThreeTierVirtualInstance_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  type: "type",
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration_ImageFields: FieldMap = {
  offer: "offer",
  publisher: "publisher",
  sku: "sku",
  version: "version",
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration_OsProfileFields: FieldMap = {
  adminUsername: "admin_username",
  sshPrivateKey: "ssh_private_key",
  sshPublicKey: "ssh_public_key",
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfigurationFields: FieldMap = {
  virtualMachineSize: "virtual_machine_size",
  image: {
    wireName: "image",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration_ImageFields,
  },
  osProfile: {
    wireName: "os_profile",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfiguration_OsProfileFields,
  },
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfigurationFields: FieldMap = {
  instanceCount: "instance_count",
  subnetId: "subnet_id",
  virtualMachineConfiguration: {
    wireName: "virtual_machine_configuration",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfigurationFields,
  },
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_DatabaseServerConfiguration_DiskVolumeConfigurationFields: FieldMap = {
  numberOfDisks: "number_of_disks",
  sizeInGb: "size_in_gb",
  skuName: "sku_name",
  volumeName: "volume_name",
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_DatabaseServerConfigurationFields: FieldMap = {
  databaseType: "database_type",
  instanceCount: "instance_count",
  subnetId: "subnet_id",
  diskVolumeConfiguration: {
    wireName: "disk_volume_configuration",
    kind: "set",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_DatabaseServerConfiguration_DiskVolumeConfigurationFields,
  },
  virtualMachineConfiguration: {
    wireName: "virtual_machine_configuration",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfiguration_VirtualMachineConfigurationFields,
  },
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachine_DataDiskFields: FieldMap = {
  names: "names",
  volumeName: "volume_name",
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachineFields: FieldMap = {
  hostName: "host_name",
  networkInterfaceNames: "network_interface_names",
  osDiskName: "os_disk_name",
  virtualMachineName: "virtual_machine_name",
  dataDisk: {
    wireName: "data_disk",
    kind: "set",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachine_DataDiskFields,
  },
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServerFields: FieldMap = {
  availabilitySetName: "availability_set_name",
  virtualMachine: {
    wireName: "virtual_machine",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachineFields,
  },
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServer_LoadBalancerFields: FieldMap = {
  backendPoolNames: "backend_pool_names",
  frontendIpConfigurationNames: "frontend_ip_configuration_names",
  healthProbeNames: "health_probe_names",
  name: "name",
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServerFields: FieldMap = {
  availabilitySetName: "availability_set_name",
  loadBalancer: {
    wireName: "load_balancer",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServer_LoadBalancerFields,
  },
  virtualMachine: {
    wireName: "virtual_machine",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServer_VirtualMachineFields,
  },
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_SharedStorageFields: FieldMap = {
  accountName: "account_name",
  privateEndpointName: "private_endpoint_name",
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNamesFields: FieldMap = {
  applicationServer: {
    wireName: "application_server",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_ApplicationServerFields,
  },
  centralServer: {
    wireName: "central_server",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServerFields,
  },
  databaseServer: {
    wireName: "database_server",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_CentralServerFields,
  },
  sharedStorage: {
    wireName: "shared_storage",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNames_SharedStorageFields,
  },
};

const SapThreeTierVirtualInstance_ThreeTierConfiguration_TransportCreateAndMountFields: FieldMap = {
  resourceGroupId: "resource_group_id",
  storageAccountName: "storage_account_name",
};

const SapThreeTierVirtualInstance_ThreeTierConfigurationFields: FieldMap = {
  appResourceGroupName: "app_resource_group_name",
  highAvailabilityType: "high_availability_type",
  secondaryIpEnabled: "secondary_ip_enabled",
  applicationServerConfiguration: {
    wireName: "application_server_configuration",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfigurationFields,
  },
  centralServerConfiguration: {
    wireName: "central_server_configuration",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ApplicationServerConfigurationFields,
  },
  databaseServerConfiguration: {
    wireName: "database_server_configuration",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_DatabaseServerConfigurationFields,
  },
  resourceNames: {
    wireName: "resource_names",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_ResourceNamesFields,
  },
  transportCreateAndMount: {
    wireName: "transport_create_and_mount",
    kind: "list",
    fields: SapThreeTierVirtualInstance_ThreeTierConfiguration_TransportCreateAndMountFields,
  },
};

const SapThreeTierVirtualInstance_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface SapThreeTierVirtualInstanceConfig {
  appLocation: string | Computed<string>;
  environment: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  managedResourceGroupName?: string | Computed<string>;
  managedResourcesNetworkAccessType?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  sapFqdn: string | Computed<string>;
  sapProduct: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  identity?: SapThreeTierVirtualInstance_Identity[] | Computed<SapThreeTierVirtualInstance_Identity[]>;
  threeTierConfiguration?: SapThreeTierVirtualInstance_ThreeTierConfiguration[] | Computed<SapThreeTierVirtualInstance_ThreeTierConfiguration[]>;
  timeouts?: SapThreeTierVirtualInstance_Timeouts | Computed<SapThreeTierVirtualInstance_Timeouts>;
}

export interface SapThreeTierVirtualInstanceAttrs {
  appLocation: string;
  environment: string;
  id: string;
  location: string;
  managedResourceGroupName: string;
  managedResourcesNetworkAccessType: string;
  name: string;
  resourceGroupName: string;
  sapFqdn: string;
  sapProduct: string;
  tags: Record<string, string>;
  identity: SapThreeTierVirtualInstance_Identity[];
  threeTierConfiguration: SapThreeTierVirtualInstance_ThreeTierConfiguration[];
  timeouts: SapThreeTierVirtualInstance_Timeouts;
}

export const SapThreeTierVirtualInstance: ResourceBinding<SapThreeTierVirtualInstanceConfig, SapThreeTierVirtualInstanceAttrs> = {
  wireType: "azurerm_workloads_sap_three_tier_virtual_instance",
  fields: {
    appLocation: "app_location",
    environment: "environment",
    id: "id",
    location: "location",
    managedResourceGroupName: "managed_resource_group_name",
    managedResourcesNetworkAccessType: "managed_resources_network_access_type",
    name: "name",
    resourceGroupName: "resource_group_name",
    sapFqdn: "sap_fqdn",
    sapProduct: "sap_product",
    tags: "tags",
    identity: {
      wireName: "identity",
      kind: "list",
      fields: SapThreeTierVirtualInstance_IdentityFields,
    },
    threeTierConfiguration: {
      wireName: "three_tier_configuration",
      kind: "list",
      fields: SapThreeTierVirtualInstance_ThreeTierConfigurationFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SapThreeTierVirtualInstance_TimeoutsFields,
    },
  },
};
