// Code generated by `ubx sdk gen` from azurerm_security_center_storage_defender. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CenterStorageDefender_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const CenterStorageDefender_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface CenterStorageDefenderConfig {
  id?: string | Computed<string>;
  malwareScanningOnUploadCapGbPerMonth?: number | Computed<number>;
  malwareScanningOnUploadEnabled?: boolean | Computed<boolean>;
  overrideSubscriptionSettingsEnabled?: boolean | Computed<boolean>;
  scanResultsEventGridTopicId?: string | Computed<string>;
  sensitiveDataDiscoveryEnabled?: boolean | Computed<boolean>;
  storageAccountId: string | Computed<string>;
  timeouts?: CenterStorageDefender_Timeouts | Computed<CenterStorageDefender_Timeouts>;
}

export interface CenterStorageDefenderAttrs {
  id: string;
  malwareScanningOnUploadCapGbPerMonth: number;
  malwareScanningOnUploadEnabled: boolean;
  overrideSubscriptionSettingsEnabled: boolean;
  scanResultsEventGridTopicId: string;
  sensitiveDataDiscoveryEnabled: boolean;
  storageAccountId: string;
  timeouts: CenterStorageDefender_Timeouts;
}

export const CenterStorageDefender: ResourceBinding<CenterStorageDefenderConfig, CenterStorageDefenderAttrs> = {
  wireType: "azurerm_security_center_storage_defender",
  fields: {
    id: "id",
    malwareScanningOnUploadCapGbPerMonth: "malware_scanning_on_upload_cap_gb_per_month",
    malwareScanningOnUploadEnabled: "malware_scanning_on_upload_enabled",
    overrideSubscriptionSettingsEnabled: "override_subscription_settings_enabled",
    scanResultsEventGridTopicId: "scan_results_event_grid_topic_id",
    sensitiveDataDiscoveryEnabled: "sensitive_data_discovery_enabled",
    storageAccountId: "storage_account_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CenterStorageDefender_TimeoutsFields,
    },
  },
};
