// Code generated by `ubx sdk gen` from azurerm_cost_management_scheduled_action. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagementScheduledAction_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ManagementScheduledAction_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ManagementScheduledActionConfig {
  dayOfMonth?: number | Computed<number>;
  daysOfWeek?: string[] | Computed<string[]>;
  displayName: string | Computed<string>;
  emailAddressSender: string | Computed<string>;
  emailAddresses: string[] | Computed<string[]>;
  emailSubject: string | Computed<string>;
  endDate: string | Computed<string>;
  frequency: string | Computed<string>;
  hourOfDay?: number | Computed<number>;
  id?: string | Computed<string>;
  message?: string | Computed<string>;
  name: string | Computed<string>;
  startDate: string | Computed<string>;
  viewId: string | Computed<string>;
  weeksOfMonth?: string[] | Computed<string[]>;
  timeouts?: ManagementScheduledAction_Timeouts | Computed<ManagementScheduledAction_Timeouts>;
}

export interface ManagementScheduledActionAttrs {
  dayOfMonth: number;
  daysOfWeek: string[];
  displayName: string;
  emailAddressSender: string;
  emailAddresses: string[];
  emailSubject: string;
  endDate: string;
  frequency: string;
  hourOfDay: number;
  id: string;
  message: string;
  name: string;
  startDate: string;
  viewId: string;
  weeksOfMonth: string[];
  timeouts: ManagementScheduledAction_Timeouts;
}

export const ManagementScheduledAction: ResourceBinding<ManagementScheduledActionConfig, ManagementScheduledActionAttrs> = {
  wireType: "azurerm_cost_management_scheduled_action",
  fields: {
    dayOfMonth: "day_of_month",
    daysOfWeek: "days_of_week",
    displayName: "display_name",
    emailAddressSender: "email_address_sender",
    emailAddresses: "email_addresses",
    emailSubject: "email_subject",
    endDate: "end_date",
    frequency: "frequency",
    hourOfDay: "hour_of_day",
    id: "id",
    message: "message",
    name: "name",
    startDate: "start_date",
    viewId: "view_id",
    weeksOfMonth: "weeks_of_month",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagementScheduledAction_TimeoutsFields,
    },
  },
};
