// Code generated by `ubx sdk gen` from azurerm_log_analytics_query_pack. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AnalyticsQueryPack_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AnalyticsQueryPack_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AnalyticsQueryPackConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: AnalyticsQueryPack_Timeouts | Computed<AnalyticsQueryPack_Timeouts>;
}

export interface AnalyticsQueryPackAttrs {
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  timeouts: AnalyticsQueryPack_Timeouts;
}

export const AnalyticsQueryPack: ResourceBinding<AnalyticsQueryPackConfig, AnalyticsQueryPackAttrs> = {
  wireType: "azurerm_log_analytics_query_pack",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AnalyticsQueryPack_TimeoutsFields,
    },
  },
};
