// Code generated by `ubx sdk gen` from azurerm_log_analytics_solution. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AnalyticsSolution_Plan {
  name: string;
  product: string;
  promotionCode: string;
  publisher: string;
}

export interface AnalyticsSolution_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AnalyticsSolution_PlanFields: FieldMap = {
  name: "name",
  product: "product",
  promotionCode: "promotion_code",
  publisher: "publisher",
};

const AnalyticsSolution_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AnalyticsSolutionConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  solutionName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  workspaceName: string | Computed<string>;
  workspaceResourceId: string | Computed<string>;
  plan?: AnalyticsSolution_Plan[] | Computed<AnalyticsSolution_Plan[]>;
  timeouts?: AnalyticsSolution_Timeouts | Computed<AnalyticsSolution_Timeouts>;
}

export interface AnalyticsSolutionAttrs {
  id: string;
  location: string;
  resourceGroupName: string;
  solutionName: string;
  tags: Record<string, string>;
  workspaceName: string;
  workspaceResourceId: string;
  plan: AnalyticsSolution_Plan[];
  timeouts: AnalyticsSolution_Timeouts;
}

export const AnalyticsSolution: ResourceBinding<AnalyticsSolutionConfig, AnalyticsSolutionAttrs> = {
  wireType: "azurerm_log_analytics_solution",
  fields: {
    id: "id",
    location: "location",
    resourceGroupName: "resource_group_name",
    solutionName: "solution_name",
    tags: "tags",
    workspaceName: "workspace_name",
    workspaceResourceId: "workspace_resource_id",
    plan: {
      wireName: "plan",
      kind: "list",
      fields: AnalyticsSolution_PlanFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AnalyticsSolution_TimeoutsFields,
    },
  },
};
