// Code generated by `ubx sdk gen` from azurerm_bot_channel_facebook. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ChannelFacebook_Page {
  accessToken: string;
  id: string;
}

export interface ChannelFacebook_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ChannelFacebook_PageFields: FieldMap = {
  accessToken: "access_token",
  id: "id",
};

const ChannelFacebook_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ChannelFacebookConfig {
  botName: string | Computed<string>;
  facebookApplicationId: string | Computed<string>;
  facebookApplicationSecret: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  page?: ChannelFacebook_Page[] | Computed<ChannelFacebook_Page[]>;
  timeouts?: ChannelFacebook_Timeouts | Computed<ChannelFacebook_Timeouts>;
}

export interface ChannelFacebookAttrs {
  botName: string;
  facebookApplicationId: string;
  facebookApplicationSecret: string;
  id: string;
  location: string;
  resourceGroupName: string;
  page: ChannelFacebook_Page[];
  timeouts: ChannelFacebook_Timeouts;
}

export const ChannelFacebook: ResourceBinding<ChannelFacebookConfig, ChannelFacebookAttrs> = {
  wireType: "azurerm_bot_channel_facebook",
  fields: {
    botName: "bot_name",
    facebookApplicationId: "facebook_application_id",
    facebookApplicationSecret: "facebook_application_secret",
    id: "id",
    location: "location",
    resourceGroupName: "resource_group_name",
    page: {
      wireName: "page",
      kind: "set",
      fields: ChannelFacebook_PageFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ChannelFacebook_TimeoutsFields,
    },
  },
};
