// Code generated by `ubx sdk gen` from azurerm_bot_channel_alexa. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ChannelAlexa_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ChannelAlexa_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ChannelAlexaConfig {
  botName: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  skillId: string | Computed<string>;
  timeouts?: ChannelAlexa_Timeouts | Computed<ChannelAlexa_Timeouts>;
}

export interface ChannelAlexaAttrs {
  botName: string;
  id: string;
  location: string;
  resourceGroupName: string;
  skillId: string;
  timeouts: ChannelAlexa_Timeouts;
}

export const ChannelAlexa: ResourceBinding<ChannelAlexaConfig, ChannelAlexaAttrs> = {
  wireType: "azurerm_bot_channel_alexa",
  fields: {
    botName: "bot_name",
    id: "id",
    location: "location",
    resourceGroupName: "resource_group_name",
    skillId: "skill_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ChannelAlexa_TimeoutsFields,
    },
  },
};
