// Code generated by `ubx sdk gen` from azurerm_eventhub_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Cluster_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Cluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ClusterConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  skuName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: Cluster_Timeouts | Computed<Cluster_Timeouts>;
}

export interface ClusterAttrs {
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  skuName: string;
  tags: Record<string, string>;
  timeouts: Cluster_Timeouts;
}

export const Cluster: ResourceBinding<ClusterConfig, ClusterAttrs> = {
  wireType: "azurerm_eventhub_cluster",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    skuName: "sku_name",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Cluster_TimeoutsFields,
    },
  },
};
