// Code generated by `ubx sdk gen` from azurerm_network_interface_security_group_association. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface InterfaceSecurityGroupAssociation_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const InterfaceSecurityGroupAssociation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface InterfaceSecurityGroupAssociationConfig {
  id?: string | Computed<string>;
  networkInterfaceId: string | Computed<string>;
  networkSecurityGroupId: string | Computed<string>;
  timeouts?: InterfaceSecurityGroupAssociation_Timeouts | Computed<InterfaceSecurityGroupAssociation_Timeouts>;
}

export interface InterfaceSecurityGroupAssociationAttrs {
  id: string;
  networkInterfaceId: string;
  networkSecurityGroupId: string;
  timeouts: InterfaceSecurityGroupAssociation_Timeouts;
}

export const InterfaceSecurityGroupAssociation: ResourceBinding<InterfaceSecurityGroupAssociationConfig, InterfaceSecurityGroupAssociationAttrs> = {
  wireType: "azurerm_network_interface_security_group_association",
  fields: {
    id: "id",
    networkInterfaceId: "network_interface_id",
    networkSecurityGroupId: "network_security_group_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: InterfaceSecurityGroupAssociation_TimeoutsFields,
    },
  },
};
