// Code generated by `ubx sdk gen` from azurerm_network_manager_verifier_workspace_reachability_analysis_intent. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTraffic {
  destinationIps: string[];
  destinationPorts: string[];
  protocols: string[];
  sourceIps: string[];
  sourcePorts: string[];
}

export interface ManagerVerifierWorkspaceReachabilityAnalysisIntent_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTrafficFields: FieldMap = {
  destinationIps: "destination_ips",
  destinationPorts: "destination_ports",
  protocols: "protocols",
  sourceIps: "source_ips",
  sourcePorts: "source_ports",
};

const ManagerVerifierWorkspaceReachabilityAnalysisIntent_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface ManagerVerifierWorkspaceReachabilityAnalysisIntentConfig {
  description?: string | Computed<string>;
  destinationResourceId: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  sourceResourceId: string | Computed<string>;
  verifierWorkspaceId: string | Computed<string>;
  ipTraffic?: ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTraffic[] | Computed<ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTraffic[]>;
  timeouts?: ManagerVerifierWorkspaceReachabilityAnalysisIntent_Timeouts | Computed<ManagerVerifierWorkspaceReachabilityAnalysisIntent_Timeouts>;
}

export interface ManagerVerifierWorkspaceReachabilityAnalysisIntentAttrs {
  description: string;
  destinationResourceId: string;
  id: string;
  name: string;
  sourceResourceId: string;
  verifierWorkspaceId: string;
  ipTraffic: ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTraffic[];
  timeouts: ManagerVerifierWorkspaceReachabilityAnalysisIntent_Timeouts;
}

export const ManagerVerifierWorkspaceReachabilityAnalysisIntent: ResourceBinding<ManagerVerifierWorkspaceReachabilityAnalysisIntentConfig, ManagerVerifierWorkspaceReachabilityAnalysisIntentAttrs> = {
  wireType: "azurerm_network_manager_verifier_workspace_reachability_analysis_intent",
  fields: {
    description: "description",
    destinationResourceId: "destination_resource_id",
    id: "id",
    name: "name",
    sourceResourceId: "source_resource_id",
    verifierWorkspaceId: "verifier_workspace_id",
    ipTraffic: {
      wireName: "ip_traffic",
      kind: "list",
      fields: ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTrafficFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagerVerifierWorkspaceReachabilityAnalysisIntent_TimeoutsFields,
    },
  },
};
