// Code generated by `ubx sdk gen` from azurerm_network_manager_verifier_workspace. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagerVerifierWorkspace_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ManagerVerifierWorkspace_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ManagerVerifierWorkspaceConfig {
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  networkManagerId: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: ManagerVerifierWorkspace_Timeouts | Computed<ManagerVerifierWorkspace_Timeouts>;
}

export interface ManagerVerifierWorkspaceAttrs {
  description: string;
  id: string;
  location: string;
  name: string;
  networkManagerId: string;
  tags: Record<string, string>;
  timeouts: ManagerVerifierWorkspace_Timeouts;
}

export const ManagerVerifierWorkspace: ResourceBinding<ManagerVerifierWorkspaceConfig, ManagerVerifierWorkspaceAttrs> = {
  wireType: "azurerm_network_manager_verifier_workspace",
  fields: {
    description: "description",
    id: "id",
    location: "location",
    name: "name",
    networkManagerId: "network_manager_id",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagerVerifierWorkspace_TimeoutsFields,
    },
  },
};
