// Code generated by `ubx sdk gen` from azurerm_datadog_monitor. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Monitor_DatadogOrganization {
  apiKey: string;
  applicationKey: string;
  enterpriseAppId: string;
  id: string;
  linkingAuthCode: string;
  linkingClientId: string;
  name: string;
  redirectUri: string;
}

export interface Monitor_Identity {
  principalId: string;
  tenantId: string;
  type: string;
}

export interface Monitor_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

export interface Monitor_User {
  email: string;
  name: string;
  phoneNumber: string;
}

const Monitor_DatadogOrganizationFields: FieldMap = {
  apiKey: "api_key",
  applicationKey: "application_key",
  enterpriseAppId: "enterprise_app_id",
  id: "id",
  linkingAuthCode: "linking_auth_code",
  linkingClientId: "linking_client_id",
  name: "name",
  redirectUri: "redirect_uri",
};

const Monitor_IdentityFields: FieldMap = {
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const Monitor_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

const Monitor_UserFields: FieldMap = {
  email: "email",
  name: "name",
  phoneNumber: "phone_number",
};

export interface MonitorConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  monitoringEnabled?: boolean | Computed<boolean>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  skuName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  datadogOrganization?: Monitor_DatadogOrganization[] | Computed<Monitor_DatadogOrganization[]>;
  identity?: Monitor_Identity[] | Computed<Monitor_Identity[]>;
  timeouts?: Monitor_Timeouts | Computed<Monitor_Timeouts>;
  user?: Monitor_User[] | Computed<Monitor_User[]>;
}

export interface MonitorAttrs {
  id: string;
  location: string;
  marketplaceSubscriptionStatus: string;
  monitoringEnabled: boolean;
  name: string;
  resourceGroupName: string;
  skuName: string;
  tags: Record<string, string>;
  datadogOrganization: Monitor_DatadogOrganization[];
  identity: Monitor_Identity[];
  timeouts: Monitor_Timeouts;
  user: Monitor_User[];
}

export const Monitor: ResourceBinding<MonitorConfig, MonitorAttrs> = {
  wireType: "azurerm_datadog_monitor",
  fields: {
    id: "id",
    location: "location",
    monitoringEnabled: "monitoring_enabled",
    name: "name",
    resourceGroupName: "resource_group_name",
    skuName: "sku_name",
    tags: "tags",
    datadogOrganization: {
      wireName: "datadog_organization",
      kind: "list",
      fields: Monitor_DatadogOrganizationFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: Monitor_IdentityFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Monitor_TimeoutsFields,
    },
    user: {
      wireName: "user",
      kind: "list",
      fields: Monitor_UserFields,
    },
  },
};
