// Code generated by `ubx sdk gen` from azurerm_synapse_firewall_rule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FirewallRule_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FirewallRule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FirewallRuleConfig {
  endIpAddress: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  startIpAddress: string | Computed<string>;
  synapseWorkspaceId: string | Computed<string>;
  timeouts?: FirewallRule_Timeouts | Computed<FirewallRule_Timeouts>;
}

export interface FirewallRuleAttrs {
  endIpAddress: string;
  id: string;
  name: string;
  startIpAddress: string;
  synapseWorkspaceId: string;
  timeouts: FirewallRule_Timeouts;
}

export const FirewallRule: ResourceBinding<FirewallRuleConfig, FirewallRuleAttrs> = {
  wireType: "azurerm_synapse_firewall_rule",
  fields: {
    endIpAddress: "end_ip_address",
    id: "id",
    name: "name",
    startIpAddress: "start_ip_address",
    synapseWorkspaceId: "synapse_workspace_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FirewallRule_TimeoutsFields,
    },
  },
};
