// Code generated by `ubx sdk gen` from azurerm_synapse_managed_private_endpoint. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagedPrivateEndpoint_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const ManagedPrivateEndpoint_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface ManagedPrivateEndpointConfig {
  fullyQualifiedDomainNames?: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  subresourceName: string | Computed<string>;
  synapseWorkspaceId: string | Computed<string>;
  targetResourceId: string | Computed<string>;
  timeouts?: ManagedPrivateEndpoint_Timeouts | Computed<ManagedPrivateEndpoint_Timeouts>;
}

export interface ManagedPrivateEndpointAttrs {
  fullyQualifiedDomainNames: string[];
  id: string;
  name: string;
  subresourceName: string;
  synapseWorkspaceId: string;
  targetResourceId: string;
  timeouts: ManagedPrivateEndpoint_Timeouts;
}

export const ManagedPrivateEndpoint: ResourceBinding<ManagedPrivateEndpointConfig, ManagedPrivateEndpointAttrs> = {
  wireType: "azurerm_synapse_managed_private_endpoint",
  fields: {
    fullyQualifiedDomainNames: "fully_qualified_domain_names",
    id: "id",
    name: "name",
    subresourceName: "subresource_name",
    synapseWorkspaceId: "synapse_workspace_id",
    targetResourceId: "target_resource_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagedPrivateEndpoint_TimeoutsFields,
    },
  },
};
