// Code generated by `ubx sdk gen` from azurerm_synapse_role_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RoleAssignment_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const RoleAssignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface RoleAssignmentConfig {
  id?: string | Computed<string>;
  principalId: string | Computed<string>;
  principalType?: string | Computed<string>;
  roleName: string | Computed<string>;
  synapseSparkPoolId?: string | Computed<string>;
  synapseWorkspaceId?: string | Computed<string>;
  timeouts?: RoleAssignment_Timeouts | Computed<RoleAssignment_Timeouts>;
}

export interface RoleAssignmentAttrs {
  id: string;
  principalId: string;
  principalType: string;
  roleName: string;
  synapseSparkPoolId: string;
  synapseWorkspaceId: string;
  timeouts: RoleAssignment_Timeouts;
}

export const RoleAssignment: ResourceBinding<RoleAssignmentConfig, RoleAssignmentAttrs> = {
  wireType: "azurerm_synapse_role_assignment",
  fields: {
    id: "id",
    principalId: "principal_id",
    principalType: "principal_type",
    roleName: "role_name",
    synapseSparkPoolId: "synapse_spark_pool_id",
    synapseWorkspaceId: "synapse_workspace_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: RoleAssignment_TimeoutsFields,
    },
  },
};
