// Code generated by `ubx sdk gen` from azurerm_synapse_sql_pool_workload_group. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SqlPoolWorkloadGroup_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const SqlPoolWorkloadGroup_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface SqlPoolWorkloadGroupConfig {
  id?: string | Computed<string>;
  importance?: string | Computed<string>;
  maxResourcePercent: number | Computed<number>;
  maxResourcePercentPerRequest?: number | Computed<number>;
  minResourcePercent: number | Computed<number>;
  minResourcePercentPerRequest?: number | Computed<number>;
  name: string | Computed<string>;
  queryExecutionTimeoutInSeconds?: number | Computed<number>;
  sqlPoolId: string | Computed<string>;
  timeouts?: SqlPoolWorkloadGroup_Timeouts | Computed<SqlPoolWorkloadGroup_Timeouts>;
}

export interface SqlPoolWorkloadGroupAttrs {
  id: string;
  importance: string;
  maxResourcePercent: number;
  maxResourcePercentPerRequest: number;
  minResourcePercent: number;
  minResourcePercentPerRequest: number;
  name: string;
  queryExecutionTimeoutInSeconds: number;
  sqlPoolId: string;
  timeouts: SqlPoolWorkloadGroup_Timeouts;
}

export const SqlPoolWorkloadGroup: ResourceBinding<SqlPoolWorkloadGroupConfig, SqlPoolWorkloadGroupAttrs> = {
  wireType: "azurerm_synapse_sql_pool_workload_group",
  fields: {
    id: "id",
    importance: "importance",
    maxResourcePercent: "max_resource_percent",
    maxResourcePercentPerRequest: "max_resource_percent_per_request",
    minResourcePercent: "min_resource_percent",
    minResourcePercentPerRequest: "min_resource_percent_per_request",
    name: "name",
    queryExecutionTimeoutInSeconds: "query_execution_timeout_in_seconds",
    sqlPoolId: "sql_pool_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SqlPoolWorkloadGroup_TimeoutsFields,
    },
  },
};
