// Code generated by `ubx sdk gen` from azurerm_dev_test_schedule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface TestSchedule_DailyRecurrence {
  time: string;
}

export interface TestSchedule_HourlyRecurrence {
  minute: number;
}

export interface TestSchedule_NotificationSettings {
  status: string;
  timeInMinutes: number;
  webhookUrl: string;
}

export interface TestSchedule_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

export interface TestSchedule_WeeklyRecurrence {
  time: string;
  weekDays: string[];
}

const TestSchedule_DailyRecurrenceFields: FieldMap = {
  time: "time",
};

const TestSchedule_HourlyRecurrenceFields: FieldMap = {
  minute: "minute",
};

const TestSchedule_NotificationSettingsFields: FieldMap = {
  status: "status",
  timeInMinutes: "time_in_minutes",
  webhookUrl: "webhook_url",
};

const TestSchedule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

const TestSchedule_WeeklyRecurrenceFields: FieldMap = {
  time: "time",
  weekDays: "week_days",
};

export interface TestScheduleConfig {
  id?: string | Computed<string>;
  labName: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  status?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  taskType: string | Computed<string>;
  timeZoneId: string | Computed<string>;
  dailyRecurrence?: TestSchedule_DailyRecurrence[] | Computed<TestSchedule_DailyRecurrence[]>;
  hourlyRecurrence?: TestSchedule_HourlyRecurrence[] | Computed<TestSchedule_HourlyRecurrence[]>;
  notificationSettings?: TestSchedule_NotificationSettings[] | Computed<TestSchedule_NotificationSettings[]>;
  timeouts?: TestSchedule_Timeouts | Computed<TestSchedule_Timeouts>;
  weeklyRecurrence?: TestSchedule_WeeklyRecurrence[] | Computed<TestSchedule_WeeklyRecurrence[]>;
}

export interface TestScheduleAttrs {
  id: string;
  labName: string;
  location: string;
  name: string;
  resourceGroupName: string;
  status: string;
  tags: Record<string, string>;
  taskType: string;
  timeZoneId: string;
  dailyRecurrence: TestSchedule_DailyRecurrence[];
  hourlyRecurrence: TestSchedule_HourlyRecurrence[];
  notificationSettings: TestSchedule_NotificationSettings[];
  timeouts: TestSchedule_Timeouts;
  weeklyRecurrence: TestSchedule_WeeklyRecurrence[];
}

export const TestSchedule: ResourceBinding<TestScheduleConfig, TestScheduleAttrs> = {
  wireType: "azurerm_dev_test_schedule",
  fields: {
    id: "id",
    labName: "lab_name",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    status: "status",
    tags: "tags",
    taskType: "task_type",
    timeZoneId: "time_zone_id",
    dailyRecurrence: {
      wireName: "daily_recurrence",
      kind: "list",
      fields: TestSchedule_DailyRecurrenceFields,
    },
    hourlyRecurrence: {
      wireName: "hourly_recurrence",
      kind: "list",
      fields: TestSchedule_HourlyRecurrenceFields,
    },
    notificationSettings: {
      wireName: "notification_settings",
      kind: "list",
      fields: TestSchedule_NotificationSettingsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: TestSchedule_TimeoutsFields,
    },
    weeklyRecurrence: {
      wireName: "weekly_recurrence",
      kind: "list",
      fields: TestSchedule_WeeklyRecurrenceFields,
    },
  },
};
