// Code generated by `ubx sdk gen` from azurerm_pim_eligible_role_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EligibleRoleAssignment_Schedule_Expiration {
  durationDays: number;
  durationHours: number;
  endDateTime: string;
}

export interface EligibleRoleAssignment_Schedule {
  startDateTime: string;
  expiration: EligibleRoleAssignment_Schedule_Expiration[];
}

export interface EligibleRoleAssignment_Ticket {
  number: string;
  system: string;
}

export interface EligibleRoleAssignment_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const EligibleRoleAssignment_Schedule_ExpirationFields: FieldMap = {
  durationDays: "duration_days",
  durationHours: "duration_hours",
  endDateTime: "end_date_time",
};

const EligibleRoleAssignment_ScheduleFields: FieldMap = {
  startDateTime: "start_date_time",
  expiration: {
    wireName: "expiration",
    kind: "list",
    fields: EligibleRoleAssignment_Schedule_ExpirationFields,
  },
};

const EligibleRoleAssignment_TicketFields: FieldMap = {
  number: "number",
  system: "system",
};

const EligibleRoleAssignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface EligibleRoleAssignmentConfig {
  condition?: string | Computed<string>;
  conditionVersion?: string | Computed<string>;
  id?: string | Computed<string>;
  justification?: string | Computed<string>;
  principalId: string | Computed<string>;
  roleDefinitionId: string | Computed<string>;
  scope: string | Computed<string>;
  schedule?: EligibleRoleAssignment_Schedule[] | Computed<EligibleRoleAssignment_Schedule[]>;
  ticket?: EligibleRoleAssignment_Ticket[] | Computed<EligibleRoleAssignment_Ticket[]>;
  timeouts?: EligibleRoleAssignment_Timeouts | Computed<EligibleRoleAssignment_Timeouts>;
}

export interface EligibleRoleAssignmentAttrs {
  condition: string;
  conditionVersion: string;
  id: string;
  justification: string;
  principalId: string;
  principalType: string;
  roleDefinitionId: string;
  scope: string;
  schedule: EligibleRoleAssignment_Schedule[];
  ticket: EligibleRoleAssignment_Ticket[];
  timeouts: EligibleRoleAssignment_Timeouts;
}

export const EligibleRoleAssignment: ResourceBinding<EligibleRoleAssignmentConfig, EligibleRoleAssignmentAttrs> = {
  wireType: "azurerm_pim_eligible_role_assignment",
  fields: {
    condition: "condition",
    conditionVersion: "condition_version",
    id: "id",
    justification: "justification",
    principalId: "principal_id",
    roleDefinitionId: "role_definition_id",
    scope: "scope",
    schedule: {
      wireName: "schedule",
      kind: "list",
      fields: EligibleRoleAssignment_ScheduleFields,
    },
    ticket: {
      wireName: "ticket",
      kind: "list",
      fields: EligibleRoleAssignment_TicketFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: EligibleRoleAssignment_TimeoutsFields,
    },
  },
};
