// Code generated by `ubx sdk gen` from azurerm_managed_application. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Application_Plan {
  name: string;
  product: string;
  promotionCode: string;
  publisher: string;
  version: string;
}

export interface Application_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Application_PlanFields: FieldMap = {
  name: "name",
  product: "product",
  promotionCode: "promotion_code",
  publisher: "publisher",
  version: "version",
};

const Application_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ApplicationConfig {
  applicationDefinitionId?: string | Computed<string>;
  id?: string | Computed<string>;
  kind: string | Computed<string>;
  location: string | Computed<string>;
  managedResourceGroupName: string | Computed<string>;
  name: string | Computed<string>;
  parameterValues?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  plan?: Application_Plan[] | Computed<Application_Plan[]>;
  timeouts?: Application_Timeouts | Computed<Application_Timeouts>;
}

export interface ApplicationAttrs {
  applicationDefinitionId: string;
  id: string;
  kind: string;
  location: string;
  managedResourceGroupName: string;
  name: string;
  outputs: Record<string, string>;
  parameterValues: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  plan: Application_Plan[];
  timeouts: Application_Timeouts;
}

export const Application: ResourceBinding<ApplicationConfig, ApplicationAttrs> = {
  wireType: "azurerm_managed_application",
  fields: {
    applicationDefinitionId: "application_definition_id",
    id: "id",
    kind: "kind",
    location: "location",
    managedResourceGroupName: "managed_resource_group_name",
    name: "name",
    parameterValues: "parameter_values",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    plan: {
      wireName: "plan",
      kind: "list",
      fields: Application_PlanFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Application_TimeoutsFields,
    },
  },
};
