// Code generated by `ubx sdk gen` from azurerm_managed_redis_access_policy_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RedisAccessPolicyAssignment_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const RedisAccessPolicyAssignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface RedisAccessPolicyAssignmentConfig {
  id?: string | Computed<string>;
  managedRedisId: string | Computed<string>;
  objectId: string | Computed<string>;
  timeouts?: RedisAccessPolicyAssignment_Timeouts | Computed<RedisAccessPolicyAssignment_Timeouts>;
}

export interface RedisAccessPolicyAssignmentAttrs {
  id: string;
  managedRedisId: string;
  objectId: string;
  timeouts: RedisAccessPolicyAssignment_Timeouts;
}

export const RedisAccessPolicyAssignment: ResourceBinding<RedisAccessPolicyAssignmentConfig, RedisAccessPolicyAssignmentAttrs> = {
  wireType: "azurerm_managed_redis_access_policy_assignment",
  fields: {
    id: "id",
    managedRedisId: "managed_redis_id",
    objectId: "object_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: RedisAccessPolicyAssignment_TimeoutsFields,
    },
  },
};
