// Code generated by `ubx sdk gen` from azurerm_container_app_environment_managed_certificate. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AppEnvironmentManagedCertificate_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AppEnvironmentManagedCertificate_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AppEnvironmentManagedCertificateConfig {
  containerAppEnvironmentId: string | Computed<string>;
  domainControlValidation?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  subjectName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: AppEnvironmentManagedCertificate_Timeouts | Computed<AppEnvironmentManagedCertificate_Timeouts>;
}

export interface AppEnvironmentManagedCertificateAttrs {
  containerAppEnvironmentId: string;
  domainControlValidation: string;
  id: string;
  name: string;
  subjectName: string;
  tags: Record<string, string>;
  validationToken: string;
  timeouts: AppEnvironmentManagedCertificate_Timeouts;
}

export const AppEnvironmentManagedCertificate: ResourceBinding<AppEnvironmentManagedCertificateConfig, AppEnvironmentManagedCertificateAttrs> = {
  wireType: "azurerm_container_app_environment_managed_certificate",
  fields: {
    containerAppEnvironmentId: "container_app_environment_id",
    domainControlValidation: "domain_control_validation",
    id: "id",
    name: "name",
    subjectName: "subject_name",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AppEnvironmentManagedCertificate_TimeoutsFields,
    },
  },
};
