// Code generated by `ubx sdk gen` from azurerm_container_registry_credential_set. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RegistryCredentialSet_AuthenticationCredentials {
  passwordSecretId: string;
  usernameSecretId: string;
}

export interface RegistryCredentialSet_Identity {
  principalId: string;
  tenantId: string;
  type: string;
}

export interface RegistryCredentialSet_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const RegistryCredentialSet_AuthenticationCredentialsFields: FieldMap = {
  passwordSecretId: "password_secret_id",
  usernameSecretId: "username_secret_id",
};

const RegistryCredentialSet_IdentityFields: FieldMap = {
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const RegistryCredentialSet_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface RegistryCredentialSetConfig {
  containerRegistryId: string | Computed<string>;
  id?: string | Computed<string>;
  loginServer: string | Computed<string>;
  name: string | Computed<string>;
  authenticationCredentials?: RegistryCredentialSet_AuthenticationCredentials[] | Computed<RegistryCredentialSet_AuthenticationCredentials[]>;
  identity?: RegistryCredentialSet_Identity[] | Computed<RegistryCredentialSet_Identity[]>;
  timeouts?: RegistryCredentialSet_Timeouts | Computed<RegistryCredentialSet_Timeouts>;
}

export interface RegistryCredentialSetAttrs {
  containerRegistryId: string;
  id: string;
  loginServer: string;
  name: string;
  authenticationCredentials: RegistryCredentialSet_AuthenticationCredentials[];
  identity: RegistryCredentialSet_Identity[];
  timeouts: RegistryCredentialSet_Timeouts;
}

export const RegistryCredentialSet: ResourceBinding<RegistryCredentialSetConfig, RegistryCredentialSetAttrs> = {
  wireType: "azurerm_container_registry_credential_set",
  fields: {
    containerRegistryId: "container_registry_id",
    id: "id",
    loginServer: "login_server",
    name: "name",
    authenticationCredentials: {
      wireName: "authentication_credentials",
      kind: "list",
      fields: RegistryCredentialSet_AuthenticationCredentialsFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: RegistryCredentialSet_IdentityFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: RegistryCredentialSet_TimeoutsFields,
    },
  },
};
