// Code generated by `ubx sdk gen` from azurerm_container_registry_task. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RegistryTask_AgentSetting {
  cpu: number;
}

export interface RegistryTask_BaseImageTrigger {
  enabled: boolean;
  name: string;
  type: string;
  updateTriggerEndpoint: string;
  updateTriggerPayloadType: string;
}

export interface RegistryTask_DockerStep {
  arguments: Record<string, string>;
  cacheEnabled: boolean;
  contextAccessToken: string;
  contextPath: string;
  dockerfilePath: string;
  imageNames: string[];
  pushEnabled: boolean;
  secretArguments: Record<string, string>;
  target: string;
}

export interface RegistryTask_EncodedStep {
  contextAccessToken: string;
  contextPath: string;
  secretValues: Record<string, string>;
  taskContent: string;
  valueContent: string;
  values: Record<string, string>;
}

export interface RegistryTask_FileStep {
  contextAccessToken: string;
  contextPath: string;
  secretValues: Record<string, string>;
  taskFilePath: string;
  valueFilePath: string;
  values: Record<string, string>;
}

export interface RegistryTask_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface RegistryTask_Platform {
  architecture: string;
  os: string;
  variant: string;
}

export interface RegistryTask_RegistryCredential_Custom {
  identity: string;
  loginServer: string;
  password: string;
  username: string;
}

export interface RegistryTask_RegistryCredential_Source {
  loginMode: string;
}

export interface RegistryTask_RegistryCredential {
  custom: RegistryTask_RegistryCredential_Custom[];
  source: RegistryTask_RegistryCredential_Source[];
}

export interface RegistryTask_SourceTrigger_Authentication {
  expireInSeconds: number;
  refreshToken: string;
  scope: string;
  token: string;
  tokenType: string;
}

export interface RegistryTask_SourceTrigger {
  branch: string;
  enabled: boolean;
  events: string[];
  name: string;
  repositoryUrl: string;
  sourceType: string;
  authentication: RegistryTask_SourceTrigger_Authentication[];
}

export interface RegistryTask_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

export interface RegistryTask_TimerTrigger {
  enabled: boolean;
  name: string;
  schedule: string;
}

const RegistryTask_AgentSettingFields: FieldMap = {
  cpu: "cpu",
};

const RegistryTask_BaseImageTriggerFields: FieldMap = {
  enabled: "enabled",
  name: "name",
  type: "type",
  updateTriggerEndpoint: "update_trigger_endpoint",
  updateTriggerPayloadType: "update_trigger_payload_type",
};

const RegistryTask_DockerStepFields: FieldMap = {
  arguments: "arguments",
  cacheEnabled: "cache_enabled",
  contextAccessToken: "context_access_token",
  contextPath: "context_path",
  dockerfilePath: "dockerfile_path",
  imageNames: "image_names",
  pushEnabled: "push_enabled",
  secretArguments: "secret_arguments",
  target: "target",
};

const RegistryTask_EncodedStepFields: FieldMap = {
  contextAccessToken: "context_access_token",
  contextPath: "context_path",
  secretValues: "secret_values",
  taskContent: "task_content",
  valueContent: "value_content",
  values: "values",
};

const RegistryTask_FileStepFields: FieldMap = {
  contextAccessToken: "context_access_token",
  contextPath: "context_path",
  secretValues: "secret_values",
  taskFilePath: "task_file_path",
  valueFilePath: "value_file_path",
  values: "values",
};

const RegistryTask_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const RegistryTask_PlatformFields: FieldMap = {
  architecture: "architecture",
  os: "os",
  variant: "variant",
};

const RegistryTask_RegistryCredential_CustomFields: FieldMap = {
  identity: "identity",
  loginServer: "login_server",
  password: "password",
  username: "username",
};

const RegistryTask_RegistryCredential_SourceFields: FieldMap = {
  loginMode: "login_mode",
};

const RegistryTask_RegistryCredentialFields: FieldMap = {
  custom: {
    wireName: "custom",
    kind: "set",
    fields: RegistryTask_RegistryCredential_CustomFields,
  },
  source: {
    wireName: "source",
    kind: "list",
    fields: RegistryTask_RegistryCredential_SourceFields,
  },
};

const RegistryTask_SourceTrigger_AuthenticationFields: FieldMap = {
  expireInSeconds: "expire_in_seconds",
  refreshToken: "refresh_token",
  scope: "scope",
  token: "token",
  tokenType: "token_type",
};

const RegistryTask_SourceTriggerFields: FieldMap = {
  branch: "branch",
  enabled: "enabled",
  events: "events",
  name: "name",
  repositoryUrl: "repository_url",
  sourceType: "source_type",
  authentication: {
    wireName: "authentication",
    kind: "list",
    fields: RegistryTask_SourceTrigger_AuthenticationFields,
  },
};

const RegistryTask_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

const RegistryTask_TimerTriggerFields: FieldMap = {
  enabled: "enabled",
  name: "name",
  schedule: "schedule",
};

export interface RegistryTaskConfig {
  agentPoolName?: string | Computed<string>;
  containerRegistryId: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  isSystemTask?: boolean | Computed<boolean>;
  logTemplate?: string | Computed<string>;
  name: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeoutInSeconds?: number | Computed<number>;
  agentSetting?: RegistryTask_AgentSetting[] | Computed<RegistryTask_AgentSetting[]>;
  baseImageTrigger?: RegistryTask_BaseImageTrigger[] | Computed<RegistryTask_BaseImageTrigger[]>;
  dockerStep?: RegistryTask_DockerStep[] | Computed<RegistryTask_DockerStep[]>;
  encodedStep?: RegistryTask_EncodedStep[] | Computed<RegistryTask_EncodedStep[]>;
  fileStep?: RegistryTask_FileStep[] | Computed<RegistryTask_FileStep[]>;
  identity?: RegistryTask_Identity[] | Computed<RegistryTask_Identity[]>;
  platform?: RegistryTask_Platform[] | Computed<RegistryTask_Platform[]>;
  registryCredential?: RegistryTask_RegistryCredential[] | Computed<RegistryTask_RegistryCredential[]>;
  sourceTrigger?: RegistryTask_SourceTrigger[] | Computed<RegistryTask_SourceTrigger[]>;
  timeouts?: RegistryTask_Timeouts | Computed<RegistryTask_Timeouts>;
  timerTrigger?: RegistryTask_TimerTrigger[] | Computed<RegistryTask_TimerTrigger[]>;
}

export interface RegistryTaskAttrs {
  agentPoolName: string;
  containerRegistryId: string;
  enabled: boolean;
  id: string;
  isSystemTask: boolean;
  logTemplate: string;
  name: string;
  tags: Record<string, string>;
  timeoutInSeconds: number;
  agentSetting: RegistryTask_AgentSetting[];
  baseImageTrigger: RegistryTask_BaseImageTrigger[];
  dockerStep: RegistryTask_DockerStep[];
  encodedStep: RegistryTask_EncodedStep[];
  fileStep: RegistryTask_FileStep[];
  identity: RegistryTask_Identity[];
  platform: RegistryTask_Platform[];
  registryCredential: RegistryTask_RegistryCredential[];
  sourceTrigger: RegistryTask_SourceTrigger[];
  timeouts: RegistryTask_Timeouts;
  timerTrigger: RegistryTask_TimerTrigger[];
}

export const RegistryTask: ResourceBinding<RegistryTaskConfig, RegistryTaskAttrs> = {
  wireType: "azurerm_container_registry_task",
  fields: {
    agentPoolName: "agent_pool_name",
    containerRegistryId: "container_registry_id",
    enabled: "enabled",
    id: "id",
    isSystemTask: "is_system_task",
    logTemplate: "log_template",
    name: "name",
    tags: "tags",
    timeoutInSeconds: "timeout_in_seconds",
    agentSetting: {
      wireName: "agent_setting",
      kind: "list",
      fields: RegistryTask_AgentSettingFields,
    },
    baseImageTrigger: {
      wireName: "base_image_trigger",
      kind: "list",
      fields: RegistryTask_BaseImageTriggerFields,
    },
    dockerStep: {
      wireName: "docker_step",
      kind: "list",
      fields: RegistryTask_DockerStepFields,
    },
    encodedStep: {
      wireName: "encoded_step",
      kind: "list",
      fields: RegistryTask_EncodedStepFields,
    },
    fileStep: {
      wireName: "file_step",
      kind: "list",
      fields: RegistryTask_FileStepFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: RegistryTask_IdentityFields,
    },
    platform: {
      wireName: "platform",
      kind: "list",
      fields: RegistryTask_PlatformFields,
    },
    registryCredential: {
      wireName: "registry_credential",
      kind: "list",
      fields: RegistryTask_RegistryCredentialFields,
    },
    sourceTrigger: {
      wireName: "source_trigger",
      kind: "list",
      fields: RegistryTask_SourceTriggerFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: RegistryTask_TimeoutsFields,
    },
    timerTrigger: {
      wireName: "timer_trigger",
      kind: "list",
      fields: RegistryTask_TimerTriggerFields,
    },
  },
};
