// Code generated by `ubx sdk gen` from azurerm_storage_account. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Account_AzureFilesAuthentication_ActiveDirectory {
  domainGuid: string;
  domainName: string;
  domainSid: string;
  forestName: string;
  netbiosDomainName: string;
  storageSid: string;
}

export interface Account_AzureFilesAuthentication {
  defaultShareLevelPermission: string;
  directoryType: string;
  activeDirectory: Account_AzureFilesAuthentication_ActiveDirectory[];
}

export interface Account_BlobProperties_ContainerDeleteRetentionPolicy {
  days: number;
}

export interface Account_BlobProperties_CorsRule {
  allowedHeaders: string[];
  allowedMethods: string[];
  allowedOrigins: string[];
  exposedHeaders: string[];
  maxAgeInSeconds: number;
}

export interface Account_BlobProperties_DeleteRetentionPolicy {
  days: number;
  permanentDeleteEnabled: boolean;
}

export interface Account_BlobProperties {
  changeFeedEnabled: boolean;
  changeFeedRetentionInDays: number;
  defaultServiceVersion: string;
  lastAccessTimeEnabled: boolean;
  versioningEnabled: boolean;
  containerDeleteRetentionPolicy: Account_BlobProperties_ContainerDeleteRetentionPolicy[];
  corsRule: Account_BlobProperties_CorsRule[];
  deleteRetentionPolicy: Account_BlobProperties_DeleteRetentionPolicy[];
  restorePolicy: Account_BlobProperties_ContainerDeleteRetentionPolicy[];
}

export interface Account_CustomDomain {
  name: string;
  useSubdomain: boolean;
}

export interface Account_CustomerManagedKey {
  keyVaultKeyId: string;
  userAssignedIdentityId: string;
}

export interface Account_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface Account_ImmutabilityPolicy {
  allowProtectedAppendWrites: boolean;
  periodSinceCreationInDays: number;
  state: string;
}

export interface Account_NetworkRules_PrivateLinkAccess {
  endpointResourceId: string;
  endpointTenantId: string;
}

export interface Account_NetworkRules {
  bypass: string[];
  defaultAction: string;
  ipRules: string[];
  virtualNetworkSubnetIds: string[];
  privateLinkAccess: Account_NetworkRules_PrivateLinkAccess[];
}

export interface Account_Routing {
  choice: string;
  publishInternetEndpoints: boolean;
  publishMicrosoftEndpoints: boolean;
}

export interface Account_SasPolicy {
  expirationAction: string;
  expirationPeriod: string;
}

export interface Account_ShareProperties_Smb {
  authenticationTypes: string[];
  channelEncryptionType: string[];
  kerberosTicketEncryptionType: string[];
  multichannelEnabled: boolean;
  versions: string[];
}

export interface Account_ShareProperties {
  corsRule: Account_BlobProperties_CorsRule[];
  retentionPolicy: Account_BlobProperties_ContainerDeleteRetentionPolicy[];
  smb: Account_ShareProperties_Smb[];
}

export interface Account_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Account_AzureFilesAuthentication_ActiveDirectoryFields: FieldMap = {
  domainGuid: "domain_guid",
  domainName: "domain_name",
  domainSid: "domain_sid",
  forestName: "forest_name",
  netbiosDomainName: "netbios_domain_name",
  storageSid: "storage_sid",
};

const Account_AzureFilesAuthenticationFields: FieldMap = {
  defaultShareLevelPermission: "default_share_level_permission",
  directoryType: "directory_type",
  activeDirectory: {
    wireName: "active_directory",
    kind: "list",
    fields: Account_AzureFilesAuthentication_ActiveDirectoryFields,
  },
};

const Account_BlobProperties_ContainerDeleteRetentionPolicyFields: FieldMap = {
  days: "days",
};

const Account_BlobProperties_CorsRuleFields: FieldMap = {
  allowedHeaders: "allowed_headers",
  allowedMethods: "allowed_methods",
  allowedOrigins: "allowed_origins",
  exposedHeaders: "exposed_headers",
  maxAgeInSeconds: "max_age_in_seconds",
};

const Account_BlobProperties_DeleteRetentionPolicyFields: FieldMap = {
  days: "days",
  permanentDeleteEnabled: "permanent_delete_enabled",
};

const Account_BlobPropertiesFields: FieldMap = {
  changeFeedEnabled: "change_feed_enabled",
  changeFeedRetentionInDays: "change_feed_retention_in_days",
  defaultServiceVersion: "default_service_version",
  lastAccessTimeEnabled: "last_access_time_enabled",
  versioningEnabled: "versioning_enabled",
  containerDeleteRetentionPolicy: {
    wireName: "container_delete_retention_policy",
    kind: "list",
    fields: Account_BlobProperties_ContainerDeleteRetentionPolicyFields,
  },
  corsRule: {
    wireName: "cors_rule",
    kind: "list",
    fields: Account_BlobProperties_CorsRuleFields,
  },
  deleteRetentionPolicy: {
    wireName: "delete_retention_policy",
    kind: "list",
    fields: Account_BlobProperties_DeleteRetentionPolicyFields,
  },
  restorePolicy: {
    wireName: "restore_policy",
    kind: "list",
    fields: Account_BlobProperties_ContainerDeleteRetentionPolicyFields,
  },
};

const Account_CustomDomainFields: FieldMap = {
  name: "name",
  useSubdomain: "use_subdomain",
};

const Account_CustomerManagedKeyFields: FieldMap = {
  keyVaultKeyId: "key_vault_key_id",
  userAssignedIdentityId: "user_assigned_identity_id",
};

const Account_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const Account_ImmutabilityPolicyFields: FieldMap = {
  allowProtectedAppendWrites: "allow_protected_append_writes",
  periodSinceCreationInDays: "period_since_creation_in_days",
  state: "state",
};

const Account_NetworkRules_PrivateLinkAccessFields: FieldMap = {
  endpointResourceId: "endpoint_resource_id",
  endpointTenantId: "endpoint_tenant_id",
};

const Account_NetworkRulesFields: FieldMap = {
  bypass: "bypass",
  defaultAction: "default_action",
  ipRules: "ip_rules",
  virtualNetworkSubnetIds: "virtual_network_subnet_ids",
  privateLinkAccess: {
    wireName: "private_link_access",
    kind: "list",
    fields: Account_NetworkRules_PrivateLinkAccessFields,
  },
};

const Account_RoutingFields: FieldMap = {
  choice: "choice",
  publishInternetEndpoints: "publish_internet_endpoints",
  publishMicrosoftEndpoints: "publish_microsoft_endpoints",
};

const Account_SasPolicyFields: FieldMap = {
  expirationAction: "expiration_action",
  expirationPeriod: "expiration_period",
};

const Account_ShareProperties_SmbFields: FieldMap = {
  authenticationTypes: "authentication_types",
  channelEncryptionType: "channel_encryption_type",
  kerberosTicketEncryptionType: "kerberos_ticket_encryption_type",
  multichannelEnabled: "multichannel_enabled",
  versions: "versions",
};

const Account_SharePropertiesFields: FieldMap = {
  corsRule: {
    wireName: "cors_rule",
    kind: "list",
    fields: Account_BlobProperties_CorsRuleFields,
  },
  retentionPolicy: {
    wireName: "retention_policy",
    kind: "list",
    fields: Account_BlobProperties_ContainerDeleteRetentionPolicyFields,
  },
  smb: {
    wireName: "smb",
    kind: "list",
    fields: Account_ShareProperties_SmbFields,
  },
};

const Account_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AccountConfig {
  accessTier?: string | Computed<string>;
  accountKind?: string | Computed<string>;
  accountReplicationType: string | Computed<string>;
  accountTier: string | Computed<string>;
  allowNestedItemsToBePublic?: boolean | Computed<boolean>;
  allowedCopyScope?: string | Computed<string>;
  crossTenantReplicationEnabled?: boolean | Computed<boolean>;
  defaultToOauthAuthentication?: boolean | Computed<boolean>;
  dnsEndpointType?: string | Computed<string>;
  edgeZone?: string | Computed<string>;
  httpsTrafficOnlyEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  infrastructureEncryptionEnabled?: boolean | Computed<boolean>;
  isHnsEnabled?: boolean | Computed<boolean>;
  largeFileShareEnabled?: boolean | Computed<boolean>;
  localUserEnabled?: boolean | Computed<boolean>;
  location: string | Computed<string>;
  minTlsVersion?: string | Computed<string>;
  name: string | Computed<string>;
  nfsv3Enabled?: boolean | Computed<boolean>;
  provisionedBillingModelVersion?: string | Computed<string>;
  publicNetworkAccessEnabled?: boolean | Computed<boolean>;
  queueEncryptionKeyType?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  sftpEnabled?: boolean | Computed<boolean>;
  sharedAccessKeyEnabled?: boolean | Computed<boolean>;
  tableEncryptionKeyType?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  azureFilesAuthentication?: Account_AzureFilesAuthentication[] | Computed<Account_AzureFilesAuthentication[]>;
  blobProperties?: Account_BlobProperties[] | Computed<Account_BlobProperties[]>;
  customDomain?: Account_CustomDomain[] | Computed<Account_CustomDomain[]>;
  customerManagedKey?: Account_CustomerManagedKey[] | Computed<Account_CustomerManagedKey[]>;
  identity?: Account_Identity[] | Computed<Account_Identity[]>;
  immutabilityPolicy?: Account_ImmutabilityPolicy[] | Computed<Account_ImmutabilityPolicy[]>;
  networkRules?: Account_NetworkRules[] | Computed<Account_NetworkRules[]>;
  routing?: Account_Routing[] | Computed<Account_Routing[]>;
  sasPolicy?: Account_SasPolicy[] | Computed<Account_SasPolicy[]>;
  shareProperties?: Account_ShareProperties[] | Computed<Account_ShareProperties[]>;
  timeouts?: Account_Timeouts | Computed<Account_Timeouts>;
}

export interface AccountAttrs {
  accessTier: string;
  accountKind: string;
  accountReplicationType: string;
  accountTier: string;
  allowNestedItemsToBePublic: boolean;
  allowedCopyScope: string;
  crossTenantReplicationEnabled: boolean;
  defaultToOauthAuthentication: boolean;
  dnsEndpointType: string;
  edgeZone: string;
  httpsTrafficOnlyEnabled: boolean;
  id: string;
  infrastructureEncryptionEnabled: boolean;
  isHnsEnabled: boolean;
  largeFileShareEnabled: boolean;
  localUserEnabled: boolean;
  location: string;
  minTlsVersion: string;
  name: string;
  nfsv3Enabled: boolean;
  primaryAccessKey: string;
  primaryBlobConnectionString: string;
  primaryBlobEndpoint: string;
  primaryBlobHost: string;
  primaryBlobInternetEndpoint: string;
  primaryBlobInternetHost: string;
  primaryBlobMicrosoftEndpoint: string;
  primaryBlobMicrosoftHost: string;
  primaryConnectionString: string;
  primaryDfsEndpoint: string;
  primaryDfsHost: string;
  primaryDfsInternetEndpoint: string;
  primaryDfsInternetHost: string;
  primaryDfsMicrosoftEndpoint: string;
  primaryDfsMicrosoftHost: string;
  primaryFileEndpoint: string;
  primaryFileHost: string;
  primaryFileInternetEndpoint: string;
  primaryFileInternetHost: string;
  primaryFileMicrosoftEndpoint: string;
  primaryFileMicrosoftHost: string;
  primaryLocation: string;
  primaryQueueEndpoint: string;
  primaryQueueHost: string;
  primaryQueueMicrosoftEndpoint: string;
  primaryQueueMicrosoftHost: string;
  primaryTableEndpoint: string;
  primaryTableHost: string;
  primaryTableMicrosoftEndpoint: string;
  primaryTableMicrosoftHost: string;
  primaryWebEndpoint: string;
  primaryWebHost: string;
  primaryWebInternetEndpoint: string;
  primaryWebInternetHost: string;
  primaryWebMicrosoftEndpoint: string;
  primaryWebMicrosoftHost: string;
  provisionedBillingModelVersion: string;
  publicNetworkAccessEnabled: boolean;
  queueEncryptionKeyType: string;
  resourceGroupName: string;
  secondaryAccessKey: string;
  secondaryBlobConnectionString: string;
  secondaryBlobEndpoint: string;
  secondaryBlobHost: string;
  secondaryBlobInternetEndpoint: string;
  secondaryBlobInternetHost: string;
  secondaryBlobMicrosoftEndpoint: string;
  secondaryBlobMicrosoftHost: string;
  secondaryConnectionString: string;
  secondaryDfsEndpoint: string;
  secondaryDfsHost: string;
  secondaryDfsInternetEndpoint: string;
  secondaryDfsInternetHost: string;
  secondaryDfsMicrosoftEndpoint: string;
  secondaryDfsMicrosoftHost: string;
  secondaryFileEndpoint: string;
  secondaryFileHost: string;
  secondaryFileInternetEndpoint: string;
  secondaryFileInternetHost: string;
  secondaryFileMicrosoftEndpoint: string;
  secondaryFileMicrosoftHost: string;
  secondaryLocation: string;
  secondaryQueueEndpoint: string;
  secondaryQueueHost: string;
  secondaryQueueMicrosoftEndpoint: string;
  secondaryQueueMicrosoftHost: string;
  secondaryTableEndpoint: string;
  secondaryTableHost: string;
  secondaryTableMicrosoftEndpoint: string;
  secondaryTableMicrosoftHost: string;
  secondaryWebEndpoint: string;
  secondaryWebHost: string;
  secondaryWebInternetEndpoint: string;
  secondaryWebInternetHost: string;
  secondaryWebMicrosoftEndpoint: string;
  secondaryWebMicrosoftHost: string;
  sftpEnabled: boolean;
  sharedAccessKeyEnabled: boolean;
  tableEncryptionKeyType: string;
  tags: Record<string, string>;
  azureFilesAuthentication: Account_AzureFilesAuthentication[];
  blobProperties: Account_BlobProperties[];
  customDomain: Account_CustomDomain[];
  customerManagedKey: Account_CustomerManagedKey[];
  identity: Account_Identity[];
  immutabilityPolicy: Account_ImmutabilityPolicy[];
  networkRules: Account_NetworkRules[];
  routing: Account_Routing[];
  sasPolicy: Account_SasPolicy[];
  shareProperties: Account_ShareProperties[];
  timeouts: Account_Timeouts;
}

export const Account: ResourceBinding<AccountConfig, AccountAttrs> = {
  wireType: "azurerm_storage_account",
  fields: {
    accessTier: "access_tier",
    accountKind: "account_kind",
    accountReplicationType: "account_replication_type",
    accountTier: "account_tier",
    allowNestedItemsToBePublic: "allow_nested_items_to_be_public",
    allowedCopyScope: "allowed_copy_scope",
    crossTenantReplicationEnabled: "cross_tenant_replication_enabled",
    defaultToOauthAuthentication: "default_to_oauth_authentication",
    dnsEndpointType: "dns_endpoint_type",
    edgeZone: "edge_zone",
    httpsTrafficOnlyEnabled: "https_traffic_only_enabled",
    id: "id",
    infrastructureEncryptionEnabled: "infrastructure_encryption_enabled",
    isHnsEnabled: "is_hns_enabled",
    largeFileShareEnabled: "large_file_share_enabled",
    localUserEnabled: "local_user_enabled",
    location: "location",
    minTlsVersion: "min_tls_version",
    name: "name",
    nfsv3Enabled: "nfsv3_enabled",
    provisionedBillingModelVersion: "provisioned_billing_model_version",
    publicNetworkAccessEnabled: "public_network_access_enabled",
    queueEncryptionKeyType: "queue_encryption_key_type",
    resourceGroupName: "resource_group_name",
    sftpEnabled: "sftp_enabled",
    sharedAccessKeyEnabled: "shared_access_key_enabled",
    tableEncryptionKeyType: "table_encryption_key_type",
    tags: "tags",
    azureFilesAuthentication: {
      wireName: "azure_files_authentication",
      kind: "list",
      fields: Account_AzureFilesAuthenticationFields,
    },
    blobProperties: {
      wireName: "blob_properties",
      kind: "list",
      fields: Account_BlobPropertiesFields,
    },
    customDomain: {
      wireName: "custom_domain",
      kind: "list",
      fields: Account_CustomDomainFields,
    },
    customerManagedKey: {
      wireName: "customer_managed_key",
      kind: "list",
      fields: Account_CustomerManagedKeyFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: Account_IdentityFields,
    },
    immutabilityPolicy: {
      wireName: "immutability_policy",
      kind: "list",
      fields: Account_ImmutabilityPolicyFields,
    },
    networkRules: {
      wireName: "network_rules",
      kind: "list",
      fields: Account_NetworkRulesFields,
    },
    routing: {
      wireName: "routing",
      kind: "list",
      fields: Account_RoutingFields,
    },
    sasPolicy: {
      wireName: "sas_policy",
      kind: "list",
      fields: Account_SasPolicyFields,
    },
    shareProperties: {
      wireName: "share_properties",
      kind: "list",
      fields: Account_SharePropertiesFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Account_TimeoutsFields,
    },
  },
};
