// Code generated by `ubx sdk gen` from azurerm_storage_mover_job_definition. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MoverJobDefinition_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const MoverJobDefinition_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface MoverJobDefinitionConfig {
  agentName?: string | Computed<string>;
  copyMode: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  sourceName: string | Computed<string>;
  sourceSubPath?: string | Computed<string>;
  storageMoverProjectId: string | Computed<string>;
  targetName: string | Computed<string>;
  targetSubPath?: string | Computed<string>;
  timeouts?: MoverJobDefinition_Timeouts | Computed<MoverJobDefinition_Timeouts>;
}

export interface MoverJobDefinitionAttrs {
  agentName: string;
  copyMode: string;
  description: string;
  id: string;
  name: string;
  sourceName: string;
  sourceSubPath: string;
  storageMoverProjectId: string;
  targetName: string;
  targetSubPath: string;
  timeouts: MoverJobDefinition_Timeouts;
}

export const MoverJobDefinition: ResourceBinding<MoverJobDefinitionConfig, MoverJobDefinitionAttrs> = {
  wireType: "azurerm_storage_mover_job_definition",
  fields: {
    agentName: "agent_name",
    copyMode: "copy_mode",
    description: "description",
    id: "id",
    name: "name",
    sourceName: "source_name",
    sourceSubPath: "source_sub_path",
    storageMoverProjectId: "storage_mover_project_id",
    targetName: "target_name",
    targetSubPath: "target_sub_path",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: MoverJobDefinition_TimeoutsFields,
    },
  },
};
