// Code generated by `ubx sdk gen` from azurerm_lighthouse_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Assignment_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const Assignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface AssignmentConfig {
  id?: string | Computed<string>;
  lighthouseDefinitionId: string | Computed<string>;
  name?: string | Computed<string>;
  scope: string | Computed<string>;
  timeouts?: Assignment_Timeouts | Computed<Assignment_Timeouts>;
}

export interface AssignmentAttrs {
  id: string;
  lighthouseDefinitionId: string;
  name: string;
  scope: string;
  timeouts: Assignment_Timeouts;
}

export const Assignment: ResourceBinding<AssignmentConfig, AssignmentAttrs> = {
  wireType: "azurerm_lighthouse_assignment",
  fields: {
    id: "id",
    lighthouseDefinitionId: "lighthouse_definition_id",
    name: "name",
    scope: "scope",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Assignment_TimeoutsFields,
    },
  },
};
