// Code generated by `ubx sdk gen` from azurerm_subnet_network_security_group_association. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface NetworkSecurityGroupAssociation_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const NetworkSecurityGroupAssociation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface NetworkSecurityGroupAssociationConfig {
  id?: string | Computed<string>;
  networkSecurityGroupId: string | Computed<string>;
  subnetId: string | Computed<string>;
  timeouts?: NetworkSecurityGroupAssociation_Timeouts | Computed<NetworkSecurityGroupAssociation_Timeouts>;
}

export interface NetworkSecurityGroupAssociationAttrs {
  id: string;
  networkSecurityGroupId: string;
  subnetId: string;
  timeouts: NetworkSecurityGroupAssociation_Timeouts;
}

export const NetworkSecurityGroupAssociation: ResourceBinding<NetworkSecurityGroupAssociationConfig, NetworkSecurityGroupAssociationAttrs> = {
  wireType: "azurerm_subnet_network_security_group_association",
  fields: {
    id: "id",
    networkSecurityGroupId: "network_security_group_id",
    subnetId: "subnet_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: NetworkSecurityGroupAssociation_TimeoutsFields,
    },
  },
};
