// Code generated by `ubx sdk gen` from azurerm_nat_gateway_public_ip_prefix_association. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface GatewayPublicIpPrefixAssociation_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const GatewayPublicIpPrefixAssociation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface GatewayPublicIpPrefixAssociationConfig {
  id?: string | Computed<string>;
  natGatewayId: string | Computed<string>;
  publicIpPrefixId: string | Computed<string>;
  timeouts?: GatewayPublicIpPrefixAssociation_Timeouts | Computed<GatewayPublicIpPrefixAssociation_Timeouts>;
}

export interface GatewayPublicIpPrefixAssociationAttrs {
  id: string;
  natGatewayId: string;
  publicIpPrefixId: string;
  timeouts: GatewayPublicIpPrefixAssociation_Timeouts;
}

export const GatewayPublicIpPrefixAssociation: ResourceBinding<GatewayPublicIpPrefixAssociationConfig, GatewayPublicIpPrefixAssociationAttrs> = {
  wireType: "azurerm_nat_gateway_public_ip_prefix_association",
  fields: {
    id: "id",
    natGatewayId: "nat_gateway_id",
    publicIpPrefixId: "public_ip_prefix_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: GatewayPublicIpPrefixAssociation_TimeoutsFields,
    },
  },
};
