// Code generated by `ubx sdk gen` from azurerm_app_service_source_control. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ServiceSourceControl_GithubActionConfiguration_CodeConfiguration {
  runtimeStack: string;
  runtimeVersion: string;
}

export interface ServiceSourceControl_GithubActionConfiguration_ContainerConfiguration {
  imageName: string;
  registryPassword: string;
  registryUrl: string;
  registryUsername: string;
}

export interface ServiceSourceControl_GithubActionConfiguration {
  generateWorkflowFile: boolean;
  linuxAction: boolean;
  codeConfiguration: ServiceSourceControl_GithubActionConfiguration_CodeConfiguration[];
  containerConfiguration: ServiceSourceControl_GithubActionConfiguration_ContainerConfiguration[];
}

export interface ServiceSourceControl_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const ServiceSourceControl_GithubActionConfiguration_CodeConfigurationFields: FieldMap = {
  runtimeStack: "runtime_stack",
  runtimeVersion: "runtime_version",
};

const ServiceSourceControl_GithubActionConfiguration_ContainerConfigurationFields: FieldMap = {
  imageName: "image_name",
  registryPassword: "registry_password",
  registryUrl: "registry_url",
  registryUsername: "registry_username",
};

const ServiceSourceControl_GithubActionConfigurationFields: FieldMap = {
  generateWorkflowFile: "generate_workflow_file",
  linuxAction: "linux_action",
  codeConfiguration: {
    wireName: "code_configuration",
    kind: "list",
    fields: ServiceSourceControl_GithubActionConfiguration_CodeConfigurationFields,
  },
  containerConfiguration: {
    wireName: "container_configuration",
    kind: "list",
    fields: ServiceSourceControl_GithubActionConfiguration_ContainerConfigurationFields,
  },
};

const ServiceSourceControl_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface ServiceSourceControlConfig {
  appId: string | Computed<string>;
  branch?: string | Computed<string>;
  id?: string | Computed<string>;
  repoUrl?: string | Computed<string>;
  rollbackEnabled?: boolean | Computed<boolean>;
  useLocalGit?: boolean | Computed<boolean>;
  useManualIntegration?: boolean | Computed<boolean>;
  useMercurial?: boolean | Computed<boolean>;
  githubActionConfiguration?: ServiceSourceControl_GithubActionConfiguration[] | Computed<ServiceSourceControl_GithubActionConfiguration[]>;
  timeouts?: ServiceSourceControl_Timeouts | Computed<ServiceSourceControl_Timeouts>;
}

export interface ServiceSourceControlAttrs {
  appId: string;
  branch: string;
  id: string;
  repoUrl: string;
  rollbackEnabled: boolean;
  scmType: string;
  useLocalGit: boolean;
  useManualIntegration: boolean;
  useMercurial: boolean;
  usesGithubAction: boolean;
  githubActionConfiguration: ServiceSourceControl_GithubActionConfiguration[];
  timeouts: ServiceSourceControl_Timeouts;
}

export const ServiceSourceControl: ResourceBinding<ServiceSourceControlConfig, ServiceSourceControlAttrs> = {
  wireType: "azurerm_app_service_source_control",
  fields: {
    appId: "app_id",
    branch: "branch",
    id: "id",
    repoUrl: "repo_url",
    rollbackEnabled: "rollback_enabled",
    useLocalGit: "use_local_git",
    useManualIntegration: "use_manual_integration",
    useMercurial: "use_mercurial",
    githubActionConfiguration: {
      wireName: "github_action_configuration",
      kind: "list",
      fields: ServiceSourceControl_GithubActionConfigurationFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ServiceSourceControl_TimeoutsFields,
    },
  },
};
