// Code generated by `ubx sdk gen` from azurerm_app_service_certificate_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ServiceCertificateBinding_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const ServiceCertificateBinding_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface ServiceCertificateBindingConfig {
  certificateId: string | Computed<string>;
  hostnameBindingId: string | Computed<string>;
  id?: string | Computed<string>;
  sslState: string | Computed<string>;
  timeouts?: ServiceCertificateBinding_Timeouts | Computed<ServiceCertificateBinding_Timeouts>;
}

export interface ServiceCertificateBindingAttrs {
  appServiceName: string;
  certificateId: string;
  hostname: string;
  hostnameBindingId: string;
  id: string;
  sslState: string;
  thumbprint: string;
  timeouts: ServiceCertificateBinding_Timeouts;
}

export const ServiceCertificateBinding: ResourceBinding<ServiceCertificateBindingConfig, ServiceCertificateBindingAttrs> = {
  wireType: "azurerm_app_service_certificate_binding",
  fields: {
    certificateId: "certificate_id",
    hostnameBindingId: "hostname_binding_id",
    id: "id",
    sslState: "ssl_state",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ServiceCertificateBinding_TimeoutsFields,
    },
  },
};
