// Code generated by `ubx sdk gen` from azurerm_extended_location_custom_location. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LocationCustomLocation_Authentication {
  type: string;
  value: string;
}

export interface LocationCustomLocation_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const LocationCustomLocation_AuthenticationFields: FieldMap = {
  type: "type",
  value: "value",
};

const LocationCustomLocation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface LocationCustomLocationConfig {
  clusterExtensionIds: string[] | Computed<string[]>;
  displayName?: string | Computed<string>;
  hostResourceId: string | Computed<string>;
  hostType?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  namespace: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  authentication?: LocationCustomLocation_Authentication[] | Computed<LocationCustomLocation_Authentication[]>;
  timeouts?: LocationCustomLocation_Timeouts | Computed<LocationCustomLocation_Timeouts>;
}

export interface LocationCustomLocationAttrs {
  clusterExtensionIds: string[];
  displayName: string;
  hostResourceId: string;
  hostType: string;
  id: string;
  location: string;
  name: string;
  namespace: string;
  resourceGroupName: string;
  authentication: LocationCustomLocation_Authentication[];
  timeouts: LocationCustomLocation_Timeouts;
}

export const LocationCustomLocation: ResourceBinding<LocationCustomLocationConfig, LocationCustomLocationAttrs> = {
  wireType: "azurerm_extended_location_custom_location",
  fields: {
    clusterExtensionIds: "cluster_extension_ids",
    displayName: "display_name",
    hostResourceId: "host_resource_id",
    hostType: "host_type",
    id: "id",
    location: "location",
    name: "name",
    namespace: "namespace",
    resourceGroupName: "resource_group_name",
    authentication: {
      wireName: "authentication",
      kind: "list",
      fields: LocationCustomLocation_AuthenticationFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: LocationCustomLocation_TimeoutsFields,
    },
  },
};
