// Code generated by `ubx sdk gen` from azurerm_machine_learning_datastore_fileshare. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LearningDatastoreFileshare_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const LearningDatastoreFileshare_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface LearningDatastoreFileshareConfig {
  accountKey?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  serviceDataIdentity?: string | Computed<string>;
  sharedAccessSignature?: string | Computed<string>;
  storageFileshareId: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  workspaceId: string | Computed<string>;
  timeouts?: LearningDatastoreFileshare_Timeouts | Computed<LearningDatastoreFileshare_Timeouts>;
}

export interface LearningDatastoreFileshareAttrs {
  accountKey: string;
  description: string;
  id: string;
  isDefault: boolean;
  name: string;
  serviceDataIdentity: string;
  sharedAccessSignature: string;
  storageFileshareId: string;
  tags: Record<string, string>;
  workspaceId: string;
  timeouts: LearningDatastoreFileshare_Timeouts;
}

export const LearningDatastoreFileshare: ResourceBinding<LearningDatastoreFileshareConfig, LearningDatastoreFileshareAttrs> = {
  wireType: "azurerm_machine_learning_datastore_fileshare",
  fields: {
    accountKey: "account_key",
    description: "description",
    id: "id",
    name: "name",
    serviceDataIdentity: "service_data_identity",
    sharedAccessSignature: "shared_access_signature",
    storageFileshareId: "storage_fileshare_id",
    tags: "tags",
    workspaceId: "workspace_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: LearningDatastoreFileshare_TimeoutsFields,
    },
  },
};
