// Code generated by `ubx sdk gen` from azurerm_machine_learning_compute_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LearningComputeCluster_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface LearningComputeCluster_ScaleSettings {
  maxNodeCount: number;
  minNodeCount: number;
  scaleDownNodesAfterIdleDuration: string;
}

export interface LearningComputeCluster_Ssh {
  adminPassword: string;
  adminUsername: string;
  keyValue: string;
}

export interface LearningComputeCluster_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const LearningComputeCluster_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const LearningComputeCluster_ScaleSettingsFields: FieldMap = {
  maxNodeCount: "max_node_count",
  minNodeCount: "min_node_count",
  scaleDownNodesAfterIdleDuration: "scale_down_nodes_after_idle_duration",
};

const LearningComputeCluster_SshFields: FieldMap = {
  adminPassword: "admin_password",
  adminUsername: "admin_username",
  keyValue: "key_value",
};

const LearningComputeCluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface LearningComputeClusterConfig {
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  localAuthEnabled?: boolean | Computed<boolean>;
  location: string | Computed<string>;
  machineLearningWorkspaceId: string | Computed<string>;
  name: string | Computed<string>;
  nodePublicIpEnabled?: boolean | Computed<boolean>;
  sshPublicAccessEnabled?: boolean | Computed<boolean>;
  subnetResourceId?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  vmPriority: string | Computed<string>;
  vmSize: string | Computed<string>;
  identity?: LearningComputeCluster_Identity[] | Computed<LearningComputeCluster_Identity[]>;
  scaleSettings?: LearningComputeCluster_ScaleSettings[] | Computed<LearningComputeCluster_ScaleSettings[]>;
  ssh?: LearningComputeCluster_Ssh[] | Computed<LearningComputeCluster_Ssh[]>;
  timeouts?: LearningComputeCluster_Timeouts | Computed<LearningComputeCluster_Timeouts>;
}

export interface LearningComputeClusterAttrs {
  description: string;
  id: string;
  localAuthEnabled: boolean;
  location: string;
  machineLearningWorkspaceId: string;
  name: string;
  nodePublicIpEnabled: boolean;
  sshPublicAccessEnabled: boolean;
  subnetResourceId: string;
  tags: Record<string, string>;
  vmPriority: string;
  vmSize: string;
  identity: LearningComputeCluster_Identity[];
  scaleSettings: LearningComputeCluster_ScaleSettings[];
  ssh: LearningComputeCluster_Ssh[];
  timeouts: LearningComputeCluster_Timeouts;
}

export const LearningComputeCluster: ResourceBinding<LearningComputeClusterConfig, LearningComputeClusterAttrs> = {
  wireType: "azurerm_machine_learning_compute_cluster",
  fields: {
    description: "description",
    id: "id",
    localAuthEnabled: "local_auth_enabled",
    location: "location",
    machineLearningWorkspaceId: "machine_learning_workspace_id",
    name: "name",
    nodePublicIpEnabled: "node_public_ip_enabled",
    sshPublicAccessEnabled: "ssh_public_access_enabled",
    subnetResourceId: "subnet_resource_id",
    tags: "tags",
    vmPriority: "vm_priority",
    vmSize: "vm_size",
    identity: {
      wireName: "identity",
      kind: "list",
      fields: LearningComputeCluster_IdentityFields,
    },
    scaleSettings: {
      wireName: "scale_settings",
      kind: "list",
      fields: LearningComputeCluster_ScaleSettingsFields,
    },
    ssh: {
      wireName: "ssh",
      kind: "list",
      fields: LearningComputeCluster_SshFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: LearningComputeCluster_TimeoutsFields,
    },
  },
};
