// Code generated by `ubx sdk gen` from azurerm_system_center_virtual_machine_manager_virtual_machine_instance. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CenterVirtualMachineManagerVirtualMachineInstance_Hardware {
  cpuCount: number;
  dynamicMemoryMaxInMb: number;
  dynamicMemoryMinInMb: number;
  limitCpuForMigrationEnabled: boolean;
  memoryInMb: number;
}

export interface CenterVirtualMachineManagerVirtualMachineInstance_Infrastructure {
  checkpointType: string;
  systemCenterVirtualMachineManagerCloudId: string;
  systemCenterVirtualMachineManagerInventoryItemId: string;
  systemCenterVirtualMachineManagerTemplateId: string;
  systemCenterVirtualMachineManagerVirtualMachineServerId: string;
}

export interface CenterVirtualMachineManagerVirtualMachineInstance_NetworkInterface {
  ipv4AddressType: string;
  ipv6AddressType: string;
  macAddressType: string;
  name: string;
  virtualNetworkId: string;
}

export interface CenterVirtualMachineManagerVirtualMachineInstance_OperatingSystem {
  adminPassword: string;
  computerName: string;
}

export interface CenterVirtualMachineManagerVirtualMachineInstance_StorageDisk {
  bus: number;
  busType: string;
  diskSizeGb: number;
  lun: number;
  name: string;
  storageQosPolicyName: string;
  templateDiskId: string;
  vhdType: string;
}

export interface CenterVirtualMachineManagerVirtualMachineInstance_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const CenterVirtualMachineManagerVirtualMachineInstance_HardwareFields: FieldMap = {
  cpuCount: "cpu_count",
  dynamicMemoryMaxInMb: "dynamic_memory_max_in_mb",
  dynamicMemoryMinInMb: "dynamic_memory_min_in_mb",
  limitCpuForMigrationEnabled: "limit_cpu_for_migration_enabled",
  memoryInMb: "memory_in_mb",
};

const CenterVirtualMachineManagerVirtualMachineInstance_InfrastructureFields: FieldMap = {
  checkpointType: "checkpoint_type",
  systemCenterVirtualMachineManagerCloudId: "system_center_virtual_machine_manager_cloud_id",
  systemCenterVirtualMachineManagerInventoryItemId: "system_center_virtual_machine_manager_inventory_item_id",
  systemCenterVirtualMachineManagerTemplateId: "system_center_virtual_machine_manager_template_id",
  systemCenterVirtualMachineManagerVirtualMachineServerId: "system_center_virtual_machine_manager_virtual_machine_server_id",
};

const CenterVirtualMachineManagerVirtualMachineInstance_NetworkInterfaceFields: FieldMap = {
  ipv4AddressType: "ipv4_address_type",
  ipv6AddressType: "ipv6_address_type",
  macAddressType: "mac_address_type",
  name: "name",
  virtualNetworkId: "virtual_network_id",
};

const CenterVirtualMachineManagerVirtualMachineInstance_OperatingSystemFields: FieldMap = {
  adminPassword: "admin_password",
  computerName: "computer_name",
};

const CenterVirtualMachineManagerVirtualMachineInstance_StorageDiskFields: FieldMap = {
  bus: "bus",
  busType: "bus_type",
  diskSizeGb: "disk_size_gb",
  lun: "lun",
  name: "name",
  storageQosPolicyName: "storage_qos_policy_name",
  templateDiskId: "template_disk_id",
  vhdType: "vhd_type",
};

const CenterVirtualMachineManagerVirtualMachineInstance_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface CenterVirtualMachineManagerVirtualMachineInstanceConfig {
  customLocationId: string | Computed<string>;
  id?: string | Computed<string>;
  scopedResourceId: string | Computed<string>;
  systemCenterVirtualMachineManagerAvailabilitySetIds?: string[] | Computed<string[]>;
  hardware?: CenterVirtualMachineManagerVirtualMachineInstance_Hardware[] | Computed<CenterVirtualMachineManagerVirtualMachineInstance_Hardware[]>;
  infrastructure?: CenterVirtualMachineManagerVirtualMachineInstance_Infrastructure[] | Computed<CenterVirtualMachineManagerVirtualMachineInstance_Infrastructure[]>;
  networkInterface?: CenterVirtualMachineManagerVirtualMachineInstance_NetworkInterface[] | Computed<CenterVirtualMachineManagerVirtualMachineInstance_NetworkInterface[]>;
  operatingSystem?: CenterVirtualMachineManagerVirtualMachineInstance_OperatingSystem[] | Computed<CenterVirtualMachineManagerVirtualMachineInstance_OperatingSystem[]>;
  storageDisk?: CenterVirtualMachineManagerVirtualMachineInstance_StorageDisk[] | Computed<CenterVirtualMachineManagerVirtualMachineInstance_StorageDisk[]>;
  timeouts?: CenterVirtualMachineManagerVirtualMachineInstance_Timeouts | Computed<CenterVirtualMachineManagerVirtualMachineInstance_Timeouts>;
}

export interface CenterVirtualMachineManagerVirtualMachineInstanceAttrs {
  customLocationId: string;
  id: string;
  scopedResourceId: string;
  systemCenterVirtualMachineManagerAvailabilitySetIds: string[];
  hardware: CenterVirtualMachineManagerVirtualMachineInstance_Hardware[];
  infrastructure: CenterVirtualMachineManagerVirtualMachineInstance_Infrastructure[];
  networkInterface: CenterVirtualMachineManagerVirtualMachineInstance_NetworkInterface[];
  operatingSystem: CenterVirtualMachineManagerVirtualMachineInstance_OperatingSystem[];
  storageDisk: CenterVirtualMachineManagerVirtualMachineInstance_StorageDisk[];
  timeouts: CenterVirtualMachineManagerVirtualMachineInstance_Timeouts;
}

export const CenterVirtualMachineManagerVirtualMachineInstance: ResourceBinding<CenterVirtualMachineManagerVirtualMachineInstanceConfig, CenterVirtualMachineManagerVirtualMachineInstanceAttrs> = {
  wireType: "azurerm_system_center_virtual_machine_manager_virtual_machine_instance",
  fields: {
    customLocationId: "custom_location_id",
    id: "id",
    scopedResourceId: "scoped_resource_id",
    systemCenterVirtualMachineManagerAvailabilitySetIds: "system_center_virtual_machine_manager_availability_set_ids",
    hardware: {
      wireName: "hardware",
      kind: "list",
      fields: CenterVirtualMachineManagerVirtualMachineInstance_HardwareFields,
    },
    infrastructure: {
      wireName: "infrastructure",
      kind: "list",
      fields: CenterVirtualMachineManagerVirtualMachineInstance_InfrastructureFields,
    },
    networkInterface: {
      wireName: "network_interface",
      kind: "list",
      fields: CenterVirtualMachineManagerVirtualMachineInstance_NetworkInterfaceFields,
    },
    operatingSystem: {
      wireName: "operating_system",
      kind: "list",
      fields: CenterVirtualMachineManagerVirtualMachineInstance_OperatingSystemFields,
    },
    storageDisk: {
      wireName: "storage_disk",
      kind: "list",
      fields: CenterVirtualMachineManagerVirtualMachineInstance_StorageDiskFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CenterVirtualMachineManagerVirtualMachineInstance_TimeoutsFields,
    },
  },
};
