// Code generated by `ubx sdk gen` from azurerm_lb_rule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Rule_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Rule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface RuleConfig {
  backendAddressPoolIds?: string[] | Computed<string[]>;
  backendPort: number | Computed<number>;
  disableOutboundSnat?: boolean | Computed<boolean>;
  floatingIpEnabled?: boolean | Computed<boolean>;
  frontendIpConfigurationName: string | Computed<string>;
  frontendPort: number | Computed<number>;
  id?: string | Computed<string>;
  idleTimeoutInMinutes?: number | Computed<number>;
  loadDistribution?: string | Computed<string>;
  loadbalancerId: string | Computed<string>;
  name: string | Computed<string>;
  probeId?: string | Computed<string>;
  protocol: string | Computed<string>;
  tcpResetEnabled?: boolean | Computed<boolean>;
  timeouts?: Rule_Timeouts | Computed<Rule_Timeouts>;
}

export interface RuleAttrs {
  backendAddressPoolIds: string[];
  backendPort: number;
  disableOutboundSnat: boolean;
  floatingIpEnabled: boolean;
  frontendIpConfigurationId: string;
  frontendIpConfigurationName: string;
  frontendPort: number;
  id: string;
  idleTimeoutInMinutes: number;
  loadDistribution: string;
  loadbalancerId: string;
  name: string;
  probeId: string;
  protocol: string;
  tcpResetEnabled: boolean;
  timeouts: Rule_Timeouts;
}

export const Rule: ResourceBinding<RuleConfig, RuleAttrs> = {
  wireType: "azurerm_lb_rule",
  fields: {
    backendAddressPoolIds: "backend_address_pool_ids",
    backendPort: "backend_port",
    disableOutboundSnat: "disable_outbound_snat",
    floatingIpEnabled: "floating_ip_enabled",
    frontendIpConfigurationName: "frontend_ip_configuration_name",
    frontendPort: "frontend_port",
    id: "id",
    idleTimeoutInMinutes: "idle_timeout_in_minutes",
    loadDistribution: "load_distribution",
    loadbalancerId: "loadbalancer_id",
    name: "name",
    probeId: "probe_id",
    protocol: "protocol",
    tcpResetEnabled: "tcp_reset_enabled",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Rule_TimeoutsFields,
    },
  },
};
