// Code generated by `ubx sdk gen` from azurerm_eventgrid_event_subscription. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EventSubscription_AdvancedFilter_BoolEquals {
  key: string;
  value: boolean;
}

export interface EventSubscription_AdvancedFilter_IsNotNull {
  key: string;
}

export interface EventSubscription_AdvancedFilter_NumberGreaterThan {
  key: string;
  value: number;
}

export interface EventSubscription_AdvancedFilter_NumberIn {
  key: string;
  values: number[];
}

export interface EventSubscription_AdvancedFilter_NumberInRange {
  key: string;
  values: number[][];
}

export interface EventSubscription_AdvancedFilter_StringBeginsWith {
  key: string;
  values: string[];
}

export interface EventSubscription_AdvancedFilter {
  boolEquals: EventSubscription_AdvancedFilter_BoolEquals[];
  isNotNull: EventSubscription_AdvancedFilter_IsNotNull[];
  isNullOrUndefined: EventSubscription_AdvancedFilter_IsNotNull[];
  numberGreaterThan: EventSubscription_AdvancedFilter_NumberGreaterThan[];
  numberGreaterThanOrEquals: EventSubscription_AdvancedFilter_NumberGreaterThan[];
  numberIn: EventSubscription_AdvancedFilter_NumberIn[];
  numberInRange: EventSubscription_AdvancedFilter_NumberInRange[];
  numberLessThan: EventSubscription_AdvancedFilter_NumberGreaterThan[];
  numberLessThanOrEquals: EventSubscription_AdvancedFilter_NumberGreaterThan[];
  numberNotIn: EventSubscription_AdvancedFilter_NumberIn[];
  numberNotInRange: EventSubscription_AdvancedFilter_NumberInRange[];
  stringBeginsWith: EventSubscription_AdvancedFilter_StringBeginsWith[];
  stringContains: EventSubscription_AdvancedFilter_StringBeginsWith[];
  stringEndsWith: EventSubscription_AdvancedFilter_StringBeginsWith[];
  stringIn: EventSubscription_AdvancedFilter_StringBeginsWith[];
  stringNotBeginsWith: EventSubscription_AdvancedFilter_StringBeginsWith[];
  stringNotContains: EventSubscription_AdvancedFilter_StringBeginsWith[];
  stringNotEndsWith: EventSubscription_AdvancedFilter_StringBeginsWith[];
  stringNotIn: EventSubscription_AdvancedFilter_StringBeginsWith[];
}

export interface EventSubscription_AzureFunctionEndpoint {
  functionId: string;
  maxEventsPerBatch: number;
  preferredBatchSizeInKilobytes: number;
}

export interface EventSubscription_DeadLetterIdentity {
  type: string;
  userAssignedIdentity: string;
}

export interface EventSubscription_DeliveryProperty {
  headerName: string;
  secret: boolean;
  sourceField: string;
  type: string;
  value: string;
}

export interface EventSubscription_RetryPolicy {
  eventTimeToLive: number;
  maxDeliveryAttempts: number;
}

export interface EventSubscription_StorageBlobDeadLetterDestination {
  storageAccountId: string;
  storageBlobContainerName: string;
}

export interface EventSubscription_StorageQueueEndpoint {
  queueMessageTimeToLiveInSeconds: number;
  queueName: string;
  storageAccountId: string;
}

export interface EventSubscription_SubjectFilter {
  caseSensitive: boolean;
  subjectBeginsWith: string;
  subjectEndsWith: string;
}

export interface EventSubscription_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

export interface EventSubscription_WebhookEndpoint {
  activeDirectoryAppIdOrUri: string;
  activeDirectoryTenantId: string;
  baseUrl: string;
  maxEventsPerBatch: number;
  preferredBatchSizeInKilobytes: number;
  url: string;
}

const EventSubscription_AdvancedFilter_BoolEqualsFields: FieldMap = {
  key: "key",
  value: "value",
};

const EventSubscription_AdvancedFilter_IsNotNullFields: FieldMap = {
  key: "key",
};

const EventSubscription_AdvancedFilter_NumberGreaterThanFields: FieldMap = {
  key: "key",
  value: "value",
};

const EventSubscription_AdvancedFilter_NumberInFields: FieldMap = {
  key: "key",
  values: "values",
};

const EventSubscription_AdvancedFilter_NumberInRangeFields: FieldMap = {
  key: "key",
  values: "values",
};

const EventSubscription_AdvancedFilter_StringBeginsWithFields: FieldMap = {
  key: "key",
  values: "values",
};

const EventSubscription_AdvancedFilterFields: FieldMap = {
  boolEquals: {
    wireName: "bool_equals",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_BoolEqualsFields,
  },
  isNotNull: {
    wireName: "is_not_null",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_IsNotNullFields,
  },
  isNullOrUndefined: {
    wireName: "is_null_or_undefined",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_IsNotNullFields,
  },
  numberGreaterThan: {
    wireName: "number_greater_than",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_NumberGreaterThanFields,
  },
  numberGreaterThanOrEquals: {
    wireName: "number_greater_than_or_equals",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_NumberGreaterThanFields,
  },
  numberIn: {
    wireName: "number_in",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_NumberInFields,
  },
  numberInRange: {
    wireName: "number_in_range",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_NumberInRangeFields,
  },
  numberLessThan: {
    wireName: "number_less_than",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_NumberGreaterThanFields,
  },
  numberLessThanOrEquals: {
    wireName: "number_less_than_or_equals",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_NumberGreaterThanFields,
  },
  numberNotIn: {
    wireName: "number_not_in",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_NumberInFields,
  },
  numberNotInRange: {
    wireName: "number_not_in_range",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_NumberInRangeFields,
  },
  stringBeginsWith: {
    wireName: "string_begins_with",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_StringBeginsWithFields,
  },
  stringContains: {
    wireName: "string_contains",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_StringBeginsWithFields,
  },
  stringEndsWith: {
    wireName: "string_ends_with",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_StringBeginsWithFields,
  },
  stringIn: {
    wireName: "string_in",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_StringBeginsWithFields,
  },
  stringNotBeginsWith: {
    wireName: "string_not_begins_with",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_StringBeginsWithFields,
  },
  stringNotContains: {
    wireName: "string_not_contains",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_StringBeginsWithFields,
  },
  stringNotEndsWith: {
    wireName: "string_not_ends_with",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_StringBeginsWithFields,
  },
  stringNotIn: {
    wireName: "string_not_in",
    kind: "list",
    fields: EventSubscription_AdvancedFilter_StringBeginsWithFields,
  },
};

const EventSubscription_AzureFunctionEndpointFields: FieldMap = {
  functionId: "function_id",
  maxEventsPerBatch: "max_events_per_batch",
  preferredBatchSizeInKilobytes: "preferred_batch_size_in_kilobytes",
};

const EventSubscription_DeadLetterIdentityFields: FieldMap = {
  type: "type",
  userAssignedIdentity: "user_assigned_identity",
};

const EventSubscription_DeliveryPropertyFields: FieldMap = {
  headerName: "header_name",
  secret: "secret",
  sourceField: "source_field",
  type: "type",
  value: "value",
};

const EventSubscription_RetryPolicyFields: FieldMap = {
  eventTimeToLive: "event_time_to_live",
  maxDeliveryAttempts: "max_delivery_attempts",
};

const EventSubscription_StorageBlobDeadLetterDestinationFields: FieldMap = {
  storageAccountId: "storage_account_id",
  storageBlobContainerName: "storage_blob_container_name",
};

const EventSubscription_StorageQueueEndpointFields: FieldMap = {
  queueMessageTimeToLiveInSeconds: "queue_message_time_to_live_in_seconds",
  queueName: "queue_name",
  storageAccountId: "storage_account_id",
};

const EventSubscription_SubjectFilterFields: FieldMap = {
  caseSensitive: "case_sensitive",
  subjectBeginsWith: "subject_begins_with",
  subjectEndsWith: "subject_ends_with",
};

const EventSubscription_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

const EventSubscription_WebhookEndpointFields: FieldMap = {
  activeDirectoryAppIdOrUri: "active_directory_app_id_or_uri",
  activeDirectoryTenantId: "active_directory_tenant_id",
  baseUrl: "base_url",
  maxEventsPerBatch: "max_events_per_batch",
  preferredBatchSizeInKilobytes: "preferred_batch_size_in_kilobytes",
  url: "url",
};

export interface EventSubscriptionConfig {
  advancedFilteringOnArraysEnabled?: boolean | Computed<boolean>;
  eventDeliverySchema?: string | Computed<string>;
  eventhubId?: string | Computed<string>;
  expirationTimeUtc?: string | Computed<string>;
  hybridConnectionId?: string | Computed<string>;
  id?: string | Computed<string>;
  includedEventTypes?: string[] | Computed<string[]>;
  labels?: string[] | Computed<string[]>;
  name: string | Computed<string>;
  scope: string | Computed<string>;
  serviceBusQueueId?: string | Computed<string>;
  serviceBusTopicId?: string | Computed<string>;
  advancedFilter?: EventSubscription_AdvancedFilter[] | Computed<EventSubscription_AdvancedFilter[]>;
  azureFunctionEndpoint?: EventSubscription_AzureFunctionEndpoint[] | Computed<EventSubscription_AzureFunctionEndpoint[]>;
  deadLetterIdentity?: EventSubscription_DeadLetterIdentity[] | Computed<EventSubscription_DeadLetterIdentity[]>;
  deliveryIdentity?: EventSubscription_DeadLetterIdentity[] | Computed<EventSubscription_DeadLetterIdentity[]>;
  deliveryProperty?: EventSubscription_DeliveryProperty[] | Computed<EventSubscription_DeliveryProperty[]>;
  retryPolicy?: EventSubscription_RetryPolicy[] | Computed<EventSubscription_RetryPolicy[]>;
  storageBlobDeadLetterDestination?: EventSubscription_StorageBlobDeadLetterDestination[] | Computed<EventSubscription_StorageBlobDeadLetterDestination[]>;
  storageQueueEndpoint?: EventSubscription_StorageQueueEndpoint[] | Computed<EventSubscription_StorageQueueEndpoint[]>;
  subjectFilter?: EventSubscription_SubjectFilter[] | Computed<EventSubscription_SubjectFilter[]>;
  timeouts?: EventSubscription_Timeouts | Computed<EventSubscription_Timeouts>;
  webhookEndpoint?: EventSubscription_WebhookEndpoint[] | Computed<EventSubscription_WebhookEndpoint[]>;
}

export interface EventSubscriptionAttrs {
  advancedFilteringOnArraysEnabled: boolean;
  eventDeliverySchema: string;
  eventhubId: string;
  expirationTimeUtc: string;
  hybridConnectionId: string;
  id: string;
  includedEventTypes: string[];
  labels: string[];
  name: string;
  scope: string;
  serviceBusQueueId: string;
  serviceBusTopicId: string;
  advancedFilter: EventSubscription_AdvancedFilter[];
  azureFunctionEndpoint: EventSubscription_AzureFunctionEndpoint[];
  deadLetterIdentity: EventSubscription_DeadLetterIdentity[];
  deliveryIdentity: EventSubscription_DeadLetterIdentity[];
  deliveryProperty: EventSubscription_DeliveryProperty[];
  retryPolicy: EventSubscription_RetryPolicy[];
  storageBlobDeadLetterDestination: EventSubscription_StorageBlobDeadLetterDestination[];
  storageQueueEndpoint: EventSubscription_StorageQueueEndpoint[];
  subjectFilter: EventSubscription_SubjectFilter[];
  timeouts: EventSubscription_Timeouts;
  webhookEndpoint: EventSubscription_WebhookEndpoint[];
}

export const EventSubscription: ResourceBinding<EventSubscriptionConfig, EventSubscriptionAttrs> = {
  wireType: "azurerm_eventgrid_event_subscription",
  fields: {
    advancedFilteringOnArraysEnabled: "advanced_filtering_on_arrays_enabled",
    eventDeliverySchema: "event_delivery_schema",
    eventhubId: "eventhub_id",
    expirationTimeUtc: "expiration_time_utc",
    hybridConnectionId: "hybrid_connection_id",
    id: "id",
    includedEventTypes: "included_event_types",
    labels: "labels",
    name: "name",
    scope: "scope",
    serviceBusQueueId: "service_bus_queue_id",
    serviceBusTopicId: "service_bus_topic_id",
    advancedFilter: {
      wireName: "advanced_filter",
      kind: "list",
      fields: EventSubscription_AdvancedFilterFields,
    },
    azureFunctionEndpoint: {
      wireName: "azure_function_endpoint",
      kind: "list",
      fields: EventSubscription_AzureFunctionEndpointFields,
    },
    deadLetterIdentity: {
      wireName: "dead_letter_identity",
      kind: "list",
      fields: EventSubscription_DeadLetterIdentityFields,
    },
    deliveryIdentity: {
      wireName: "delivery_identity",
      kind: "list",
      fields: EventSubscription_DeadLetterIdentityFields,
    },
    deliveryProperty: {
      wireName: "delivery_property",
      kind: "list",
      fields: EventSubscription_DeliveryPropertyFields,
    },
    retryPolicy: {
      wireName: "retry_policy",
      kind: "list",
      fields: EventSubscription_RetryPolicyFields,
    },
    storageBlobDeadLetterDestination: {
      wireName: "storage_blob_dead_letter_destination",
      kind: "list",
      fields: EventSubscription_StorageBlobDeadLetterDestinationFields,
    },
    storageQueueEndpoint: {
      wireName: "storage_queue_endpoint",
      kind: "list",
      fields: EventSubscription_StorageQueueEndpointFields,
    },
    subjectFilter: {
      wireName: "subject_filter",
      kind: "list",
      fields: EventSubscription_SubjectFilterFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: EventSubscription_TimeoutsFields,
    },
    webhookEndpoint: {
      wireName: "webhook_endpoint",
      kind: "list",
      fields: EventSubscription_WebhookEndpointFields,
    },
  },
};
