// Code generated by `ubx sdk gen` from azurerm_firewall_network_rule_collection. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface NetworkRuleCollection_Rule {
  description: string;
  destinationAddresses: string[];
  destinationFqdns: string[];
  destinationIpGroups: string[];
  destinationPorts: string[];
  name: string;
  protocols: string[];
  sourceAddresses: string[];
  sourceIpGroups: string[];
}

export interface NetworkRuleCollection_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const NetworkRuleCollection_RuleFields: FieldMap = {
  description: "description",
  destinationAddresses: "destination_addresses",
  destinationFqdns: "destination_fqdns",
  destinationIpGroups: "destination_ip_groups",
  destinationPorts: "destination_ports",
  name: "name",
  protocols: "protocols",
  sourceAddresses: "source_addresses",
  sourceIpGroups: "source_ip_groups",
};

const NetworkRuleCollection_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface NetworkRuleCollectionConfig {
  action: string | Computed<string>;
  azureFirewallName: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  priority: number | Computed<number>;
  resourceGroupName: string | Computed<string>;
  rule?: NetworkRuleCollection_Rule[] | Computed<NetworkRuleCollection_Rule[]>;
  timeouts?: NetworkRuleCollection_Timeouts | Computed<NetworkRuleCollection_Timeouts>;
}

export interface NetworkRuleCollectionAttrs {
  action: string;
  azureFirewallName: string;
  id: string;
  name: string;
  priority: number;
  resourceGroupName: string;
  rule: NetworkRuleCollection_Rule[];
  timeouts: NetworkRuleCollection_Timeouts;
}

export const NetworkRuleCollection: ResourceBinding<NetworkRuleCollectionConfig, NetworkRuleCollectionAttrs> = {
  wireType: "azurerm_firewall_network_rule_collection",
  fields: {
    action: "action",
    azureFirewallName: "azure_firewall_name",
    id: "id",
    name: "name",
    priority: "priority",
    resourceGroupName: "resource_group_name",
    rule: {
      wireName: "rule",
      kind: "list",
      fields: NetworkRuleCollection_RuleFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: NetworkRuleCollection_TimeoutsFields,
    },
  },
};
