// Code generated by `ubx sdk gen` from azurerm_route_map. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Map_Rule_Action_Parameter {
  asPath: string[];
  community: string[];
  routePrefix: string[];
}

export interface Map_Rule_Action {
  type: string;
  parameter: Map_Rule_Action_Parameter[];
}

export interface Map_Rule_MatchCriterion {
  asPath: string[];
  community: string[];
  matchCondition: string;
  routePrefix: string[];
}

export interface Map_Rule {
  name: string;
  nextStepIfMatched: string;
  action: Map_Rule_Action[];
  matchCriterion: Map_Rule_MatchCriterion[];
}

export interface Map_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Map_Rule_Action_ParameterFields: FieldMap = {
  asPath: "as_path",
  community: "community",
  routePrefix: "route_prefix",
};

const Map_Rule_ActionFields: FieldMap = {
  type: "type",
  parameter: {
    wireName: "parameter",
    kind: "list",
    fields: Map_Rule_Action_ParameterFields,
  },
};

const Map_Rule_MatchCriterionFields: FieldMap = {
  asPath: "as_path",
  community: "community",
  matchCondition: "match_condition",
  routePrefix: "route_prefix",
};

const Map_RuleFields: FieldMap = {
  name: "name",
  nextStepIfMatched: "next_step_if_matched",
  action: {
    wireName: "action",
    kind: "list",
    fields: Map_Rule_ActionFields,
  },
  matchCriterion: {
    wireName: "match_criterion",
    kind: "list",
    fields: Map_Rule_MatchCriterionFields,
  },
};

const Map_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface MapConfig {
  id?: string | Computed<string>;
  name: string | Computed<string>;
  virtualHubId: string | Computed<string>;
  rule?: Map_Rule[] | Computed<Map_Rule[]>;
  timeouts?: Map_Timeouts | Computed<Map_Timeouts>;
}

export interface MapAttrs {
  id: string;
  name: string;
  virtualHubId: string;
  rule: Map_Rule[];
  timeouts: Map_Timeouts;
}

export const Map: ResourceBinding<MapConfig, MapAttrs> = {
  wireType: "azurerm_route_map",
  fields: {
    id: "id",
    name: "name",
    virtualHubId: "virtual_hub_id",
    rule: {
      wireName: "rule",
      kind: "list",
      fields: Map_RuleFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Map_TimeoutsFields,
    },
  },
};
