// Code generated by `ubx sdk gen` from azurerm_data_factory_linked_service_key_vault. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FactoryLinkedServiceKeyVault_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FactoryLinkedServiceKeyVault_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FactoryLinkedServiceKeyVaultConfig {
  additionalProperties?: Record<string, string> | Computed<Record<string, string>>;
  annotations?: string[] | Computed<string[]>;
  dataFactoryId: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  integrationRuntimeName?: string | Computed<string>;
  keyVaultId: string | Computed<string>;
  name: string | Computed<string>;
  parameters?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: FactoryLinkedServiceKeyVault_Timeouts | Computed<FactoryLinkedServiceKeyVault_Timeouts>;
}

export interface FactoryLinkedServiceKeyVaultAttrs {
  additionalProperties: Record<string, string>;
  annotations: string[];
  dataFactoryId: string;
  description: string;
  id: string;
  integrationRuntimeName: string;
  keyVaultId: string;
  name: string;
  parameters: Record<string, string>;
  timeouts: FactoryLinkedServiceKeyVault_Timeouts;
}

export const FactoryLinkedServiceKeyVault: ResourceBinding<FactoryLinkedServiceKeyVaultConfig, FactoryLinkedServiceKeyVaultAttrs> = {
  wireType: "azurerm_data_factory_linked_service_key_vault",
  fields: {
    additionalProperties: "additional_properties",
    annotations: "annotations",
    dataFactoryId: "data_factory_id",
    description: "description",
    id: "id",
    integrationRuntimeName: "integration_runtime_name",
    keyVaultId: "key_vault_id",
    name: "name",
    parameters: "parameters",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FactoryLinkedServiceKeyVault_TimeoutsFields,
    },
  },
};
