// Code generated by `ubx sdk gen` from azurerm_data_factory_trigger_custom_event. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FactoryTriggerCustomEvent_Pipeline {
  name: string;
  parameters: Record<string, string>;
}

export interface FactoryTriggerCustomEvent_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FactoryTriggerCustomEvent_PipelineFields: FieldMap = {
  name: "name",
  parameters: "parameters",
};

const FactoryTriggerCustomEvent_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FactoryTriggerCustomEventConfig {
  activated?: boolean | Computed<boolean>;
  additionalProperties?: Record<string, string> | Computed<Record<string, string>>;
  annotations?: string[] | Computed<string[]>;
  dataFactoryId: string | Computed<string>;
  description?: string | Computed<string>;
  eventgridTopicId: string | Computed<string>;
  events: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  subjectBeginsWith?: string | Computed<string>;
  subjectEndsWith?: string | Computed<string>;
  pipeline?: FactoryTriggerCustomEvent_Pipeline[] | Computed<FactoryTriggerCustomEvent_Pipeline[]>;
  timeouts?: FactoryTriggerCustomEvent_Timeouts | Computed<FactoryTriggerCustomEvent_Timeouts>;
}

export interface FactoryTriggerCustomEventAttrs {
  activated: boolean;
  additionalProperties: Record<string, string>;
  annotations: string[];
  dataFactoryId: string;
  description: string;
  eventgridTopicId: string;
  events: string[];
  id: string;
  name: string;
  subjectBeginsWith: string;
  subjectEndsWith: string;
  pipeline: FactoryTriggerCustomEvent_Pipeline[];
  timeouts: FactoryTriggerCustomEvent_Timeouts;
}

export const FactoryTriggerCustomEvent: ResourceBinding<FactoryTriggerCustomEventConfig, FactoryTriggerCustomEventAttrs> = {
  wireType: "azurerm_data_factory_trigger_custom_event",
  fields: {
    activated: "activated",
    additionalProperties: "additional_properties",
    annotations: "annotations",
    dataFactoryId: "data_factory_id",
    description: "description",
    eventgridTopicId: "eventgrid_topic_id",
    events: "events",
    id: "id",
    name: "name",
    subjectBeginsWith: "subject_begins_with",
    subjectEndsWith: "subject_ends_with",
    pipeline: {
      wireName: "pipeline",
      kind: "set",
      fields: FactoryTriggerCustomEvent_PipelineFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FactoryTriggerCustomEvent_TimeoutsFields,
    },
  },
};
