// Code generated by `ubx sdk gen` from azurerm_data_factory_trigger_blob_event. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FactoryTriggerBlobEvent_Pipeline {
  name: string;
  parameters: Record<string, string>;
}

export interface FactoryTriggerBlobEvent_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FactoryTriggerBlobEvent_PipelineFields: FieldMap = {
  name: "name",
  parameters: "parameters",
};

const FactoryTriggerBlobEvent_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FactoryTriggerBlobEventConfig {
  activated?: boolean | Computed<boolean>;
  additionalProperties?: Record<string, string> | Computed<Record<string, string>>;
  annotations?: string[] | Computed<string[]>;
  blobPathBeginsWith?: string | Computed<string>;
  blobPathEndsWith?: string | Computed<string>;
  dataFactoryId: string | Computed<string>;
  description?: string | Computed<string>;
  events: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  ignoreEmptyBlobs?: boolean | Computed<boolean>;
  name: string | Computed<string>;
  storageAccountId: string | Computed<string>;
  pipeline?: FactoryTriggerBlobEvent_Pipeline[] | Computed<FactoryTriggerBlobEvent_Pipeline[]>;
  timeouts?: FactoryTriggerBlobEvent_Timeouts | Computed<FactoryTriggerBlobEvent_Timeouts>;
}

export interface FactoryTriggerBlobEventAttrs {
  activated: boolean;
  additionalProperties: Record<string, string>;
  annotations: string[];
  blobPathBeginsWith: string;
  blobPathEndsWith: string;
  dataFactoryId: string;
  description: string;
  events: string[];
  id: string;
  ignoreEmptyBlobs: boolean;
  name: string;
  storageAccountId: string;
  pipeline: FactoryTriggerBlobEvent_Pipeline[];
  timeouts: FactoryTriggerBlobEvent_Timeouts;
}

export const FactoryTriggerBlobEvent: ResourceBinding<FactoryTriggerBlobEventConfig, FactoryTriggerBlobEventAttrs> = {
  wireType: "azurerm_data_factory_trigger_blob_event",
  fields: {
    activated: "activated",
    additionalProperties: "additional_properties",
    annotations: "annotations",
    blobPathBeginsWith: "blob_path_begins_with",
    blobPathEndsWith: "blob_path_ends_with",
    dataFactoryId: "data_factory_id",
    description: "description",
    events: "events",
    id: "id",
    ignoreEmptyBlobs: "ignore_empty_blobs",
    name: "name",
    storageAccountId: "storage_account_id",
    pipeline: {
      wireName: "pipeline",
      kind: "set",
      fields: FactoryTriggerBlobEvent_PipelineFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FactoryTriggerBlobEvent_TimeoutsFields,
    },
  },
};
