// Code generated by `ubx sdk gen` from azurerm_data_factory_linked_service_azure_databricks. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FactoryLinkedServiceAzureDatabricks_InstancePool {
  clusterVersion: string;
  instancePoolId: string;
  maxNumberOfWorkers: number;
  minNumberOfWorkers: number;
}

export interface FactoryLinkedServiceAzureDatabricks_KeyVaultPassword {
  linkedServiceName: string;
  secretName: string;
}

export interface FactoryLinkedServiceAzureDatabricks_NewClusterConfig {
  clusterVersion: string;
  customTags: Record<string, string>;
  driverNodeType: string;
  initScripts: string[];
  logDestination: string;
  maxNumberOfWorkers: number;
  minNumberOfWorkers: number;
  nodeType: string;
  sparkConfig: Record<string, string>;
  sparkEnvironmentVariables: Record<string, string>;
}

export interface FactoryLinkedServiceAzureDatabricks_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FactoryLinkedServiceAzureDatabricks_InstancePoolFields: FieldMap = {
  clusterVersion: "cluster_version",
  instancePoolId: "instance_pool_id",
  maxNumberOfWorkers: "max_number_of_workers",
  minNumberOfWorkers: "min_number_of_workers",
};

const FactoryLinkedServiceAzureDatabricks_KeyVaultPasswordFields: FieldMap = {
  linkedServiceName: "linked_service_name",
  secretName: "secret_name",
};

const FactoryLinkedServiceAzureDatabricks_NewClusterConfigFields: FieldMap = {
  clusterVersion: "cluster_version",
  customTags: "custom_tags",
  driverNodeType: "driver_node_type",
  initScripts: "init_scripts",
  logDestination: "log_destination",
  maxNumberOfWorkers: "max_number_of_workers",
  minNumberOfWorkers: "min_number_of_workers",
  nodeType: "node_type",
  sparkConfig: "spark_config",
  sparkEnvironmentVariables: "spark_environment_variables",
};

const FactoryLinkedServiceAzureDatabricks_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FactoryLinkedServiceAzureDatabricksConfig {
  accessToken?: string | Computed<string>;
  adbDomain: string | Computed<string>;
  additionalProperties?: Record<string, string> | Computed<Record<string, string>>;
  annotations?: string[] | Computed<string[]>;
  dataFactoryId: string | Computed<string>;
  description?: string | Computed<string>;
  existingClusterId?: string | Computed<string>;
  id?: string | Computed<string>;
  integrationRuntimeName?: string | Computed<string>;
  msiWorkspaceId?: string | Computed<string>;
  name: string | Computed<string>;
  parameters?: Record<string, string> | Computed<Record<string, string>>;
  instancePool?: FactoryLinkedServiceAzureDatabricks_InstancePool[] | Computed<FactoryLinkedServiceAzureDatabricks_InstancePool[]>;
  keyVaultPassword?: FactoryLinkedServiceAzureDatabricks_KeyVaultPassword[] | Computed<FactoryLinkedServiceAzureDatabricks_KeyVaultPassword[]>;
  newClusterConfig?: FactoryLinkedServiceAzureDatabricks_NewClusterConfig[] | Computed<FactoryLinkedServiceAzureDatabricks_NewClusterConfig[]>;
  timeouts?: FactoryLinkedServiceAzureDatabricks_Timeouts | Computed<FactoryLinkedServiceAzureDatabricks_Timeouts>;
}

export interface FactoryLinkedServiceAzureDatabricksAttrs {
  accessToken: string;
  adbDomain: string;
  additionalProperties: Record<string, string>;
  annotations: string[];
  dataFactoryId: string;
  description: string;
  existingClusterId: string;
  id: string;
  integrationRuntimeName: string;
  msiWorkspaceId: string;
  name: string;
  parameters: Record<string, string>;
  instancePool: FactoryLinkedServiceAzureDatabricks_InstancePool[];
  keyVaultPassword: FactoryLinkedServiceAzureDatabricks_KeyVaultPassword[];
  newClusterConfig: FactoryLinkedServiceAzureDatabricks_NewClusterConfig[];
  timeouts: FactoryLinkedServiceAzureDatabricks_Timeouts;
}

export const FactoryLinkedServiceAzureDatabricks: ResourceBinding<FactoryLinkedServiceAzureDatabricksConfig, FactoryLinkedServiceAzureDatabricksAttrs> = {
  wireType: "azurerm_data_factory_linked_service_azure_databricks",
  fields: {
    accessToken: "access_token",
    adbDomain: "adb_domain",
    additionalProperties: "additional_properties",
    annotations: "annotations",
    dataFactoryId: "data_factory_id",
    description: "description",
    existingClusterId: "existing_cluster_id",
    id: "id",
    integrationRuntimeName: "integration_runtime_name",
    msiWorkspaceId: "msi_workspace_id",
    name: "name",
    parameters: "parameters",
    instancePool: {
      wireName: "instance_pool",
      kind: "list",
      fields: FactoryLinkedServiceAzureDatabricks_InstancePoolFields,
    },
    keyVaultPassword: {
      wireName: "key_vault_password",
      kind: "list",
      fields: FactoryLinkedServiceAzureDatabricks_KeyVaultPasswordFields,
    },
    newClusterConfig: {
      wireName: "new_cluster_config",
      kind: "list",
      fields: FactoryLinkedServiceAzureDatabricks_NewClusterConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FactoryLinkedServiceAzureDatabricks_TimeoutsFields,
    },
  },
};
