// Code generated by `ubx sdk gen` from azurerm_data_protection_backup_vault_customer_managed_key. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ProtectionBackupVaultCustomerManagedKey_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ProtectionBackupVaultCustomerManagedKey_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ProtectionBackupVaultCustomerManagedKeyConfig {
  dataProtectionBackupVaultId: string | Computed<string>;
  id?: string | Computed<string>;
  keyVaultKeyId: string | Computed<string>;
  timeouts?: ProtectionBackupVaultCustomerManagedKey_Timeouts | Computed<ProtectionBackupVaultCustomerManagedKey_Timeouts>;
}

export interface ProtectionBackupVaultCustomerManagedKeyAttrs {
  dataProtectionBackupVaultId: string;
  id: string;
  keyVaultKeyId: string;
  timeouts: ProtectionBackupVaultCustomerManagedKey_Timeouts;
}

export const ProtectionBackupVaultCustomerManagedKey: ResourceBinding<ProtectionBackupVaultCustomerManagedKeyConfig, ProtectionBackupVaultCustomerManagedKeyAttrs> = {
  wireType: "azurerm_data_protection_backup_vault_customer_managed_key",
  fields: {
    dataProtectionBackupVaultId: "data_protection_backup_vault_id",
    id: "id",
    keyVaultKeyId: "key_vault_key_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ProtectionBackupVaultCustomerManagedKey_TimeoutsFields,
    },
  },
};
