// Code generated by `ubx sdk gen` from azurerm_cdn_frontdoor_route. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FrontdoorRoute_Cache {
  compressionEnabled: boolean;
  contentTypesToCompress: string[];
  queryStringCachingBehavior: string;
  queryStrings: string[];
}

export interface FrontdoorRoute_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FrontdoorRoute_CacheFields: FieldMap = {
  compressionEnabled: "compression_enabled",
  contentTypesToCompress: "content_types_to_compress",
  queryStringCachingBehavior: "query_string_caching_behavior",
  queryStrings: "query_strings",
};

const FrontdoorRoute_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FrontdoorRouteConfig {
  cdnFrontdoorCustomDomainIds?: string[] | Computed<string[]>;
  cdnFrontdoorEndpointId: string | Computed<string>;
  cdnFrontdoorOriginGroupId: string | Computed<string>;
  cdnFrontdoorOriginIds?: string[] | Computed<string[]>;
  cdnFrontdoorOriginPath?: string | Computed<string>;
  cdnFrontdoorRuleSetIds?: string[] | Computed<string[]>;
  enabled?: boolean | Computed<boolean>;
  forwardingProtocol?: string | Computed<string>;
  httpsRedirectEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  linkToDefaultDomain?: boolean | Computed<boolean>;
  name: string | Computed<string>;
  patternsToMatch: string[] | Computed<string[]>;
  supportedProtocols: string[] | Computed<string[]>;
  cache?: FrontdoorRoute_Cache[] | Computed<FrontdoorRoute_Cache[]>;
  timeouts?: FrontdoorRoute_Timeouts | Computed<FrontdoorRoute_Timeouts>;
}

export interface FrontdoorRouteAttrs {
  cdnFrontdoorCustomDomainIds: string[];
  cdnFrontdoorEndpointId: string;
  cdnFrontdoorOriginGroupId: string;
  cdnFrontdoorOriginIds: string[];
  cdnFrontdoorOriginPath: string;
  cdnFrontdoorRuleSetIds: string[];
  enabled: boolean;
  forwardingProtocol: string;
  httpsRedirectEnabled: boolean;
  id: string;
  linkToDefaultDomain: boolean;
  name: string;
  patternsToMatch: string[];
  supportedProtocols: string[];
  cache: FrontdoorRoute_Cache[];
  timeouts: FrontdoorRoute_Timeouts;
}

export const FrontdoorRoute: ResourceBinding<FrontdoorRouteConfig, FrontdoorRouteAttrs> = {
  wireType: "azurerm_cdn_frontdoor_route",
  fields: {
    cdnFrontdoorCustomDomainIds: "cdn_frontdoor_custom_domain_ids",
    cdnFrontdoorEndpointId: "cdn_frontdoor_endpoint_id",
    cdnFrontdoorOriginGroupId: "cdn_frontdoor_origin_group_id",
    cdnFrontdoorOriginIds: "cdn_frontdoor_origin_ids",
    cdnFrontdoorOriginPath: "cdn_frontdoor_origin_path",
    cdnFrontdoorRuleSetIds: "cdn_frontdoor_rule_set_ids",
    enabled: "enabled",
    forwardingProtocol: "forwarding_protocol",
    httpsRedirectEnabled: "https_redirect_enabled",
    id: "id",
    linkToDefaultDomain: "link_to_default_domain",
    name: "name",
    patternsToMatch: "patterns_to_match",
    supportedProtocols: "supported_protocols",
    cache: {
      wireName: "cache",
      kind: "list",
      fields: FrontdoorRoute_CacheFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FrontdoorRoute_TimeoutsFields,
    },
  },
};
