// Code generated by `ubx sdk gen` from azurerm_cdn_frontdoor_custom_domain. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FrontdoorCustomDomain_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

export interface FrontdoorCustomDomain_Tls_CipherSuite_CustomCiphers {
  tls12: string[];
  tls13: string[];
}

export interface FrontdoorCustomDomain_Tls_CipherSuite {
  type: string;
  customCiphers: FrontdoorCustomDomain_Tls_CipherSuite_CustomCiphers[];
}

export interface FrontdoorCustomDomain_Tls {
  cdnFrontdoorSecretId: string;
  certificateType: string;
  minimumVersion: string;
  cipherSuite: FrontdoorCustomDomain_Tls_CipherSuite[];
}

const FrontdoorCustomDomain_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

const FrontdoorCustomDomain_Tls_CipherSuite_CustomCiphersFields: FieldMap = {
  tls12: "tls12",
  tls13: "tls13",
};

const FrontdoorCustomDomain_Tls_CipherSuiteFields: FieldMap = {
  type: "type",
  customCiphers: {
    wireName: "custom_ciphers",
    kind: "list",
    fields: FrontdoorCustomDomain_Tls_CipherSuite_CustomCiphersFields,
  },
};

const FrontdoorCustomDomain_TlsFields: FieldMap = {
  cdnFrontdoorSecretId: "cdn_frontdoor_secret_id",
  certificateType: "certificate_type",
  minimumVersion: "minimum_version",
  cipherSuite: {
    wireName: "cipher_suite",
    kind: "list",
    fields: FrontdoorCustomDomain_Tls_CipherSuiteFields,
  },
};

export interface FrontdoorCustomDomainConfig {
  cdnFrontdoorProfileId: string | Computed<string>;
  dnsZoneId?: string | Computed<string>;
  hostName: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  timeouts?: FrontdoorCustomDomain_Timeouts | Computed<FrontdoorCustomDomain_Timeouts>;
  tls?: FrontdoorCustomDomain_Tls[] | Computed<FrontdoorCustomDomain_Tls[]>;
}

export interface FrontdoorCustomDomainAttrs {
  cdnFrontdoorProfileId: string;
  dnsZoneId: string;
  expirationDate: string;
  hostName: string;
  id: string;
  name: string;
  validationToken: string;
  timeouts: FrontdoorCustomDomain_Timeouts;
  tls: FrontdoorCustomDomain_Tls[];
}

export const FrontdoorCustomDomain: ResourceBinding<FrontdoorCustomDomainConfig, FrontdoorCustomDomainAttrs> = {
  wireType: "azurerm_cdn_frontdoor_custom_domain",
  fields: {
    cdnFrontdoorProfileId: "cdn_frontdoor_profile_id",
    dnsZoneId: "dns_zone_id",
    hostName: "host_name",
    id: "id",
    name: "name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FrontdoorCustomDomain_TimeoutsFields,
    },
    tls: {
      wireName: "tls",
      kind: "list",
      fields: FrontdoorCustomDomain_TlsFields,
    },
  },
};
