// Code generated by `ubx sdk gen` from azurerm_cdn_frontdoor_profile. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FrontdoorProfile_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface FrontdoorProfile_LogScrubbingRule {
  matchVariable: string;
}

export interface FrontdoorProfile_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FrontdoorProfile_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const FrontdoorProfile_LogScrubbingRuleFields: FieldMap = {
  matchVariable: "match_variable",
};

const FrontdoorProfile_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FrontdoorProfileConfig {
  id?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  responseTimeoutSeconds?: number | Computed<number>;
  skuName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  identity?: FrontdoorProfile_Identity[] | Computed<FrontdoorProfile_Identity[]>;
  logScrubbingRule?: FrontdoorProfile_LogScrubbingRule[] | Computed<FrontdoorProfile_LogScrubbingRule[]>;
  timeouts?: FrontdoorProfile_Timeouts | Computed<FrontdoorProfile_Timeouts>;
}

export interface FrontdoorProfileAttrs {
  id: string;
  name: string;
  resourceGroupName: string;
  resourceGuid: string;
  responseTimeoutSeconds: number;
  skuName: string;
  tags: Record<string, string>;
  identity: FrontdoorProfile_Identity[];
  logScrubbingRule: FrontdoorProfile_LogScrubbingRule[];
  timeouts: FrontdoorProfile_Timeouts;
}

export const FrontdoorProfile: ResourceBinding<FrontdoorProfileConfig, FrontdoorProfileAttrs> = {
  wireType: "azurerm_cdn_frontdoor_profile",
  fields: {
    id: "id",
    name: "name",
    resourceGroupName: "resource_group_name",
    responseTimeoutSeconds: "response_timeout_seconds",
    skuName: "sku_name",
    tags: "tags",
    identity: {
      wireName: "identity",
      kind: "list",
      fields: FrontdoorProfile_IdentityFields,
    },
    logScrubbingRule: {
      wireName: "log_scrubbing_rule",
      kind: "set",
      fields: FrontdoorProfile_LogScrubbingRuleFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FrontdoorProfile_TimeoutsFields,
    },
  },
};
