// Code generated by `ubx sdk gen` from azurerm_shared_image_gallery. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ImageGallery_Sharing_CommunityGallery {
  eula: string;
  name: string;
  prefix: string;
  publisherEmail: string;
  publisherUri: string;
}

export interface ImageGallery_Sharing {
  permission: string;
  communityGallery: ImageGallery_Sharing_CommunityGallery[];
}

export interface ImageGallery_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ImageGallery_Sharing_CommunityGalleryFields: FieldMap = {
  eula: "eula",
  name: "name",
  prefix: "prefix",
  publisherEmail: "publisher_email",
  publisherUri: "publisher_uri",
};

const ImageGallery_SharingFields: FieldMap = {
  permission: "permission",
  communityGallery: {
    wireName: "community_gallery",
    kind: "list",
    fields: ImageGallery_Sharing_CommunityGalleryFields,
  },
};

const ImageGallery_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ImageGalleryConfig {
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  sharing?: ImageGallery_Sharing[] | Computed<ImageGallery_Sharing[]>;
  timeouts?: ImageGallery_Timeouts | Computed<ImageGallery_Timeouts>;
}

export interface ImageGalleryAttrs {
  description: string;
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  uniqueName: string;
  sharing: ImageGallery_Sharing[];
  timeouts: ImageGallery_Timeouts;
}

export const ImageGallery: ResourceBinding<ImageGalleryConfig, ImageGalleryAttrs> = {
  wireType: "azurerm_shared_image_gallery",
  fields: {
    description: "description",
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    sharing: {
      wireName: "sharing",
      kind: "list",
      fields: ImageGallery_SharingFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ImageGallery_TimeoutsFields,
    },
  },
};
