// Code generated by `ubx sdk gen` from azurerm_shared_image. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Image_Identifier {
  offer: string;
  publisher: string;
  sku: string;
}

export interface Image_PurchasePlan {
  name: string;
  product: string;
  publisher: string;
}

export interface Image_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Image_IdentifierFields: FieldMap = {
  offer: "offer",
  publisher: "publisher",
  sku: "sku",
};

const Image_PurchasePlanFields: FieldMap = {
  name: "name",
  product: "product",
  publisher: "publisher",
};

const Image_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ImageConfig {
  acceleratedNetworkSupportEnabled?: boolean | Computed<boolean>;
  architecture?: string | Computed<string>;
  confidentialVmEnabled?: boolean | Computed<boolean>;
  confidentialVmSupported?: boolean | Computed<boolean>;
  description?: string | Computed<string>;
  diskControllerTypeNvmeEnabled?: boolean | Computed<boolean>;
  diskTypesNotAllowed?: string[] | Computed<string[]>;
  endOfLifeDate?: string | Computed<string>;
  eula?: string | Computed<string>;
  galleryName: string | Computed<string>;
  hibernationEnabled?: boolean | Computed<boolean>;
  hyperVGeneration?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  maxRecommendedMemoryInGb?: number | Computed<number>;
  maxRecommendedVcpuCount?: number | Computed<number>;
  minRecommendedMemoryInGb?: number | Computed<number>;
  minRecommendedVcpuCount?: number | Computed<number>;
  name: string | Computed<string>;
  osType: string | Computed<string>;
  privacyStatementUri?: string | Computed<string>;
  releaseNoteUri?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  specialized?: boolean | Computed<boolean>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  trustedLaunchEnabled?: boolean | Computed<boolean>;
  trustedLaunchSupported?: boolean | Computed<boolean>;
  identifier?: Image_Identifier[] | Computed<Image_Identifier[]>;
  purchasePlan?: Image_PurchasePlan[] | Computed<Image_PurchasePlan[]>;
  timeouts?: Image_Timeouts | Computed<Image_Timeouts>;
}

export interface ImageAttrs {
  acceleratedNetworkSupportEnabled: boolean;
  architecture: string;
  confidentialVmEnabled: boolean;
  confidentialVmSupported: boolean;
  description: string;
  diskControllerTypeNvmeEnabled: boolean;
  diskTypesNotAllowed: string[];
  endOfLifeDate: string;
  eula: string;
  galleryName: string;
  hibernationEnabled: boolean;
  hyperVGeneration: string;
  id: string;
  location: string;
  maxRecommendedMemoryInGb: number;
  maxRecommendedVcpuCount: number;
  minRecommendedMemoryInGb: number;
  minRecommendedVcpuCount: number;
  name: string;
  osType: string;
  privacyStatementUri: string;
  releaseNoteUri: string;
  resourceGroupName: string;
  specialized: boolean;
  tags: Record<string, string>;
  trustedLaunchEnabled: boolean;
  trustedLaunchSupported: boolean;
  identifier: Image_Identifier[];
  purchasePlan: Image_PurchasePlan[];
  timeouts: Image_Timeouts;
}

export const Image: ResourceBinding<ImageConfig, ImageAttrs> = {
  wireType: "azurerm_shared_image",
  fields: {
    acceleratedNetworkSupportEnabled: "accelerated_network_support_enabled",
    architecture: "architecture",
    confidentialVmEnabled: "confidential_vm_enabled",
    confidentialVmSupported: "confidential_vm_supported",
    description: "description",
    diskControllerTypeNvmeEnabled: "disk_controller_type_nvme_enabled",
    diskTypesNotAllowed: "disk_types_not_allowed",
    endOfLifeDate: "end_of_life_date",
    eula: "eula",
    galleryName: "gallery_name",
    hibernationEnabled: "hibernation_enabled",
    hyperVGeneration: "hyper_v_generation",
    id: "id",
    location: "location",
    maxRecommendedMemoryInGb: "max_recommended_memory_in_gb",
    maxRecommendedVcpuCount: "max_recommended_vcpu_count",
    minRecommendedMemoryInGb: "min_recommended_memory_in_gb",
    minRecommendedVcpuCount: "min_recommended_vcpu_count",
    name: "name",
    osType: "os_type",
    privacyStatementUri: "privacy_statement_uri",
    releaseNoteUri: "release_note_uri",
    resourceGroupName: "resource_group_name",
    specialized: "specialized",
    tags: "tags",
    trustedLaunchEnabled: "trusted_launch_enabled",
    trustedLaunchSupported: "trusted_launch_supported",
    identifier: {
      wireName: "identifier",
      kind: "list",
      fields: Image_IdentifierFields,
    },
    purchasePlan: {
      wireName: "purchase_plan",
      kind: "list",
      fields: Image_PurchasePlanFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Image_TimeoutsFields,
    },
  },
};
