// Code generated by `ubx sdk gen` from azurerm_virtual_hub_connection. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HubConnection_Routing_PropagatedRouteTable {
  labels: string[];
  routeTableIds: string[];
}

export interface HubConnection_Routing_StaticVnetRoute {
  addressPrefixes: string[];
  name: string;
  nextHopIpAddress: string;
}

export interface HubConnection_Routing {
  associatedRouteTableId: string;
  inboundRouteMapId: string;
  outboundRouteMapId: string;
  staticVnetLocalRouteOverrideCriteria: string;
  staticVnetPropagateStaticRoutesEnabled: boolean;
  propagatedRouteTable: HubConnection_Routing_PropagatedRouteTable[];
  staticVnetRoute: HubConnection_Routing_StaticVnetRoute[];
}

export interface HubConnection_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const HubConnection_Routing_PropagatedRouteTableFields: FieldMap = {
  labels: "labels",
  routeTableIds: "route_table_ids",
};

const HubConnection_Routing_StaticVnetRouteFields: FieldMap = {
  addressPrefixes: "address_prefixes",
  name: "name",
  nextHopIpAddress: "next_hop_ip_address",
};

const HubConnection_RoutingFields: FieldMap = {
  associatedRouteTableId: "associated_route_table_id",
  inboundRouteMapId: "inbound_route_map_id",
  outboundRouteMapId: "outbound_route_map_id",
  staticVnetLocalRouteOverrideCriteria: "static_vnet_local_route_override_criteria",
  staticVnetPropagateStaticRoutesEnabled: "static_vnet_propagate_static_routes_enabled",
  propagatedRouteTable: {
    wireName: "propagated_route_table",
    kind: "list",
    fields: HubConnection_Routing_PropagatedRouteTableFields,
  },
  staticVnetRoute: {
    wireName: "static_vnet_route",
    kind: "list",
    fields: HubConnection_Routing_StaticVnetRouteFields,
  },
};

const HubConnection_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface HubConnectionConfig {
  id?: string | Computed<string>;
  internetSecurityEnabled?: boolean | Computed<boolean>;
  name: string | Computed<string>;
  remoteVirtualNetworkId: string | Computed<string>;
  virtualHubId: string | Computed<string>;
  routing?: HubConnection_Routing[] | Computed<HubConnection_Routing[]>;
  timeouts?: HubConnection_Timeouts | Computed<HubConnection_Timeouts>;
}

export interface HubConnectionAttrs {
  id: string;
  internetSecurityEnabled: boolean;
  name: string;
  remoteVirtualNetworkId: string;
  virtualHubId: string;
  routing: HubConnection_Routing[];
  timeouts: HubConnection_Timeouts;
}

export const HubConnection: ResourceBinding<HubConnectionConfig, HubConnectionAttrs> = {
  wireType: "azurerm_virtual_hub_connection",
  fields: {
    id: "id",
    internetSecurityEnabled: "internet_security_enabled",
    name: "name",
    remoteVirtualNetworkId: "remote_virtual_network_id",
    virtualHubId: "virtual_hub_id",
    routing: {
      wireName: "routing",
      kind: "list",
      fields: HubConnection_RoutingFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: HubConnection_TimeoutsFields,
    },
  },
};
