// Code generated by `ubx sdk gen` from azurerm_virtual_hub_route_table. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HubRouteTable_Route {
  destinations: string[];
  destinationsType: string;
  name: string;
  nextHop: string;
  nextHopType: string;
}

export interface HubRouteTable_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const HubRouteTable_RouteFields: FieldMap = {
  destinations: "destinations",
  destinationsType: "destinations_type",
  name: "name",
  nextHop: "next_hop",
  nextHopType: "next_hop_type",
};

const HubRouteTable_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface HubRouteTableConfig {
  id?: string | Computed<string>;
  labels?: string[] | Computed<string[]>;
  name: string | Computed<string>;
  virtualHubId: string | Computed<string>;
  route?: HubRouteTable_Route[] | Computed<HubRouteTable_Route[]>;
  timeouts?: HubRouteTable_Timeouts | Computed<HubRouteTable_Timeouts>;
}

export interface HubRouteTableAttrs {
  id: string;
  labels: string[];
  name: string;
  virtualHubId: string;
  route: HubRouteTable_Route[];
  timeouts: HubRouteTable_Timeouts;
}

export const HubRouteTable: ResourceBinding<HubRouteTableConfig, HubRouteTableAttrs> = {
  wireType: "azurerm_virtual_hub_route_table",
  fields: {
    id: "id",
    labels: "labels",
    name: "name",
    virtualHubId: "virtual_hub_id",
    route: {
      wireName: "route",
      kind: "set",
      fields: HubRouteTable_RouteFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: HubRouteTable_TimeoutsFields,
    },
  },
};
