// Code generated by `ubx sdk gen` from azurerm_virtual_machine_gallery_application_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MachineGalleryApplicationAssignment_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const MachineGalleryApplicationAssignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface MachineGalleryApplicationAssignmentConfig {
  configurationBlobUri?: string | Computed<string>;
  galleryApplicationVersionId: string | Computed<string>;
  id?: string | Computed<string>;
  order?: number | Computed<number>;
  tag?: string | Computed<string>;
  virtualMachineId: string | Computed<string>;
  timeouts?: MachineGalleryApplicationAssignment_Timeouts | Computed<MachineGalleryApplicationAssignment_Timeouts>;
}

export interface MachineGalleryApplicationAssignmentAttrs {
  configurationBlobUri: string;
  galleryApplicationVersionId: string;
  id: string;
  order: number;
  tag: string;
  virtualMachineId: string;
  timeouts: MachineGalleryApplicationAssignment_Timeouts;
}

export const MachineGalleryApplicationAssignment: ResourceBinding<MachineGalleryApplicationAssignmentConfig, MachineGalleryApplicationAssignmentAttrs> = {
  wireType: "azurerm_virtual_machine_gallery_application_assignment",
  fields: {
    configurationBlobUri: "configuration_blob_uri",
    galleryApplicationVersionId: "gallery_application_version_id",
    id: "id",
    order: "order",
    tag: "tag",
    virtualMachineId: "virtual_machine_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: MachineGalleryApplicationAssignment_TimeoutsFields,
    },
  },
};
