// Code generated by `ubx sdk gen` from azurerm_virtual_machine_automanage_configuration_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MachineAutomanageConfigurationAssignment_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const MachineAutomanageConfigurationAssignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface MachineAutomanageConfigurationAssignmentConfig {
  configurationId: string | Computed<string>;
  id?: string | Computed<string>;
  virtualMachineId: string | Computed<string>;
  timeouts?: MachineAutomanageConfigurationAssignment_Timeouts | Computed<MachineAutomanageConfigurationAssignment_Timeouts>;
}

export interface MachineAutomanageConfigurationAssignmentAttrs {
  configurationId: string;
  id: string;
  virtualMachineId: string;
  timeouts: MachineAutomanageConfigurationAssignment_Timeouts;
}

export const MachineAutomanageConfigurationAssignment: ResourceBinding<MachineAutomanageConfigurationAssignmentConfig, MachineAutomanageConfigurationAssignmentAttrs> = {
  wireType: "azurerm_virtual_machine_automanage_configuration_assignment",
  fields: {
    configurationId: "configuration_id",
    id: "id",
    virtualMachineId: "virtual_machine_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: MachineAutomanageConfigurationAssignment_TimeoutsFields,
    },
  },
};
