// Code generated by `ubx sdk gen` from azurerm_role_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Assignment_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const Assignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface AssignmentConfig {
  condition?: string | Computed<string>;
  conditionVersion?: string | Computed<string>;
  delegatedManagedIdentityResourceId?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  principalId: string | Computed<string>;
  principalType?: string | Computed<string>;
  roleDefinitionId?: string | Computed<string>;
  roleDefinitionName?: string | Computed<string>;
  scope: string | Computed<string>;
  skipServicePrincipalAadCheck?: boolean | Computed<boolean>;
  timeouts?: Assignment_Timeouts | Computed<Assignment_Timeouts>;
}

export interface AssignmentAttrs {
  condition: string;
  conditionVersion: string;
  delegatedManagedIdentityResourceId: string;
  description: string;
  id: string;
  name: string;
  principalId: string;
  principalType: string;
  roleDefinitionId: string;
  roleDefinitionName: string;
  scope: string;
  skipServicePrincipalAadCheck: boolean;
  timeouts: Assignment_Timeouts;
}

export const Assignment: ResourceBinding<AssignmentConfig, AssignmentAttrs> = {
  wireType: "azurerm_role_assignment",
  fields: {
    condition: "condition",
    conditionVersion: "condition_version",
    delegatedManagedIdentityResourceId: "delegated_managed_identity_resource_id",
    description: "description",
    id: "id",
    name: "name",
    principalId: "principal_id",
    principalType: "principal_type",
    roleDefinitionId: "role_definition_id",
    roleDefinitionName: "role_definition_name",
    scope: "scope",
    skipServicePrincipalAadCheck: "skip_service_principal_aad_check",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Assignment_TimeoutsFields,
    },
  },
};
