// Code generated by `ubx sdk gen` from azurerm_automation_connection_service_principal. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConnectionServicePrincipal_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ConnectionServicePrincipal_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ConnectionServicePrincipalConfig {
  applicationId: string | Computed<string>;
  automationAccountName: string | Computed<string>;
  certificateThumbprint: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  subscriptionId: string | Computed<string>;
  tenantId: string | Computed<string>;
  timeouts?: ConnectionServicePrincipal_Timeouts | Computed<ConnectionServicePrincipal_Timeouts>;
}

export interface ConnectionServicePrincipalAttrs {
  applicationId: string;
  automationAccountName: string;
  certificateThumbprint: string;
  description: string;
  id: string;
  name: string;
  resourceGroupName: string;
  subscriptionId: string;
  tenantId: string;
  timeouts: ConnectionServicePrincipal_Timeouts;
}

export const ConnectionServicePrincipal: ResourceBinding<ConnectionServicePrincipalConfig, ConnectionServicePrincipalAttrs> = {
  wireType: "azurerm_automation_connection_service_principal",
  fields: {
    applicationId: "application_id",
    automationAccountName: "automation_account_name",
    certificateThumbprint: "certificate_thumbprint",
    description: "description",
    id: "id",
    name: "name",
    resourceGroupName: "resource_group_name",
    subscriptionId: "subscription_id",
    tenantId: "tenant_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ConnectionServicePrincipal_TimeoutsFields,
    },
  },
};
