// Code generated by `ubx sdk gen` from azurerm_automation_connection_classic_certificate. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConnectionClassicCertificate_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ConnectionClassicCertificate_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ConnectionClassicCertificateConfig {
  automationAccountName: string | Computed<string>;
  certificateAssetName: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  subscriptionId: string | Computed<string>;
  subscriptionName: string | Computed<string>;
  timeouts?: ConnectionClassicCertificate_Timeouts | Computed<ConnectionClassicCertificate_Timeouts>;
}

export interface ConnectionClassicCertificateAttrs {
  automationAccountName: string;
  certificateAssetName: string;
  description: string;
  id: string;
  name: string;
  resourceGroupName: string;
  subscriptionId: string;
  subscriptionName: string;
  timeouts: ConnectionClassicCertificate_Timeouts;
}

export const ConnectionClassicCertificate: ResourceBinding<ConnectionClassicCertificateConfig, ConnectionClassicCertificateAttrs> = {
  wireType: "azurerm_automation_connection_classic_certificate",
  fields: {
    automationAccountName: "automation_account_name",
    certificateAssetName: "certificate_asset_name",
    description: "description",
    id: "id",
    name: "name",
    resourceGroupName: "resource_group_name",
    subscriptionId: "subscription_id",
    subscriptionName: "subscription_name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ConnectionClassicCertificate_TimeoutsFields,
    },
  },
};
