// Code generated by `ubx sdk gen` from azurerm_automation_python3_package. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Python3Package_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Python3Package_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface Python3PackageConfig {
  automationAccountName: string | Computed<string>;
  contentUri: string | Computed<string>;
  contentVersion?: string | Computed<string>;
  hashAlgorithm?: string | Computed<string>;
  hashValue?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: Python3Package_Timeouts | Computed<Python3Package_Timeouts>;
}

export interface Python3PackageAttrs {
  automationAccountName: string;
  contentUri: string;
  contentVersion: string;
  hashAlgorithm: string;
  hashValue: string;
  id: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  timeouts: Python3Package_Timeouts;
}

export const Python3Package: ResourceBinding<Python3PackageConfig, Python3PackageAttrs> = {
  wireType: "azurerm_automation_python3_package",
  fields: {
    automationAccountName: "automation_account_name",
    contentUri: "content_uri",
    contentVersion: "content_version",
    hashAlgorithm: "hash_algorithm",
    hashValue: "hash_value",
    id: "id",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Python3Package_TimeoutsFields,
    },
  },
};
