// Code generated by `ubx sdk gen` from azurerm_automation_variable_int. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface VariableInt_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const VariableInt_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface VariableIntConfig {
  automationAccountName: string | Computed<string>;
  description?: string | Computed<string>;
  encrypted?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  value?: number | Computed<number>;
  timeouts?: VariableInt_Timeouts | Computed<VariableInt_Timeouts>;
}

export interface VariableIntAttrs {
  automationAccountName: string;
  description: string;
  encrypted: boolean;
  id: string;
  name: string;
  resourceGroupName: string;
  value: number;
  timeouts: VariableInt_Timeouts;
}

export const VariableInt: ResourceBinding<VariableIntConfig, VariableIntAttrs> = {
  wireType: "azurerm_automation_variable_int",
  fields: {
    automationAccountName: "automation_account_name",
    description: "description",
    encrypted: "encrypted",
    id: "id",
    name: "name",
    resourceGroupName: "resource_group_name",
    value: "value",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: VariableInt_TimeoutsFields,
    },
  },
};
