// Code generated by `ubx sdk gen` from azurerm_web_pubsub_socketio. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PubsubSocketio_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface PubsubSocketio_Sku {
  capacity: number;
  name: string;
}

export interface PubsubSocketio_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const PubsubSocketio_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const PubsubSocketio_SkuFields: FieldMap = {
  capacity: "capacity",
  name: "name",
};

const PubsubSocketio_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface PubsubSocketioConfig {
  aadAuthEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  liveTraceConnectivityLogsEnabled?: boolean | Computed<boolean>;
  liveTraceEnabled?: boolean | Computed<boolean>;
  liveTraceHttpRequestLogsEnabled?: boolean | Computed<boolean>;
  liveTraceMessagingLogsEnabled?: boolean | Computed<boolean>;
  localAuthEnabled?: boolean | Computed<boolean>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  publicNetworkAccess?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  serviceMode?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  tlsClientCertEnabled?: boolean | Computed<boolean>;
  identity?: PubsubSocketio_Identity[] | Computed<PubsubSocketio_Identity[]>;
  sku?: PubsubSocketio_Sku[] | Computed<PubsubSocketio_Sku[]>;
  timeouts?: PubsubSocketio_Timeouts | Computed<PubsubSocketio_Timeouts>;
}

export interface PubsubSocketioAttrs {
  aadAuthEnabled: boolean;
  externalIp: string;
  hostname: string;
  id: string;
  liveTraceConnectivityLogsEnabled: boolean;
  liveTraceEnabled: boolean;
  liveTraceHttpRequestLogsEnabled: boolean;
  liveTraceMessagingLogsEnabled: boolean;
  localAuthEnabled: boolean;
  location: string;
  name: string;
  primaryAccessKey: string;
  primaryConnectionString: string;
  publicNetworkAccess: string;
  publicPort: number;
  resourceGroupName: string;
  secondaryAccessKey: string;
  secondaryConnectionString: string;
  serverPort: number;
  serviceMode: string;
  tags: Record<string, string>;
  tlsClientCertEnabled: boolean;
  identity: PubsubSocketio_Identity[];
  sku: PubsubSocketio_Sku[];
  timeouts: PubsubSocketio_Timeouts;
}

export const PubsubSocketio: ResourceBinding<PubsubSocketioConfig, PubsubSocketioAttrs> = {
  wireType: "azurerm_web_pubsub_socketio",
  fields: {
    aadAuthEnabled: "aad_auth_enabled",
    id: "id",
    liveTraceConnectivityLogsEnabled: "live_trace_connectivity_logs_enabled",
    liveTraceEnabled: "live_trace_enabled",
    liveTraceHttpRequestLogsEnabled: "live_trace_http_request_logs_enabled",
    liveTraceMessagingLogsEnabled: "live_trace_messaging_logs_enabled",
    localAuthEnabled: "local_auth_enabled",
    location: "location",
    name: "name",
    publicNetworkAccess: "public_network_access",
    resourceGroupName: "resource_group_name",
    serviceMode: "service_mode",
    tags: "tags",
    tlsClientCertEnabled: "tls_client_cert_enabled",
    identity: {
      wireName: "identity",
      kind: "list",
      fields: PubsubSocketio_IdentityFields,
    },
    sku: {
      wireName: "sku",
      kind: "list",
      fields: PubsubSocketio_SkuFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: PubsubSocketio_TimeoutsFields,
    },
  },
};
