// Code generated by `ubx sdk gen` from azurerm_sentinel_data_connector_azure_security_center. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataConnectorAzureSecurityCenter_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const DataConnectorAzureSecurityCenter_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface DataConnectorAzureSecurityCenterConfig {
  id?: string | Computed<string>;
  logAnalyticsWorkspaceId: string | Computed<string>;
  name: string | Computed<string>;
  subscriptionId?: string | Computed<string>;
  timeouts?: DataConnectorAzureSecurityCenter_Timeouts | Computed<DataConnectorAzureSecurityCenter_Timeouts>;
}

export interface DataConnectorAzureSecurityCenterAttrs {
  id: string;
  logAnalyticsWorkspaceId: string;
  name: string;
  subscriptionId: string;
  timeouts: DataConnectorAzureSecurityCenter_Timeouts;
}

export const DataConnectorAzureSecurityCenter: ResourceBinding<DataConnectorAzureSecurityCenterConfig, DataConnectorAzureSecurityCenterAttrs> = {
  wireType: "azurerm_sentinel_data_connector_azure_security_center",
  fields: {
    id: "id",
    logAnalyticsWorkspaceId: "log_analytics_workspace_id",
    name: "name",
    subscriptionId: "subscription_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DataConnectorAzureSecurityCenter_TimeoutsFields,
    },
  },
};
