// Code generated by `ubx sdk gen` from azurerm_sentinel_data_connector_microsoft_threat_protection. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataConnectorMicrosoftThreatProtection_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const DataConnectorMicrosoftThreatProtection_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface DataConnectorMicrosoftThreatProtectionConfig {
  id?: string | Computed<string>;
  logAnalyticsWorkspaceId: string | Computed<string>;
  name: string | Computed<string>;
  tenantId?: string | Computed<string>;
  timeouts?: DataConnectorMicrosoftThreatProtection_Timeouts | Computed<DataConnectorMicrosoftThreatProtection_Timeouts>;
}

export interface DataConnectorMicrosoftThreatProtectionAttrs {
  id: string;
  logAnalyticsWorkspaceId: string;
  name: string;
  tenantId: string;
  timeouts: DataConnectorMicrosoftThreatProtection_Timeouts;
}

export const DataConnectorMicrosoftThreatProtection: ResourceBinding<DataConnectorMicrosoftThreatProtectionConfig, DataConnectorMicrosoftThreatProtectionAttrs> = {
  wireType: "azurerm_sentinel_data_connector_microsoft_threat_protection",
  fields: {
    id: "id",
    logAnalyticsWorkspaceId: "log_analytics_workspace_id",
    name: "name",
    tenantId: "tenant_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DataConnectorMicrosoftThreatProtection_TimeoutsFields,
    },
  },
};
