// Code generated by `ubx sdk gen` from azurerm_sentinel_metadata. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Metadata_Author {
  email: string;
  link: string;
  name: string;
}

export interface Metadata_Category {
  domains: string[];
  verticals: string[];
}

export interface Metadata_Source {
  id: string;
  kind: string;
  name: string;
}

export interface Metadata_Support {
  email: string;
  link: string;
  name: string;
  tier: string;
}

export interface Metadata_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Metadata_AuthorFields: FieldMap = {
  email: "email",
  link: "link",
  name: "name",
};

const Metadata_CategoryFields: FieldMap = {
  domains: "domains",
  verticals: "verticals",
};

const Metadata_SourceFields: FieldMap = {
  id: "id",
  kind: "kind",
  name: "name",
};

const Metadata_SupportFields: FieldMap = {
  email: "email",
  link: "link",
  name: "name",
  tier: "tier",
};

const Metadata_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface MetadataConfig {
  contentId: string | Computed<string>;
  contentSchemaVersion?: string | Computed<string>;
  customVersion?: string | Computed<string>;
  dependency?: string | Computed<string>;
  firstPublishDate?: string | Computed<string>;
  iconId?: string | Computed<string>;
  id?: string | Computed<string>;
  kind: string | Computed<string>;
  lastPublishDate?: string | Computed<string>;
  name: string | Computed<string>;
  parentId: string | Computed<string>;
  previewImages?: string[] | Computed<string[]>;
  previewImagesDark?: string[] | Computed<string[]>;
  providers?: string[] | Computed<string[]>;
  threatAnalysisTactics?: string[] | Computed<string[]>;
  threatAnalysisTechniques?: string[] | Computed<string[]>;
  version?: string | Computed<string>;
  workspaceId: string | Computed<string>;
  author?: Metadata_Author[] | Computed<Metadata_Author[]>;
  category?: Metadata_Category[] | Computed<Metadata_Category[]>;
  source?: Metadata_Source[] | Computed<Metadata_Source[]>;
  support?: Metadata_Support[] | Computed<Metadata_Support[]>;
  timeouts?: Metadata_Timeouts | Computed<Metadata_Timeouts>;
}

export interface MetadataAttrs {
  contentId: string;
  contentSchemaVersion: string;
  customVersion: string;
  dependency: string;
  firstPublishDate: string;
  iconId: string;
  id: string;
  kind: string;
  lastPublishDate: string;
  name: string;
  parentId: string;
  previewImages: string[];
  previewImagesDark: string[];
  providers: string[];
  threatAnalysisTactics: string[];
  threatAnalysisTechniques: string[];
  version: string;
  workspaceId: string;
  author: Metadata_Author[];
  category: Metadata_Category[];
  source: Metadata_Source[];
  support: Metadata_Support[];
  timeouts: Metadata_Timeouts;
}

export const Metadata: ResourceBinding<MetadataConfig, MetadataAttrs> = {
  wireType: "azurerm_sentinel_metadata",
  fields: {
    contentId: "content_id",
    contentSchemaVersion: "content_schema_version",
    customVersion: "custom_version",
    dependency: "dependency",
    firstPublishDate: "first_publish_date",
    iconId: "icon_id",
    id: "id",
    kind: "kind",
    lastPublishDate: "last_publish_date",
    name: "name",
    parentId: "parent_id",
    previewImages: "preview_images",
    previewImagesDark: "preview_images_dark",
    providers: "providers",
    threatAnalysisTactics: "threat_analysis_tactics",
    threatAnalysisTechniques: "threat_analysis_techniques",
    version: "version",
    workspaceId: "workspace_id",
    author: {
      wireName: "author",
      kind: "list",
      fields: Metadata_AuthorFields,
    },
    category: {
      wireName: "category",
      kind: "list",
      fields: Metadata_CategoryFields,
    },
    source: {
      wireName: "source",
      kind: "list",
      fields: Metadata_SourceFields,
    },
    support: {
      wireName: "support",
      kind: "list",
      fields: Metadata_SupportFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Metadata_TimeoutsFields,
    },
  },
};
