// Code generated by `ubx sdk gen` from azurerm_subscription_policy_remediation. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PolicyRemediation_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const PolicyRemediation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface PolicyRemediationConfig {
  failurePercentage?: number | Computed<number>;
  id?: string | Computed<string>;
  locationFilters?: string[] | Computed<string[]>;
  name: string | Computed<string>;
  parallelDeployments?: number | Computed<number>;
  policyAssignmentId: string | Computed<string>;
  policyDefinitionReferenceId?: string | Computed<string>;
  resourceCount?: number | Computed<number>;
  resourceDiscoveryMode?: string | Computed<string>;
  subscriptionId: string | Computed<string>;
  timeouts?: PolicyRemediation_Timeouts | Computed<PolicyRemediation_Timeouts>;
}

export interface PolicyRemediationAttrs {
  failurePercentage: number;
  id: string;
  locationFilters: string[];
  name: string;
  parallelDeployments: number;
  policyAssignmentId: string;
  policyDefinitionReferenceId: string;
  resourceCount: number;
  resourceDiscoveryMode: string;
  subscriptionId: string;
  timeouts: PolicyRemediation_Timeouts;
}

export const PolicyRemediation: ResourceBinding<PolicyRemediationConfig, PolicyRemediationAttrs> = {
  wireType: "azurerm_subscription_policy_remediation",
  fields: {
    failurePercentage: "failure_percentage",
    id: "id",
    locationFilters: "location_filters",
    name: "name",
    parallelDeployments: "parallel_deployments",
    policyAssignmentId: "policy_assignment_id",
    policyDefinitionReferenceId: "policy_definition_reference_id",
    resourceCount: "resource_count",
    resourceDiscoveryMode: "resource_discovery_mode",
    subscriptionId: "subscription_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: PolicyRemediation_TimeoutsFields,
    },
  },
};
