// Code generated by `ubx sdk gen` from azurerm_chaos_studio_capability. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface StudioCapability_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const StudioCapability_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface StudioCapabilityConfig {
  capabilityType: string | Computed<string>;
  chaosStudioTargetId: string | Computed<string>;
  id?: string | Computed<string>;
  timeouts?: StudioCapability_Timeouts | Computed<StudioCapability_Timeouts>;
}

export interface StudioCapabilityAttrs {
  capabilityType: string;
  chaosStudioTargetId: string;
  id: string;
  urn: string;
  timeouts: StudioCapability_Timeouts;
}

export const StudioCapability: ResourceBinding<StudioCapabilityConfig, StudioCapabilityAttrs> = {
  wireType: "azurerm_chaos_studio_capability",
  fields: {
    capabilityType: "capability_type",
    chaosStudioTargetId: "chaos_studio_target_id",
    id: "id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: StudioCapability_TimeoutsFields,
    },
  },
};
