// Code generated by `ubx sdk gen` from azurerm_mssql_database. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Database_Identity {
  identityIds: string[];
  type: string;
}

export interface Database_Import {
  administratorLogin: string;
  administratorLoginPassword: string;
  authenticationType: string;
  storageAccountId: string;
  storageKey: string;
  storageKeyType: string;
  storageUri: string;
}

export interface Database_LongTermRetentionPolicy {
  monthlyRetention: string;
  weekOfYear: number;
  weeklyRetention: string;
  yearlyRetention: string;
}

export interface Database_ShortTermRetentionPolicy {
  backupIntervalInHours: number;
  retentionDays: number;
}

export interface Database_ThreatDetectionPolicy {
  disabledAlerts: string[];
  emailAccountAdminsEnabled: boolean;
  emailAddresses: string[];
  retentionDays: number;
  state: string;
  storageAccountAccessKey: string;
  storageEndpoint: string;
}

export interface Database_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Database_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  type: "type",
};

const Database_ImportFields: FieldMap = {
  administratorLogin: "administrator_login",
  administratorLoginPassword: "administrator_login_password",
  authenticationType: "authentication_type",
  storageAccountId: "storage_account_id",
  storageKey: "storage_key",
  storageKeyType: "storage_key_type",
  storageUri: "storage_uri",
};

const Database_LongTermRetentionPolicyFields: FieldMap = {
  monthlyRetention: "monthly_retention",
  weekOfYear: "week_of_year",
  weeklyRetention: "weekly_retention",
  yearlyRetention: "yearly_retention",
};

const Database_ShortTermRetentionPolicyFields: FieldMap = {
  backupIntervalInHours: "backup_interval_in_hours",
  retentionDays: "retention_days",
};

const Database_ThreatDetectionPolicyFields: FieldMap = {
  disabledAlerts: "disabled_alerts",
  emailAccountAdminsEnabled: "email_account_admins_enabled",
  emailAddresses: "email_addresses",
  retentionDays: "retention_days",
  state: "state",
  storageAccountAccessKey: "storage_account_access_key",
  storageEndpoint: "storage_endpoint",
};

const Database_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface DatabaseConfig {
  autoPauseDelayInMinutes?: number | Computed<number>;
  collation?: string | Computed<string>;
  createMode?: string | Computed<string>;
  creationSourceDatabaseId?: string | Computed<string>;
  elasticPoolId?: string | Computed<string>;
  enclaveType?: string | Computed<string>;
  geoBackupEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  ledgerEnabled?: boolean | Computed<boolean>;
  licenseType?: string | Computed<string>;
  maintenanceConfigurationName?: string | Computed<string>;
  maxSizeGb?: number | Computed<number>;
  minCapacity?: number | Computed<number>;
  name: string | Computed<string>;
  readReplicaCount?: number | Computed<number>;
  readScale?: boolean | Computed<boolean>;
  recoverDatabaseId?: string | Computed<string>;
  recoveryPointId?: string | Computed<string>;
  restoreDroppedDatabaseId?: string | Computed<string>;
  restoreLongTermRetentionBackupId?: string | Computed<string>;
  restorePointInTime?: string | Computed<string>;
  sampleName?: string | Computed<string>;
  secondaryType?: string | Computed<string>;
  serverId: string | Computed<string>;
  skuName?: string | Computed<string>;
  storageAccountType?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  transparentDataEncryptionEnabled?: boolean | Computed<boolean>;
  transparentDataEncryptionKeyAutomaticRotationEnabled?: boolean | Computed<boolean>;
  transparentDataEncryptionKeyVaultKeyId?: string | Computed<string>;
  zoneRedundant?: boolean | Computed<boolean>;
  identity?: Database_Identity[] | Computed<Database_Identity[]>;
  import?: Database_Import[] | Computed<Database_Import[]>;
  longTermRetentionPolicy?: Database_LongTermRetentionPolicy[] | Computed<Database_LongTermRetentionPolicy[]>;
  shortTermRetentionPolicy?: Database_ShortTermRetentionPolicy[] | Computed<Database_ShortTermRetentionPolicy[]>;
  threatDetectionPolicy?: Database_ThreatDetectionPolicy[] | Computed<Database_ThreatDetectionPolicy[]>;
  timeouts?: Database_Timeouts | Computed<Database_Timeouts>;
}

export interface DatabaseAttrs {
  autoPauseDelayInMinutes: number;
  collation: string;
  createMode: string;
  creationSourceDatabaseId: string;
  elasticPoolId: string;
  enclaveType: string;
  geoBackupEnabled: boolean;
  id: string;
  ledgerEnabled: boolean;
  licenseType: string;
  maintenanceConfigurationName: string;
  maxSizeGb: number;
  minCapacity: number;
  name: string;
  readReplicaCount: number;
  readScale: boolean;
  recoverDatabaseId: string;
  recoveryPointId: string;
  restoreDroppedDatabaseId: string;
  restoreLongTermRetentionBackupId: string;
  restorePointInTime: string;
  sampleName: string;
  secondaryType: string;
  serverId: string;
  skuName: string;
  storageAccountType: string;
  tags: Record<string, string>;
  transparentDataEncryptionEnabled: boolean;
  transparentDataEncryptionKeyAutomaticRotationEnabled: boolean;
  transparentDataEncryptionKeyVaultKeyId: string;
  zoneRedundant: boolean;
  identity: Database_Identity[];
  import: Database_Import[];
  longTermRetentionPolicy: Database_LongTermRetentionPolicy[];
  shortTermRetentionPolicy: Database_ShortTermRetentionPolicy[];
  threatDetectionPolicy: Database_ThreatDetectionPolicy[];
  timeouts: Database_Timeouts;
}

export const Database: ResourceBinding<DatabaseConfig, DatabaseAttrs> = {
  wireType: "azurerm_mssql_database",
  fields: {
    autoPauseDelayInMinutes: "auto_pause_delay_in_minutes",
    collation: "collation",
    createMode: "create_mode",
    creationSourceDatabaseId: "creation_source_database_id",
    elasticPoolId: "elastic_pool_id",
    enclaveType: "enclave_type",
    geoBackupEnabled: "geo_backup_enabled",
    id: "id",
    ledgerEnabled: "ledger_enabled",
    licenseType: "license_type",
    maintenanceConfigurationName: "maintenance_configuration_name",
    maxSizeGb: "max_size_gb",
    minCapacity: "min_capacity",
    name: "name",
    readReplicaCount: "read_replica_count",
    readScale: "read_scale",
    recoverDatabaseId: "recover_database_id",
    recoveryPointId: "recovery_point_id",
    restoreDroppedDatabaseId: "restore_dropped_database_id",
    restoreLongTermRetentionBackupId: "restore_long_term_retention_backup_id",
    restorePointInTime: "restore_point_in_time",
    sampleName: "sample_name",
    secondaryType: "secondary_type",
    serverId: "server_id",
    skuName: "sku_name",
    storageAccountType: "storage_account_type",
    tags: "tags",
    transparentDataEncryptionEnabled: "transparent_data_encryption_enabled",
    transparentDataEncryptionKeyAutomaticRotationEnabled: "transparent_data_encryption_key_automatic_rotation_enabled",
    transparentDataEncryptionKeyVaultKeyId: "transparent_data_encryption_key_vault_key_id",
    zoneRedundant: "zone_redundant",
    identity: {
      wireName: "identity",
      kind: "list",
      fields: Database_IdentityFields,
    },
    import: {
      wireName: "import",
      kind: "list",
      fields: Database_ImportFields,
    },
    longTermRetentionPolicy: {
      wireName: "long_term_retention_policy",
      kind: "list",
      fields: Database_LongTermRetentionPolicyFields,
    },
    shortTermRetentionPolicy: {
      wireName: "short_term_retention_policy",
      kind: "list",
      fields: Database_ShortTermRetentionPolicyFields,
    },
    threatDetectionPolicy: {
      wireName: "threat_detection_policy",
      kind: "list",
      fields: Database_ThreatDetectionPolicyFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Database_TimeoutsFields,
    },
  },
};
