// Code generated by `ubx sdk gen` from azurerm_mssql_job_credential. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface JobCredential_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const JobCredential_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface JobCredentialConfig {
  id?: string | Computed<string>;
  jobAgentId: string | Computed<string>;
  name: string | Computed<string>;
  password?: string | Computed<string>;
  passwordWo?: string | Computed<string>;
  passwordWoVersion?: number | Computed<number>;
  username: string | Computed<string>;
  timeouts?: JobCredential_Timeouts | Computed<JobCredential_Timeouts>;
}

export interface JobCredentialAttrs {
  id: string;
  jobAgentId: string;
  name: string;
  password: string;
  passwordWo: string;
  passwordWoVersion: number;
  username: string;
  timeouts: JobCredential_Timeouts;
}

export const JobCredential: ResourceBinding<JobCredentialConfig, JobCredentialAttrs> = {
  wireType: "azurerm_mssql_job_credential",
  fields: {
    id: "id",
    jobAgentId: "job_agent_id",
    name: "name",
    password: "password",
    passwordWo: "password_wo",
    passwordWoVersion: "password_wo_version",
    username: "username",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: JobCredential_TimeoutsFields,
    },
  },
};
