// Code generated by `ubx sdk gen` from azurerm_mssql_outbound_firewall_rule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface OutboundFirewallRule_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const OutboundFirewallRule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface OutboundFirewallRuleConfig {
  id?: string | Computed<string>;
  name: string | Computed<string>;
  serverId: string | Computed<string>;
  timeouts?: OutboundFirewallRule_Timeouts | Computed<OutboundFirewallRule_Timeouts>;
}

export interface OutboundFirewallRuleAttrs {
  id: string;
  name: string;
  serverId: string;
  timeouts: OutboundFirewallRule_Timeouts;
}

export const OutboundFirewallRule: ResourceBinding<OutboundFirewallRuleConfig, OutboundFirewallRuleAttrs> = {
  wireType: "azurerm_mssql_outbound_firewall_rule",
  fields: {
    id: "id",
    name: "name",
    serverId: "server_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: OutboundFirewallRule_TimeoutsFields,
    },
  },
};
