// Code generated by `ubx sdk gen` from azurerm_mssql_server_microsoft_support_auditing_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ServerMicrosoftSupportAuditingPolicy_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ServerMicrosoftSupportAuditingPolicy_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ServerMicrosoftSupportAuditingPolicyConfig {
  blobStorageEndpoint?: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  logMonitoringEnabled?: boolean | Computed<boolean>;
  serverId: string | Computed<string>;
  storageAccountAccessKey?: string | Computed<string>;
  storageAccountSubscriptionId?: string | Computed<string>;
  timeouts?: ServerMicrosoftSupportAuditingPolicy_Timeouts | Computed<ServerMicrosoftSupportAuditingPolicy_Timeouts>;
}

export interface ServerMicrosoftSupportAuditingPolicyAttrs {
  blobStorageEndpoint: string;
  enabled: boolean;
  id: string;
  logMonitoringEnabled: boolean;
  serverId: string;
  storageAccountAccessKey: string;
  storageAccountSubscriptionId: string;
  timeouts: ServerMicrosoftSupportAuditingPolicy_Timeouts;
}

export const ServerMicrosoftSupportAuditingPolicy: ResourceBinding<ServerMicrosoftSupportAuditingPolicyConfig, ServerMicrosoftSupportAuditingPolicyAttrs> = {
  wireType: "azurerm_mssql_server_microsoft_support_auditing_policy",
  fields: {
    blobStorageEndpoint: "blob_storage_endpoint",
    enabled: "enabled",
    id: "id",
    logMonitoringEnabled: "log_monitoring_enabled",
    serverId: "server_id",
    storageAccountAccessKey: "storage_account_access_key",
    storageAccountSubscriptionId: "storage_account_subscription_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ServerMicrosoftSupportAuditingPolicy_TimeoutsFields,
    },
  },
};
