// Code generated by `ubx sdk gen` from azurerm_vpn_server_configuration. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ServerConfiguration_AzureActiveDirectoryAuthentication {
  audience: string;
  issuer: string;
  tenant: string;
}

export interface ServerConfiguration_ClientRevokedCertificate {
  name: string;
  thumbprint: string;
}

export interface ServerConfiguration_ClientRootCertificate {
  name: string;
  publicCertData: string;
}

export interface ServerConfiguration_IpsecPolicy {
  dhGroup: string;
  ikeEncryption: string;
  ikeIntegrity: string;
  ipsecEncryption: string;
  ipsecIntegrity: string;
  pfsGroup: string;
  saDataSizeKilobytes: number;
  saLifetimeSeconds: number;
}

export interface ServerConfiguration_Radius_Server {
  address: string;
  score: number;
  secret: string;
}

export interface ServerConfiguration_Radius {
  clientRootCertificate: ServerConfiguration_ClientRevokedCertificate[];
  server: ServerConfiguration_Radius_Server[];
  serverRootCertificate: ServerConfiguration_ClientRootCertificate[];
}

export interface ServerConfiguration_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const ServerConfiguration_AzureActiveDirectoryAuthenticationFields: FieldMap = {
  audience: "audience",
  issuer: "issuer",
  tenant: "tenant",
};

const ServerConfiguration_ClientRevokedCertificateFields: FieldMap = {
  name: "name",
  thumbprint: "thumbprint",
};

const ServerConfiguration_ClientRootCertificateFields: FieldMap = {
  name: "name",
  publicCertData: "public_cert_data",
};

const ServerConfiguration_IpsecPolicyFields: FieldMap = {
  dhGroup: "dh_group",
  ikeEncryption: "ike_encryption",
  ikeIntegrity: "ike_integrity",
  ipsecEncryption: "ipsec_encryption",
  ipsecIntegrity: "ipsec_integrity",
  pfsGroup: "pfs_group",
  saDataSizeKilobytes: "sa_data_size_kilobytes",
  saLifetimeSeconds: "sa_lifetime_seconds",
};

const ServerConfiguration_Radius_ServerFields: FieldMap = {
  address: "address",
  score: "score",
  secret: "secret",
};

const ServerConfiguration_RadiusFields: FieldMap = {
  clientRootCertificate: {
    wireName: "client_root_certificate",
    kind: "set",
    fields: ServerConfiguration_ClientRevokedCertificateFields,
  },
  server: {
    wireName: "server",
    kind: "list",
    fields: ServerConfiguration_Radius_ServerFields,
  },
  serverRootCertificate: {
    wireName: "server_root_certificate",
    kind: "set",
    fields: ServerConfiguration_ClientRootCertificateFields,
  },
};

const ServerConfiguration_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface ServerConfigurationConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  vpnAuthenticationTypes: string[] | Computed<string[]>;
  vpnProtocols?: string[] | Computed<string[]>;
  azureActiveDirectoryAuthentication?: ServerConfiguration_AzureActiveDirectoryAuthentication[] | Computed<ServerConfiguration_AzureActiveDirectoryAuthentication[]>;
  clientRevokedCertificate?: ServerConfiguration_ClientRevokedCertificate[] | Computed<ServerConfiguration_ClientRevokedCertificate[]>;
  clientRootCertificate?: ServerConfiguration_ClientRootCertificate[] | Computed<ServerConfiguration_ClientRootCertificate[]>;
  ipsecPolicy?: ServerConfiguration_IpsecPolicy[] | Computed<ServerConfiguration_IpsecPolicy[]>;
  radius?: ServerConfiguration_Radius[] | Computed<ServerConfiguration_Radius[]>;
  timeouts?: ServerConfiguration_Timeouts | Computed<ServerConfiguration_Timeouts>;
}

export interface ServerConfigurationAttrs {
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  vpnAuthenticationTypes: string[];
  vpnProtocols: string[];
  azureActiveDirectoryAuthentication: ServerConfiguration_AzureActiveDirectoryAuthentication[];
  clientRevokedCertificate: ServerConfiguration_ClientRevokedCertificate[];
  clientRootCertificate: ServerConfiguration_ClientRootCertificate[];
  ipsecPolicy: ServerConfiguration_IpsecPolicy[];
  radius: ServerConfiguration_Radius[];
  timeouts: ServerConfiguration_Timeouts;
}

export const ServerConfiguration: ResourceBinding<ServerConfigurationConfig, ServerConfigurationAttrs> = {
  wireType: "azurerm_vpn_server_configuration",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    vpnAuthenticationTypes: "vpn_authentication_types",
    vpnProtocols: "vpn_protocols",
    azureActiveDirectoryAuthentication: {
      wireName: "azure_active_directory_authentication",
      kind: "list",
      fields: ServerConfiguration_AzureActiveDirectoryAuthenticationFields,
    },
    clientRevokedCertificate: {
      wireName: "client_revoked_certificate",
      kind: "set",
      fields: ServerConfiguration_ClientRevokedCertificateFields,
    },
    clientRootCertificate: {
      wireName: "client_root_certificate",
      kind: "set",
      fields: ServerConfiguration_ClientRootCertificateFields,
    },
    ipsecPolicy: {
      wireName: "ipsec_policy",
      kind: "list",
      fields: ServerConfiguration_IpsecPolicyFields,
    },
    radius: {
      wireName: "radius",
      kind: "list",
      fields: ServerConfiguration_RadiusFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ServerConfiguration_TimeoutsFields,
    },
  },
};
