// Code generated by `ubx sdk gen` from azurerm_vpn_site. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Site_Link_Bgp {
  asn: number;
  peeringAddress: string;
}

export interface Site_Link {
  fqdn: string;
  id: string;
  ipAddress: string;
  name: string;
  providerName: string;
  speedInMbps: number;
  bgp: Site_Link_Bgp[];
}

export interface Site_O365Policy_TrafficCategory {
  allowEndpointEnabled: boolean;
  defaultEndpointEnabled: boolean;
  optimizeEndpointEnabled: boolean;
}

export interface Site_O365Policy {
  trafficCategory: Site_O365Policy_TrafficCategory[];
}

export interface Site_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Site_Link_BgpFields: FieldMap = {
  asn: "asn",
  peeringAddress: "peering_address",
};

const Site_LinkFields: FieldMap = {
  fqdn: "fqdn",
  id: "id",
  ipAddress: "ip_address",
  name: "name",
  providerName: "provider_name",
  speedInMbps: "speed_in_mbps",
  bgp: {
    wireName: "bgp",
    kind: "list",
    fields: Site_Link_BgpFields,
  },
};

const Site_O365Policy_TrafficCategoryFields: FieldMap = {
  allowEndpointEnabled: "allow_endpoint_enabled",
  defaultEndpointEnabled: "default_endpoint_enabled",
  optimizeEndpointEnabled: "optimize_endpoint_enabled",
};

const Site_O365PolicyFields: FieldMap = {
  trafficCategory: {
    wireName: "traffic_category",
    kind: "list",
    fields: Site_O365Policy_TrafficCategoryFields,
  },
};

const Site_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface SiteConfig {
  addressCidrs?: string[] | Computed<string[]>;
  deviceModel?: string | Computed<string>;
  deviceVendor?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  virtualWanId: string | Computed<string>;
  link?: Site_Link[] | Computed<Site_Link[]>;
  o365Policy?: Site_O365Policy[] | Computed<Site_O365Policy[]>;
  timeouts?: Site_Timeouts | Computed<Site_Timeouts>;
}

export interface SiteAttrs {
  addressCidrs: string[];
  deviceModel: string;
  deviceVendor: string;
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  virtualWanId: string;
  link: Site_Link[];
  o365Policy: Site_O365Policy[];
  timeouts: Site_Timeouts;
}

export const Site: ResourceBinding<SiteConfig, SiteAttrs> = {
  wireType: "azurerm_vpn_site",
  fields: {
    addressCidrs: "address_cidrs",
    deviceModel: "device_model",
    deviceVendor: "device_vendor",
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    virtualWanId: "virtual_wan_id",
    link: {
      wireName: "link",
      kind: "list",
      fields: Site_LinkFields,
    },
    o365Policy: {
      wireName: "o365_policy",
      kind: "list",
      fields: Site_O365PolicyFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Site_TimeoutsFields,
    },
  },
};
