// Code generated by `ubx sdk gen` from azurerm_kubernetes_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Cluster_KubeAdminConfig {
  clientCertificate: string;
  clientKey: string;
  clusterCaCertificate: string;
  host: string;
  password: string;
  username: string;
}

export interface Cluster_AciConnectorLinux_ConnectorIdentity {
  clientId: string;
  objectId: string;
  userAssignedIdentityId: string;
}

export interface Cluster_AciConnectorLinux {
  connectorIdentity: Cluster_AciConnectorLinux_ConnectorIdentity[];
  subnetName: string;
}

export interface Cluster_ApiServerAccessProfile {
  authorizedIpRanges: string[];
  subnetId: string;
  virtualNetworkIntegrationEnabled: boolean;
}

export interface Cluster_AutoScalerProfile {
  balanceSimilarNodeGroups: boolean;
  daemonsetEvictionForEmptyNodesEnabled: boolean;
  daemonsetEvictionForOccupiedNodesEnabled: boolean;
  emptyBulkDeleteMax: string;
  expander: string;
  ignoreDaemonsetsUtilizationEnabled: boolean;
  maxGracefulTerminationSec: string;
  maxNodeProvisioningTime: string;
  maxUnreadyNodes: number;
  maxUnreadyPercentage: number;
  newPodScaleUpDelay: string;
  scaleDownDelayAfterAdd: string;
  scaleDownDelayAfterDelete: string;
  scaleDownDelayAfterFailure: string;
  scaleDownUnneeded: string;
  scaleDownUnready: string;
  scaleDownUtilizationThreshold: string;
  scanInterval: string;
  skipNodesWithLocalStorage: boolean;
  skipNodesWithSystemPods: boolean;
}

export interface Cluster_AzureActiveDirectoryRoleBasedAccessControl {
  adminGroupObjectIds: string[];
  azureRbacEnabled: boolean;
  tenantId: string;
}

export interface Cluster_BootstrapProfile {
  artifactSource: string;
  containerRegistryId: string;
}

export interface Cluster_ConfidentialComputing {
  sgxQuoteHelperEnabled: boolean;
}

export interface Cluster_DefaultNodePool_KubeletConfig {
  allowedUnsafeSysctls: string[];
  containerLogMaxFiles: number;
  containerLogMaxSizeMb: number;
  cpuCfsQuotaEnabled: boolean;
  cpuCfsQuotaPeriod: string;
  cpuManagerPolicy: string;
  imageGcHighThreshold: number;
  imageGcLowThreshold: number;
  podMaxPid: number;
  topologyManagerPolicy: string;
}

export interface Cluster_DefaultNodePool_LinuxOsConfig_SysctlConfig {
  fsAioMaxNr: number;
  fsFileMax: number;
  fsInotifyMaxUserWatches: number;
  fsNrOpen: number;
  kernelThreadsMax: number;
  netCoreNetdevMaxBacklog: number;
  netCoreOptmemMax: number;
  netCoreRmemDefault: number;
  netCoreRmemMax: number;
  netCoreSomaxconn: number;
  netCoreWmemDefault: number;
  netCoreWmemMax: number;
  netIpv4IpLocalPortRangeMax: number;
  netIpv4IpLocalPortRangeMin: number;
  netIpv4NeighDefaultGcThresh1: number;
  netIpv4NeighDefaultGcThresh2: number;
  netIpv4NeighDefaultGcThresh3: number;
  netIpv4TcpFinTimeout: number;
  netIpv4TcpKeepaliveIntvl: number;
  netIpv4TcpKeepaliveProbes: number;
  netIpv4TcpKeepaliveTime: number;
  netIpv4TcpMaxSynBacklog: number;
  netIpv4TcpMaxTwBuckets: number;
  netIpv4TcpTwReuse: boolean;
  netNetfilterNfConntrackBuckets: number;
  netNetfilterNfConntrackMax: number;
  vmMaxMapCount: number;
  vmSwappiness: number;
  vmVfsCachePressure: number;
}

export interface Cluster_DefaultNodePool_LinuxOsConfig {
  swapFileSizeMb: number;
  transparentHugePage: string;
  transparentHugePageDefrag: string;
  sysctlConfig: Cluster_DefaultNodePool_LinuxOsConfig_SysctlConfig[];
}

export interface Cluster_DefaultNodePool_NodeNetworkProfile_AllowedHostPorts {
  portEnd: number;
  portStart: number;
  protocol: string;
}

export interface Cluster_DefaultNodePool_NodeNetworkProfile {
  applicationSecurityGroupIds: string[];
  nodePublicIpTags: Record<string, string>;
  allowedHostPorts: Cluster_DefaultNodePool_NodeNetworkProfile_AllowedHostPorts[];
}

export interface Cluster_DefaultNodePool_UpgradeSettings {
  drainTimeoutInMinutes: number;
  maxSurge: string;
  nodeSoakDurationInMinutes: number;
  undrainableNodeBehavior: string;
}

export interface Cluster_DefaultNodePool {
  autoScalingEnabled: boolean;
  capacityReservationGroupId: string;
  fipsEnabled: boolean;
  gpuDriver: string;
  gpuInstance: string;
  hostEncryptionEnabled: boolean;
  hostGroupId: string;
  kubeletDiskType: string;
  maxCount: number;
  maxPods: number;
  minCount: number;
  name: string;
  nodeCount: number;
  nodeLabels: Record<string, string>;
  nodePublicIpEnabled: boolean;
  nodePublicIpPrefixId: string;
  onlyCriticalAddonsEnabled: boolean;
  orchestratorVersion: string;
  osDiskSizeGb: number;
  osDiskType: string;
  osSku: string;
  podSubnetId: string;
  proximityPlacementGroupId: string;
  scaleDownMode: string;
  snapshotId: string;
  tags: Record<string, string>;
  temporaryNameForRotation: string;
  type: string;
  ultraSsdEnabled: boolean;
  vmSize: string;
  vnetSubnetId: string;
  workloadRuntime: string;
  zones: string[];
  kubeletConfig: Cluster_DefaultNodePool_KubeletConfig[];
  linuxOsConfig: Cluster_DefaultNodePool_LinuxOsConfig[];
  nodeNetworkProfile: Cluster_DefaultNodePool_NodeNetworkProfile[];
  upgradeSettings: Cluster_DefaultNodePool_UpgradeSettings[];
}

export interface Cluster_HttpProxyConfig {
  httpProxy: string;
  httpsProxy: string;
  noProxy: string[];
  trustedCa: string;
}

export interface Cluster_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface Cluster_IngressApplicationGateway {
  effectiveGatewayId: string;
  gatewayId: string;
  gatewayName: string;
  ingressApplicationGatewayIdentity: Cluster_AciConnectorLinux_ConnectorIdentity[];
  subnetCidr: string;
  subnetId: string;
}

export interface Cluster_KeyManagementService {
  keyVaultKeyId: string;
  keyVaultNetworkAccess: string;
}

export interface Cluster_KeyVaultSecretsProvider {
  secretIdentity: Cluster_AciConnectorLinux_ConnectorIdentity[];
  secretRotationEnabled: boolean;
  secretRotationInterval: string;
}

export interface Cluster_LinuxProfile_SshKey {
  keyData: string;
}

export interface Cluster_LinuxProfile {
  adminUsername: string;
  sshKey: Cluster_LinuxProfile_SshKey[];
}

export interface Cluster_MaintenanceWindow_Allowed {
  day: string;
  hours: number[];
}

export interface Cluster_MaintenanceWindow_NotAllowed {
  end: string;
  start: string;
}

export interface Cluster_MaintenanceWindow {
  allowed: Cluster_MaintenanceWindow_Allowed[];
  notAllowed: Cluster_MaintenanceWindow_NotAllowed[];
}

export interface Cluster_MaintenanceWindowAutoUpgrade {
  dayOfMonth: number;
  dayOfWeek: string;
  duration: number;
  frequency: string;
  interval: number;
  startDate: string;
  startTime: string;
  utcOffset: string;
  weekIndex: string;
  notAllowed: Cluster_MaintenanceWindow_NotAllowed[];
}

export interface Cluster_MicrosoftDefender {
  logAnalyticsWorkspaceId: string;
}

export interface Cluster_MonitorMetrics {
  annotationsAllowed: string;
  labelsAllowed: string;
}

export interface Cluster_NetworkProfile_AdvancedNetworking {
  observabilityEnabled: boolean;
  securityEnabled: boolean;
}

export interface Cluster_NetworkProfile_LoadBalancerProfile {
  backendPoolType: string;
  effectiveOutboundIps: string[];
  idleTimeoutInMinutes: number;
  managedOutboundIpCount: number;
  managedOutboundIpv6Count: number;
  outboundIpAddressIds: string[];
  outboundIpPrefixIds: string[];
  outboundPortsAllocated: number;
}

export interface Cluster_NetworkProfile_NatGatewayProfile {
  effectiveOutboundIps: string[];
  idleTimeoutInMinutes: number;
  managedOutboundIpCount: number;
}

export interface Cluster_NetworkProfile {
  dnsServiceIp: string;
  ipVersions: string[];
  loadBalancerSku: string;
  networkDataPlane: string;
  networkMode: string;
  networkPlugin: string;
  networkPluginMode: string;
  networkPolicy: string;
  outboundType: string;
  podCidr: string;
  podCidrs: string[];
  serviceCidr: string;
  serviceCidrs: string[];
  advancedNetworking: Cluster_NetworkProfile_AdvancedNetworking[];
  loadBalancerProfile: Cluster_NetworkProfile_LoadBalancerProfile[];
  natGatewayProfile: Cluster_NetworkProfile_NatGatewayProfile[];
}

export interface Cluster_NodeProvisioningProfile {
  defaultNodePools: string;
  mode: string;
}

export interface Cluster_OmsAgent {
  logAnalyticsWorkspaceId: string;
  msiAuthForMonitoringEnabled: boolean;
  omsAgentIdentity: Cluster_AciConnectorLinux_ConnectorIdentity[];
}

export interface Cluster_ServiceMeshProfile_CertificateAuthority {
  certChainObjectName: string;
  certObjectName: string;
  keyObjectName: string;
  keyVaultId: string;
  rootCertObjectName: string;
}

export interface Cluster_ServiceMeshProfile {
  externalIngressGatewayEnabled: boolean;
  internalIngressGatewayEnabled: boolean;
  mode: string;
  revisions: string[];
  certificateAuthority: Cluster_ServiceMeshProfile_CertificateAuthority[];
}

export interface Cluster_ServicePrincipal {
  clientId: string;
  clientSecret: string;
}

export interface Cluster_StorageProfile {
  blobDriverEnabled: boolean;
  diskDriverEnabled: boolean;
  fileDriverEnabled: boolean;
  snapshotControllerEnabled: boolean;
}

export interface Cluster_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

export interface Cluster_UpgradeOverride {
  effectiveUntil: string;
  forceUpgradeEnabled: boolean;
}

export interface Cluster_WebAppRouting {
  defaultNginxController: string;
  dnsZoneIds: string[];
  webAppRoutingIdentity: Cluster_AciConnectorLinux_ConnectorIdentity[];
}

export interface Cluster_WindowsProfile_Gmsa {
  dnsServer: string;
  rootDomain: string;
}

export interface Cluster_WindowsProfile {
  adminPassword: string;
  adminUsername: string;
  license: string;
  gmsa: Cluster_WindowsProfile_Gmsa[];
}

export interface Cluster_WorkloadAutoscalerProfile {
  kedaEnabled: boolean;
  verticalPodAutoscalerEnabled: boolean;
}

const Cluster_AciConnectorLinux_ConnectorIdentityFields: FieldMap = {
  clientId: "client_id",
  objectId: "object_id",
  userAssignedIdentityId: "user_assigned_identity_id",
};

const Cluster_AciConnectorLinuxFields: FieldMap = {
  connectorIdentity: {
    wireName: "connector_identity",
    kind: "list",
    fields: Cluster_AciConnectorLinux_ConnectorIdentityFields,
  },
  subnetName: "subnet_name",
};

const Cluster_ApiServerAccessProfileFields: FieldMap = {
  authorizedIpRanges: "authorized_ip_ranges",
  subnetId: "subnet_id",
  virtualNetworkIntegrationEnabled: "virtual_network_integration_enabled",
};

const Cluster_AutoScalerProfileFields: FieldMap = {
  balanceSimilarNodeGroups: "balance_similar_node_groups",
  daemonsetEvictionForEmptyNodesEnabled: "daemonset_eviction_for_empty_nodes_enabled",
  daemonsetEvictionForOccupiedNodesEnabled: "daemonset_eviction_for_occupied_nodes_enabled",
  emptyBulkDeleteMax: "empty_bulk_delete_max",
  expander: "expander",
  ignoreDaemonsetsUtilizationEnabled: "ignore_daemonsets_utilization_enabled",
  maxGracefulTerminationSec: "max_graceful_termination_sec",
  maxNodeProvisioningTime: "max_node_provisioning_time",
  maxUnreadyNodes: "max_unready_nodes",
  maxUnreadyPercentage: "max_unready_percentage",
  newPodScaleUpDelay: "new_pod_scale_up_delay",
  scaleDownDelayAfterAdd: "scale_down_delay_after_add",
  scaleDownDelayAfterDelete: "scale_down_delay_after_delete",
  scaleDownDelayAfterFailure: "scale_down_delay_after_failure",
  scaleDownUnneeded: "scale_down_unneeded",
  scaleDownUnready: "scale_down_unready",
  scaleDownUtilizationThreshold: "scale_down_utilization_threshold",
  scanInterval: "scan_interval",
  skipNodesWithLocalStorage: "skip_nodes_with_local_storage",
  skipNodesWithSystemPods: "skip_nodes_with_system_pods",
};

const Cluster_AzureActiveDirectoryRoleBasedAccessControlFields: FieldMap = {
  adminGroupObjectIds: "admin_group_object_ids",
  azureRbacEnabled: "azure_rbac_enabled",
  tenantId: "tenant_id",
};

const Cluster_BootstrapProfileFields: FieldMap = {
  artifactSource: "artifact_source",
  containerRegistryId: "container_registry_id",
};

const Cluster_ConfidentialComputingFields: FieldMap = {
  sgxQuoteHelperEnabled: "sgx_quote_helper_enabled",
};

const Cluster_DefaultNodePool_KubeletConfigFields: FieldMap = {
  allowedUnsafeSysctls: "allowed_unsafe_sysctls",
  containerLogMaxFiles: "container_log_max_files",
  containerLogMaxSizeMb: "container_log_max_size_mb",
  cpuCfsQuotaEnabled: "cpu_cfs_quota_enabled",
  cpuCfsQuotaPeriod: "cpu_cfs_quota_period",
  cpuManagerPolicy: "cpu_manager_policy",
  imageGcHighThreshold: "image_gc_high_threshold",
  imageGcLowThreshold: "image_gc_low_threshold",
  podMaxPid: "pod_max_pid",
  topologyManagerPolicy: "topology_manager_policy",
};

const Cluster_DefaultNodePool_LinuxOsConfig_SysctlConfigFields: FieldMap = {
  fsAioMaxNr: "fs_aio_max_nr",
  fsFileMax: "fs_file_max",
  fsInotifyMaxUserWatches: "fs_inotify_max_user_watches",
  fsNrOpen: "fs_nr_open",
  kernelThreadsMax: "kernel_threads_max",
  netCoreNetdevMaxBacklog: "net_core_netdev_max_backlog",
  netCoreOptmemMax: "net_core_optmem_max",
  netCoreRmemDefault: "net_core_rmem_default",
  netCoreRmemMax: "net_core_rmem_max",
  netCoreSomaxconn: "net_core_somaxconn",
  netCoreWmemDefault: "net_core_wmem_default",
  netCoreWmemMax: "net_core_wmem_max",
  netIpv4IpLocalPortRangeMax: "net_ipv4_ip_local_port_range_max",
  netIpv4IpLocalPortRangeMin: "net_ipv4_ip_local_port_range_min",
  netIpv4NeighDefaultGcThresh1: "net_ipv4_neigh_default_gc_thresh1",
  netIpv4NeighDefaultGcThresh2: "net_ipv4_neigh_default_gc_thresh2",
  netIpv4NeighDefaultGcThresh3: "net_ipv4_neigh_default_gc_thresh3",
  netIpv4TcpFinTimeout: "net_ipv4_tcp_fin_timeout",
  netIpv4TcpKeepaliveIntvl: "net_ipv4_tcp_keepalive_intvl",
  netIpv4TcpKeepaliveProbes: "net_ipv4_tcp_keepalive_probes",
  netIpv4TcpKeepaliveTime: "net_ipv4_tcp_keepalive_time",
  netIpv4TcpMaxSynBacklog: "net_ipv4_tcp_max_syn_backlog",
  netIpv4TcpMaxTwBuckets: "net_ipv4_tcp_max_tw_buckets",
  netIpv4TcpTwReuse: "net_ipv4_tcp_tw_reuse",
  netNetfilterNfConntrackBuckets: "net_netfilter_nf_conntrack_buckets",
  netNetfilterNfConntrackMax: "net_netfilter_nf_conntrack_max",
  vmMaxMapCount: "vm_max_map_count",
  vmSwappiness: "vm_swappiness",
  vmVfsCachePressure: "vm_vfs_cache_pressure",
};

const Cluster_DefaultNodePool_LinuxOsConfigFields: FieldMap = {
  swapFileSizeMb: "swap_file_size_mb",
  transparentHugePage: "transparent_huge_page",
  transparentHugePageDefrag: "transparent_huge_page_defrag",
  sysctlConfig: {
    wireName: "sysctl_config",
    kind: "list",
    fields: Cluster_DefaultNodePool_LinuxOsConfig_SysctlConfigFields,
  },
};

const Cluster_DefaultNodePool_NodeNetworkProfile_AllowedHostPortsFields: FieldMap = {
  portEnd: "port_end",
  portStart: "port_start",
  protocol: "protocol",
};

const Cluster_DefaultNodePool_NodeNetworkProfileFields: FieldMap = {
  applicationSecurityGroupIds: "application_security_group_ids",
  nodePublicIpTags: "node_public_ip_tags",
  allowedHostPorts: {
    wireName: "allowed_host_ports",
    kind: "list",
    fields: Cluster_DefaultNodePool_NodeNetworkProfile_AllowedHostPortsFields,
  },
};

const Cluster_DefaultNodePool_UpgradeSettingsFields: FieldMap = {
  drainTimeoutInMinutes: "drain_timeout_in_minutes",
  maxSurge: "max_surge",
  nodeSoakDurationInMinutes: "node_soak_duration_in_minutes",
  undrainableNodeBehavior: "undrainable_node_behavior",
};

const Cluster_DefaultNodePoolFields: FieldMap = {
  autoScalingEnabled: "auto_scaling_enabled",
  capacityReservationGroupId: "capacity_reservation_group_id",
  fipsEnabled: "fips_enabled",
  gpuDriver: "gpu_driver",
  gpuInstance: "gpu_instance",
  hostEncryptionEnabled: "host_encryption_enabled",
  hostGroupId: "host_group_id",
  kubeletDiskType: "kubelet_disk_type",
  maxCount: "max_count",
  maxPods: "max_pods",
  minCount: "min_count",
  name: "name",
  nodeCount: "node_count",
  nodeLabels: "node_labels",
  nodePublicIpEnabled: "node_public_ip_enabled",
  nodePublicIpPrefixId: "node_public_ip_prefix_id",
  onlyCriticalAddonsEnabled: "only_critical_addons_enabled",
  orchestratorVersion: "orchestrator_version",
  osDiskSizeGb: "os_disk_size_gb",
  osDiskType: "os_disk_type",
  osSku: "os_sku",
  podSubnetId: "pod_subnet_id",
  proximityPlacementGroupId: "proximity_placement_group_id",
  scaleDownMode: "scale_down_mode",
  snapshotId: "snapshot_id",
  tags: "tags",
  temporaryNameForRotation: "temporary_name_for_rotation",
  type: "type",
  ultraSsdEnabled: "ultra_ssd_enabled",
  vmSize: "vm_size",
  vnetSubnetId: "vnet_subnet_id",
  workloadRuntime: "workload_runtime",
  zones: "zones",
  kubeletConfig: {
    wireName: "kubelet_config",
    kind: "list",
    fields: Cluster_DefaultNodePool_KubeletConfigFields,
  },
  linuxOsConfig: {
    wireName: "linux_os_config",
    kind: "list",
    fields: Cluster_DefaultNodePool_LinuxOsConfigFields,
  },
  nodeNetworkProfile: {
    wireName: "node_network_profile",
    kind: "list",
    fields: Cluster_DefaultNodePool_NodeNetworkProfileFields,
  },
  upgradeSettings: {
    wireName: "upgrade_settings",
    kind: "list",
    fields: Cluster_DefaultNodePool_UpgradeSettingsFields,
  },
};

const Cluster_HttpProxyConfigFields: FieldMap = {
  httpProxy: "http_proxy",
  httpsProxy: "https_proxy",
  noProxy: "no_proxy",
  trustedCa: "trusted_ca",
};

const Cluster_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const Cluster_IngressApplicationGatewayFields: FieldMap = {
  effectiveGatewayId: "effective_gateway_id",
  gatewayId: "gateway_id",
  gatewayName: "gateway_name",
  ingressApplicationGatewayIdentity: {
    wireName: "ingress_application_gateway_identity",
    kind: "list",
    fields: Cluster_AciConnectorLinux_ConnectorIdentityFields,
  },
  subnetCidr: "subnet_cidr",
  subnetId: "subnet_id",
};

const Cluster_KeyManagementServiceFields: FieldMap = {
  keyVaultKeyId: "key_vault_key_id",
  keyVaultNetworkAccess: "key_vault_network_access",
};

const Cluster_KeyVaultSecretsProviderFields: FieldMap = {
  secretIdentity: {
    wireName: "secret_identity",
    kind: "list",
    fields: Cluster_AciConnectorLinux_ConnectorIdentityFields,
  },
  secretRotationEnabled: "secret_rotation_enabled",
  secretRotationInterval: "secret_rotation_interval",
};

const Cluster_LinuxProfile_SshKeyFields: FieldMap = {
  keyData: "key_data",
};

const Cluster_LinuxProfileFields: FieldMap = {
  adminUsername: "admin_username",
  sshKey: {
    wireName: "ssh_key",
    kind: "list",
    fields: Cluster_LinuxProfile_SshKeyFields,
  },
};

const Cluster_MaintenanceWindow_AllowedFields: FieldMap = {
  day: "day",
  hours: "hours",
};

const Cluster_MaintenanceWindow_NotAllowedFields: FieldMap = {
  end: "end",
  start: "start",
};

const Cluster_MaintenanceWindowFields: FieldMap = {
  allowed: {
    wireName: "allowed",
    kind: "set",
    fields: Cluster_MaintenanceWindow_AllowedFields,
  },
  notAllowed: {
    wireName: "not_allowed",
    kind: "set",
    fields: Cluster_MaintenanceWindow_NotAllowedFields,
  },
};

const Cluster_MaintenanceWindowAutoUpgradeFields: FieldMap = {
  dayOfMonth: "day_of_month",
  dayOfWeek: "day_of_week",
  duration: "duration",
  frequency: "frequency",
  interval: "interval",
  startDate: "start_date",
  startTime: "start_time",
  utcOffset: "utc_offset",
  weekIndex: "week_index",
  notAllowed: {
    wireName: "not_allowed",
    kind: "set",
    fields: Cluster_MaintenanceWindow_NotAllowedFields,
  },
};

const Cluster_MicrosoftDefenderFields: FieldMap = {
  logAnalyticsWorkspaceId: "log_analytics_workspace_id",
};

const Cluster_MonitorMetricsFields: FieldMap = {
  annotationsAllowed: "annotations_allowed",
  labelsAllowed: "labels_allowed",
};

const Cluster_NetworkProfile_AdvancedNetworkingFields: FieldMap = {
  observabilityEnabled: "observability_enabled",
  securityEnabled: "security_enabled",
};

const Cluster_NetworkProfile_LoadBalancerProfileFields: FieldMap = {
  backendPoolType: "backend_pool_type",
  effectiveOutboundIps: "effective_outbound_ips",
  idleTimeoutInMinutes: "idle_timeout_in_minutes",
  managedOutboundIpCount: "managed_outbound_ip_count",
  managedOutboundIpv6Count: "managed_outbound_ipv6_count",
  outboundIpAddressIds: "outbound_ip_address_ids",
  outboundIpPrefixIds: "outbound_ip_prefix_ids",
  outboundPortsAllocated: "outbound_ports_allocated",
};

const Cluster_NetworkProfile_NatGatewayProfileFields: FieldMap = {
  effectiveOutboundIps: "effective_outbound_ips",
  idleTimeoutInMinutes: "idle_timeout_in_minutes",
  managedOutboundIpCount: "managed_outbound_ip_count",
};

const Cluster_NetworkProfileFields: FieldMap = {
  dnsServiceIp: "dns_service_ip",
  ipVersions: "ip_versions",
  loadBalancerSku: "load_balancer_sku",
  networkDataPlane: "network_data_plane",
  networkMode: "network_mode",
  networkPlugin: "network_plugin",
  networkPluginMode: "network_plugin_mode",
  networkPolicy: "network_policy",
  outboundType: "outbound_type",
  podCidr: "pod_cidr",
  podCidrs: "pod_cidrs",
  serviceCidr: "service_cidr",
  serviceCidrs: "service_cidrs",
  advancedNetworking: {
    wireName: "advanced_networking",
    kind: "list",
    fields: Cluster_NetworkProfile_AdvancedNetworkingFields,
  },
  loadBalancerProfile: {
    wireName: "load_balancer_profile",
    kind: "list",
    fields: Cluster_NetworkProfile_LoadBalancerProfileFields,
  },
  natGatewayProfile: {
    wireName: "nat_gateway_profile",
    kind: "list",
    fields: Cluster_NetworkProfile_NatGatewayProfileFields,
  },
};

const Cluster_NodeProvisioningProfileFields: FieldMap = {
  defaultNodePools: "default_node_pools",
  mode: "mode",
};

const Cluster_OmsAgentFields: FieldMap = {
  logAnalyticsWorkspaceId: "log_analytics_workspace_id",
  msiAuthForMonitoringEnabled: "msi_auth_for_monitoring_enabled",
  omsAgentIdentity: {
    wireName: "oms_agent_identity",
    kind: "list",
    fields: Cluster_AciConnectorLinux_ConnectorIdentityFields,
  },
};

const Cluster_ServiceMeshProfile_CertificateAuthorityFields: FieldMap = {
  certChainObjectName: "cert_chain_object_name",
  certObjectName: "cert_object_name",
  keyObjectName: "key_object_name",
  keyVaultId: "key_vault_id",
  rootCertObjectName: "root_cert_object_name",
};

const Cluster_ServiceMeshProfileFields: FieldMap = {
  externalIngressGatewayEnabled: "external_ingress_gateway_enabled",
  internalIngressGatewayEnabled: "internal_ingress_gateway_enabled",
  mode: "mode",
  revisions: "revisions",
  certificateAuthority: {
    wireName: "certificate_authority",
    kind: "list",
    fields: Cluster_ServiceMeshProfile_CertificateAuthorityFields,
  },
};

const Cluster_ServicePrincipalFields: FieldMap = {
  clientId: "client_id",
  clientSecret: "client_secret",
};

const Cluster_StorageProfileFields: FieldMap = {
  blobDriverEnabled: "blob_driver_enabled",
  diskDriverEnabled: "disk_driver_enabled",
  fileDriverEnabled: "file_driver_enabled",
  snapshotControllerEnabled: "snapshot_controller_enabled",
};

const Cluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

const Cluster_UpgradeOverrideFields: FieldMap = {
  effectiveUntil: "effective_until",
  forceUpgradeEnabled: "force_upgrade_enabled",
};

const Cluster_WebAppRoutingFields: FieldMap = {
  defaultNginxController: "default_nginx_controller",
  dnsZoneIds: "dns_zone_ids",
  webAppRoutingIdentity: {
    wireName: "web_app_routing_identity",
    kind: "list",
    fields: Cluster_AciConnectorLinux_ConnectorIdentityFields,
  },
};

const Cluster_WindowsProfile_GmsaFields: FieldMap = {
  dnsServer: "dns_server",
  rootDomain: "root_domain",
};

const Cluster_WindowsProfileFields: FieldMap = {
  adminPassword: "admin_password",
  adminUsername: "admin_username",
  license: "license",
  gmsa: {
    wireName: "gmsa",
    kind: "list",
    fields: Cluster_WindowsProfile_GmsaFields,
  },
};

const Cluster_WorkloadAutoscalerProfileFields: FieldMap = {
  kedaEnabled: "keda_enabled",
  verticalPodAutoscalerEnabled: "vertical_pod_autoscaler_enabled",
};

export interface ClusterConfig {
  aiToolchainOperatorEnabled?: boolean | Computed<boolean>;
  automaticUpgradeChannel?: string | Computed<string>;
  azurePolicyEnabled?: boolean | Computed<boolean>;
  costAnalysisEnabled?: boolean | Computed<boolean>;
  customCaTrustCertificatesBase64?: string[] | Computed<string[]>;
  diskEncryptionSetId?: string | Computed<string>;
  dnsPrefix?: string | Computed<string>;
  dnsPrefixPrivateCluster?: string | Computed<string>;
  edgeZone?: string | Computed<string>;
  httpApplicationRoutingEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  imageCleanerEnabled?: boolean | Computed<boolean>;
  imageCleanerIntervalHours?: number | Computed<number>;
  kubernetesVersion?: string | Computed<string>;
  localAccountDisabled?: boolean | Computed<boolean>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  nodeOsUpgradeChannel?: string | Computed<string>;
  nodeResourceGroup?: string | Computed<string>;
  oidcIssuerEnabled?: boolean | Computed<boolean>;
  openServiceMeshEnabled?: boolean | Computed<boolean>;
  privateClusterEnabled?: boolean | Computed<boolean>;
  privateClusterPublicFqdnEnabled?: boolean | Computed<boolean>;
  privateDnsZoneId?: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  roleBasedAccessControlEnabled?: boolean | Computed<boolean>;
  runCommandEnabled?: boolean | Computed<boolean>;
  skuTier?: string | Computed<string>;
  supportPlan?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  workloadIdentityEnabled?: boolean | Computed<boolean>;
  aciConnectorLinux?: Cluster_AciConnectorLinux[] | Computed<Cluster_AciConnectorLinux[]>;
  apiServerAccessProfile?: Cluster_ApiServerAccessProfile[] | Computed<Cluster_ApiServerAccessProfile[]>;
  autoScalerProfile?: Cluster_AutoScalerProfile[] | Computed<Cluster_AutoScalerProfile[]>;
  azureActiveDirectoryRoleBasedAccessControl?: Cluster_AzureActiveDirectoryRoleBasedAccessControl[] | Computed<Cluster_AzureActiveDirectoryRoleBasedAccessControl[]>;
  bootstrapProfile?: Cluster_BootstrapProfile[] | Computed<Cluster_BootstrapProfile[]>;
  confidentialComputing?: Cluster_ConfidentialComputing[] | Computed<Cluster_ConfidentialComputing[]>;
  defaultNodePool?: Cluster_DefaultNodePool[] | Computed<Cluster_DefaultNodePool[]>;
  httpProxyConfig?: Cluster_HttpProxyConfig[] | Computed<Cluster_HttpProxyConfig[]>;
  identity?: Cluster_Identity[] | Computed<Cluster_Identity[]>;
  ingressApplicationGateway?: Cluster_IngressApplicationGateway[] | Computed<Cluster_IngressApplicationGateway[]>;
  keyManagementService?: Cluster_KeyManagementService[] | Computed<Cluster_KeyManagementService[]>;
  keyVaultSecretsProvider?: Cluster_KeyVaultSecretsProvider[] | Computed<Cluster_KeyVaultSecretsProvider[]>;
  kubeletIdentity?: Cluster_AciConnectorLinux_ConnectorIdentity[] | Computed<Cluster_AciConnectorLinux_ConnectorIdentity[]>;
  linuxProfile?: Cluster_LinuxProfile[] | Computed<Cluster_LinuxProfile[]>;
  maintenanceWindow?: Cluster_MaintenanceWindow[] | Computed<Cluster_MaintenanceWindow[]>;
  maintenanceWindowAutoUpgrade?: Cluster_MaintenanceWindowAutoUpgrade[] | Computed<Cluster_MaintenanceWindowAutoUpgrade[]>;
  maintenanceWindowNodeOs?: Cluster_MaintenanceWindowAutoUpgrade[] | Computed<Cluster_MaintenanceWindowAutoUpgrade[]>;
  microsoftDefender?: Cluster_MicrosoftDefender[] | Computed<Cluster_MicrosoftDefender[]>;
  monitorMetrics?: Cluster_MonitorMetrics[] | Computed<Cluster_MonitorMetrics[]>;
  networkProfile?: Cluster_NetworkProfile[] | Computed<Cluster_NetworkProfile[]>;
  nodeProvisioningProfile?: Cluster_NodeProvisioningProfile[] | Computed<Cluster_NodeProvisioningProfile[]>;
  omsAgent?: Cluster_OmsAgent[] | Computed<Cluster_OmsAgent[]>;
  serviceMeshProfile?: Cluster_ServiceMeshProfile[] | Computed<Cluster_ServiceMeshProfile[]>;
  servicePrincipal?: Cluster_ServicePrincipal[] | Computed<Cluster_ServicePrincipal[]>;
  storageProfile?: Cluster_StorageProfile[] | Computed<Cluster_StorageProfile[]>;
  timeouts?: Cluster_Timeouts | Computed<Cluster_Timeouts>;
  upgradeOverride?: Cluster_UpgradeOverride[] | Computed<Cluster_UpgradeOverride[]>;
  webAppRouting?: Cluster_WebAppRouting[] | Computed<Cluster_WebAppRouting[]>;
  windowsProfile?: Cluster_WindowsProfile[] | Computed<Cluster_WindowsProfile[]>;
  workloadAutoscalerProfile?: Cluster_WorkloadAutoscalerProfile[] | Computed<Cluster_WorkloadAutoscalerProfile[]>;
}

export interface ClusterAttrs {
  aiToolchainOperatorEnabled: boolean;
  automaticUpgradeChannel: string;
  azurePolicyEnabled: boolean;
  costAnalysisEnabled: boolean;
  currentKubernetesVersion: string;
  customCaTrustCertificatesBase64: string[];
  diskEncryptionSetId: string;
  dnsPrefix: string;
  dnsPrefixPrivateCluster: string;
  edgeZone: string;
  fqdn: string;
  httpApplicationRoutingEnabled: boolean;
  httpApplicationRoutingZoneName: string;
  id: string;
  imageCleanerEnabled: boolean;
  imageCleanerIntervalHours: number;
  kubeAdminConfig: Cluster_KubeAdminConfig[];
  kubeAdminConfigRaw: string;
  kubeConfig: Cluster_KubeAdminConfig[];
  kubeConfigRaw: string;
  kubernetesVersion: string;
  localAccountDisabled: boolean;
  location: string;
  name: string;
  nodeOsUpgradeChannel: string;
  nodeResourceGroup: string;
  nodeResourceGroupId: string;
  oidcIssuerEnabled: boolean;
  oidcIssuerUrl: string;
  openServiceMeshEnabled: boolean;
  portalFqdn: string;
  privateClusterEnabled: boolean;
  privateClusterPublicFqdnEnabled: boolean;
  privateDnsZoneId: string;
  privateFqdn: string;
  resourceGroupName: string;
  roleBasedAccessControlEnabled: boolean;
  runCommandEnabled: boolean;
  skuTier: string;
  supportPlan: string;
  tags: Record<string, string>;
  workloadIdentityEnabled: boolean;
  aciConnectorLinux: Cluster_AciConnectorLinux[];
  apiServerAccessProfile: Cluster_ApiServerAccessProfile[];
  autoScalerProfile: Cluster_AutoScalerProfile[];
  azureActiveDirectoryRoleBasedAccessControl: Cluster_AzureActiveDirectoryRoleBasedAccessControl[];
  bootstrapProfile: Cluster_BootstrapProfile[];
  confidentialComputing: Cluster_ConfidentialComputing[];
  defaultNodePool: Cluster_DefaultNodePool[];
  httpProxyConfig: Cluster_HttpProxyConfig[];
  identity: Cluster_Identity[];
  ingressApplicationGateway: Cluster_IngressApplicationGateway[];
  keyManagementService: Cluster_KeyManagementService[];
  keyVaultSecretsProvider: Cluster_KeyVaultSecretsProvider[];
  kubeletIdentity: Cluster_AciConnectorLinux_ConnectorIdentity[];
  linuxProfile: Cluster_LinuxProfile[];
  maintenanceWindow: Cluster_MaintenanceWindow[];
  maintenanceWindowAutoUpgrade: Cluster_MaintenanceWindowAutoUpgrade[];
  maintenanceWindowNodeOs: Cluster_MaintenanceWindowAutoUpgrade[];
  microsoftDefender: Cluster_MicrosoftDefender[];
  monitorMetrics: Cluster_MonitorMetrics[];
  networkProfile: Cluster_NetworkProfile[];
  nodeProvisioningProfile: Cluster_NodeProvisioningProfile[];
  omsAgent: Cluster_OmsAgent[];
  serviceMeshProfile: Cluster_ServiceMeshProfile[];
  servicePrincipal: Cluster_ServicePrincipal[];
  storageProfile: Cluster_StorageProfile[];
  timeouts: Cluster_Timeouts;
  upgradeOverride: Cluster_UpgradeOverride[];
  webAppRouting: Cluster_WebAppRouting[];
  windowsProfile: Cluster_WindowsProfile[];
  workloadAutoscalerProfile: Cluster_WorkloadAutoscalerProfile[];
}

export const Cluster: ResourceBinding<ClusterConfig, ClusterAttrs> = {
  wireType: "azurerm_kubernetes_cluster",
  fields: {
    aiToolchainOperatorEnabled: "ai_toolchain_operator_enabled",
    automaticUpgradeChannel: "automatic_upgrade_channel",
    azurePolicyEnabled: "azure_policy_enabled",
    costAnalysisEnabled: "cost_analysis_enabled",
    customCaTrustCertificatesBase64: "custom_ca_trust_certificates_base64",
    diskEncryptionSetId: "disk_encryption_set_id",
    dnsPrefix: "dns_prefix",
    dnsPrefixPrivateCluster: "dns_prefix_private_cluster",
    edgeZone: "edge_zone",
    httpApplicationRoutingEnabled: "http_application_routing_enabled",
    id: "id",
    imageCleanerEnabled: "image_cleaner_enabled",
    imageCleanerIntervalHours: "image_cleaner_interval_hours",
    kubernetesVersion: "kubernetes_version",
    localAccountDisabled: "local_account_disabled",
    location: "location",
    name: "name",
    nodeOsUpgradeChannel: "node_os_upgrade_channel",
    nodeResourceGroup: "node_resource_group",
    oidcIssuerEnabled: "oidc_issuer_enabled",
    openServiceMeshEnabled: "open_service_mesh_enabled",
    privateClusterEnabled: "private_cluster_enabled",
    privateClusterPublicFqdnEnabled: "private_cluster_public_fqdn_enabled",
    privateDnsZoneId: "private_dns_zone_id",
    resourceGroupName: "resource_group_name",
    roleBasedAccessControlEnabled: "role_based_access_control_enabled",
    runCommandEnabled: "run_command_enabled",
    skuTier: "sku_tier",
    supportPlan: "support_plan",
    tags: "tags",
    workloadIdentityEnabled: "workload_identity_enabled",
    aciConnectorLinux: {
      wireName: "aci_connector_linux",
      kind: "list",
      fields: Cluster_AciConnectorLinuxFields,
    },
    apiServerAccessProfile: {
      wireName: "api_server_access_profile",
      kind: "list",
      fields: Cluster_ApiServerAccessProfileFields,
    },
    autoScalerProfile: {
      wireName: "auto_scaler_profile",
      kind: "list",
      fields: Cluster_AutoScalerProfileFields,
    },
    azureActiveDirectoryRoleBasedAccessControl: {
      wireName: "azure_active_directory_role_based_access_control",
      kind: "list",
      fields: Cluster_AzureActiveDirectoryRoleBasedAccessControlFields,
    },
    bootstrapProfile: {
      wireName: "bootstrap_profile",
      kind: "list",
      fields: Cluster_BootstrapProfileFields,
    },
    confidentialComputing: {
      wireName: "confidential_computing",
      kind: "list",
      fields: Cluster_ConfidentialComputingFields,
    },
    defaultNodePool: {
      wireName: "default_node_pool",
      kind: "list",
      fields: Cluster_DefaultNodePoolFields,
    },
    httpProxyConfig: {
      wireName: "http_proxy_config",
      kind: "list",
      fields: Cluster_HttpProxyConfigFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: Cluster_IdentityFields,
    },
    ingressApplicationGateway: {
      wireName: "ingress_application_gateway",
      kind: "list",
      fields: Cluster_IngressApplicationGatewayFields,
    },
    keyManagementService: {
      wireName: "key_management_service",
      kind: "list",
      fields: Cluster_KeyManagementServiceFields,
    },
    keyVaultSecretsProvider: {
      wireName: "key_vault_secrets_provider",
      kind: "list",
      fields: Cluster_KeyVaultSecretsProviderFields,
    },
    kubeletIdentity: {
      wireName: "kubelet_identity",
      kind: "list",
      fields: Cluster_AciConnectorLinux_ConnectorIdentityFields,
    },
    linuxProfile: {
      wireName: "linux_profile",
      kind: "list",
      fields: Cluster_LinuxProfileFields,
    },
    maintenanceWindow: {
      wireName: "maintenance_window",
      kind: "list",
      fields: Cluster_MaintenanceWindowFields,
    },
    maintenanceWindowAutoUpgrade: {
      wireName: "maintenance_window_auto_upgrade",
      kind: "list",
      fields: Cluster_MaintenanceWindowAutoUpgradeFields,
    },
    maintenanceWindowNodeOs: {
      wireName: "maintenance_window_node_os",
      kind: "list",
      fields: Cluster_MaintenanceWindowAutoUpgradeFields,
    },
    microsoftDefender: {
      wireName: "microsoft_defender",
      kind: "list",
      fields: Cluster_MicrosoftDefenderFields,
    },
    monitorMetrics: {
      wireName: "monitor_metrics",
      kind: "list",
      fields: Cluster_MonitorMetricsFields,
    },
    networkProfile: {
      wireName: "network_profile",
      kind: "list",
      fields: Cluster_NetworkProfileFields,
    },
    nodeProvisioningProfile: {
      wireName: "node_provisioning_profile",
      kind: "list",
      fields: Cluster_NodeProvisioningProfileFields,
    },
    omsAgent: {
      wireName: "oms_agent",
      kind: "list",
      fields: Cluster_OmsAgentFields,
    },
    serviceMeshProfile: {
      wireName: "service_mesh_profile",
      kind: "list",
      fields: Cluster_ServiceMeshProfileFields,
    },
    servicePrincipal: {
      wireName: "service_principal",
      kind: "list",
      fields: Cluster_ServicePrincipalFields,
    },
    storageProfile: {
      wireName: "storage_profile",
      kind: "list",
      fields: Cluster_StorageProfileFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Cluster_TimeoutsFields,
    },
    upgradeOverride: {
      wireName: "upgrade_override",
      kind: "list",
      fields: Cluster_UpgradeOverrideFields,
    },
    webAppRouting: {
      wireName: "web_app_routing",
      kind: "list",
      fields: Cluster_WebAppRoutingFields,
    },
    windowsProfile: {
      wireName: "windows_profile",
      kind: "list",
      fields: Cluster_WindowsProfileFields,
    },
    workloadAutoscalerProfile: {
      wireName: "workload_autoscaler_profile",
      kind: "list",
      fields: Cluster_WorkloadAutoscalerProfileFields,
    },
  },
};
