// Code generated by `ubx sdk gen` from azurerm_kubernetes_fleet_manager. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FleetManager_HubProfile {
  dnsPrefix: string;
  fqdn: string;
  kubernetesVersion: string;
}

export interface FleetManager_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const FleetManager_HubProfileFields: FieldMap = {
  dnsPrefix: "dns_prefix",
  fqdn: "fqdn",
  kubernetesVersion: "kubernetes_version",
};

const FleetManager_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FleetManagerConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  hubProfile?: FleetManager_HubProfile[] | Computed<FleetManager_HubProfile[]>;
  timeouts?: FleetManager_Timeouts | Computed<FleetManager_Timeouts>;
}

export interface FleetManagerAttrs {
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  hubProfile: FleetManager_HubProfile[];
  timeouts: FleetManager_Timeouts;
}

export const FleetManager: ResourceBinding<FleetManagerConfig, FleetManagerAttrs> = {
  wireType: "azurerm_kubernetes_fleet_manager",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    hubProfile: {
      wireName: "hub_profile",
      kind: "list",
      fields: FleetManager_HubProfileFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FleetManager_TimeoutsFields,
    },
  },
};
