// Code generated by `ubx sdk gen` from azurerm_cognitive_account_project. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccountProject_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface AccountProject_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AccountProject_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const AccountProject_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AccountProjectConfig {
  cognitiveAccountId: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  identity?: AccountProject_Identity[] | Computed<AccountProject_Identity[]>;
  timeouts?: AccountProject_Timeouts | Computed<AccountProject_Timeouts>;
}

export interface AccountProjectAttrs {
  cognitiveAccountId: string;
  default: boolean;
  description: string;
  displayName: string;
  endpoints: Record<string, string>;
  id: string;
  location: string;
  name: string;
  tags: Record<string, string>;
  identity: AccountProject_Identity[];
  timeouts: AccountProject_Timeouts;
}

export const AccountProject: ResourceBinding<AccountProjectConfig, AccountProjectAttrs> = {
  wireType: "azurerm_cognitive_account_project",
  fields: {
    cognitiveAccountId: "cognitive_account_id",
    description: "description",
    displayName: "display_name",
    id: "id",
    location: "location",
    name: "name",
    tags: "tags",
    identity: {
      wireName: "identity",
      kind: "list",
      fields: AccountProject_IdentityFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AccountProject_TimeoutsFields,
    },
  },
};
