// Code generated by `ubx sdk gen` from azurerm_spring_cloud_app_cosmosdb_association. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudAppCosmosdbAssociation_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const CloudAppCosmosdbAssociation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface CloudAppCosmosdbAssociationConfig {
  apiType: string | Computed<string>;
  cosmosdbAccessKey: string | Computed<string>;
  cosmosdbAccountId: string | Computed<string>;
  cosmosdbCassandraKeyspaceName?: string | Computed<string>;
  cosmosdbGremlinDatabaseName?: string | Computed<string>;
  cosmosdbGremlinGraphName?: string | Computed<string>;
  cosmosdbMongoDatabaseName?: string | Computed<string>;
  cosmosdbSqlDatabaseName?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  springCloudAppId: string | Computed<string>;
  timeouts?: CloudAppCosmosdbAssociation_Timeouts | Computed<CloudAppCosmosdbAssociation_Timeouts>;
}

export interface CloudAppCosmosdbAssociationAttrs {
  apiType: string;
  cosmosdbAccessKey: string;
  cosmosdbAccountId: string;
  cosmosdbCassandraKeyspaceName: string;
  cosmosdbGremlinDatabaseName: string;
  cosmosdbGremlinGraphName: string;
  cosmosdbMongoDatabaseName: string;
  cosmosdbSqlDatabaseName: string;
  id: string;
  name: string;
  springCloudAppId: string;
  timeouts: CloudAppCosmosdbAssociation_Timeouts;
}

export const CloudAppCosmosdbAssociation: ResourceBinding<CloudAppCosmosdbAssociationConfig, CloudAppCosmosdbAssociationAttrs> = {
  wireType: "azurerm_spring_cloud_app_cosmosdb_association",
  fields: {
    apiType: "api_type",
    cosmosdbAccessKey: "cosmosdb_access_key",
    cosmosdbAccountId: "cosmosdb_account_id",
    cosmosdbCassandraKeyspaceName: "cosmosdb_cassandra_keyspace_name",
    cosmosdbGremlinDatabaseName: "cosmosdb_gremlin_database_name",
    cosmosdbGremlinGraphName: "cosmosdb_gremlin_graph_name",
    cosmosdbMongoDatabaseName: "cosmosdb_mongo_database_name",
    cosmosdbSqlDatabaseName: "cosmosdb_sql_database_name",
    id: "id",
    name: "name",
    springCloudAppId: "spring_cloud_app_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CloudAppCosmosdbAssociation_TimeoutsFields,
    },
  },
};
