// Code generated by `ubx sdk gen` from azurerm_spring_cloud_app_mysql_association. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudAppMysqlAssociation_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const CloudAppMysqlAssociation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface CloudAppMysqlAssociationConfig {
  databaseName: string | Computed<string>;
  id?: string | Computed<string>;
  mysqlServerId: string | Computed<string>;
  name: string | Computed<string>;
  password: string | Computed<string>;
  springCloudAppId: string | Computed<string>;
  username: string | Computed<string>;
  timeouts?: CloudAppMysqlAssociation_Timeouts | Computed<CloudAppMysqlAssociation_Timeouts>;
}

export interface CloudAppMysqlAssociationAttrs {
  databaseName: string;
  id: string;
  mysqlServerId: string;
  name: string;
  password: string;
  springCloudAppId: string;
  username: string;
  timeouts: CloudAppMysqlAssociation_Timeouts;
}

export const CloudAppMysqlAssociation: ResourceBinding<CloudAppMysqlAssociationConfig, CloudAppMysqlAssociationAttrs> = {
  wireType: "azurerm_spring_cloud_app_mysql_association",
  fields: {
    databaseName: "database_name",
    id: "id",
    mysqlServerId: "mysql_server_id",
    name: "name",
    password: "password",
    springCloudAppId: "spring_cloud_app_id",
    username: "username",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CloudAppMysqlAssociation_TimeoutsFields,
    },
  },
};
