// Code generated by `ubx sdk gen` from azurerm_spring_cloud_app. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudApp_CustomPersistentDisk {
  mountOptions: string[];
  mountPath: string;
  readOnlyEnabled: boolean;
  shareName: string;
  storageName: string;
}

export interface CloudApp_Identity {
  identityIds: string[];
  principalId: string;
  tenantId: string;
  type: string;
}

export interface CloudApp_IngressSettings {
  backendProtocol: string;
  readTimeoutInSeconds: number;
  sendTimeoutInSeconds: number;
  sessionAffinity: string;
  sessionCookieMaxAge: number;
}

export interface CloudApp_PersistentDisk {
  mountPath: string;
  sizeInGb: number;
}

export interface CloudApp_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const CloudApp_CustomPersistentDiskFields: FieldMap = {
  mountOptions: "mount_options",
  mountPath: "mount_path",
  readOnlyEnabled: "read_only_enabled",
  shareName: "share_name",
  storageName: "storage_name",
};

const CloudApp_IdentityFields: FieldMap = {
  identityIds: "identity_ids",
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const CloudApp_IngressSettingsFields: FieldMap = {
  backendProtocol: "backend_protocol",
  readTimeoutInSeconds: "read_timeout_in_seconds",
  sendTimeoutInSeconds: "send_timeout_in_seconds",
  sessionAffinity: "session_affinity",
  sessionCookieMaxAge: "session_cookie_max_age",
};

const CloudApp_PersistentDiskFields: FieldMap = {
  mountPath: "mount_path",
  sizeInGb: "size_in_gb",
};

const CloudApp_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface CloudAppConfig {
  addonJson?: string | Computed<string>;
  httpsOnly?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  isPublic?: boolean | Computed<boolean>;
  name: string | Computed<string>;
  publicEndpointEnabled?: boolean | Computed<boolean>;
  resourceGroupName: string | Computed<string>;
  serviceName: string | Computed<string>;
  tlsEnabled?: boolean | Computed<boolean>;
  customPersistentDisk?: CloudApp_CustomPersistentDisk[] | Computed<CloudApp_CustomPersistentDisk[]>;
  identity?: CloudApp_Identity[] | Computed<CloudApp_Identity[]>;
  ingressSettings?: CloudApp_IngressSettings[] | Computed<CloudApp_IngressSettings[]>;
  persistentDisk?: CloudApp_PersistentDisk[] | Computed<CloudApp_PersistentDisk[]>;
  timeouts?: CloudApp_Timeouts | Computed<CloudApp_Timeouts>;
}

export interface CloudAppAttrs {
  addonJson: string;
  fqdn: string;
  httpsOnly: boolean;
  id: string;
  isPublic: boolean;
  name: string;
  publicEndpointEnabled: boolean;
  resourceGroupName: string;
  serviceName: string;
  tlsEnabled: boolean;
  url: string;
  customPersistentDisk: CloudApp_CustomPersistentDisk[];
  identity: CloudApp_Identity[];
  ingressSettings: CloudApp_IngressSettings[];
  persistentDisk: CloudApp_PersistentDisk[];
  timeouts: CloudApp_Timeouts;
}

export const CloudApp: ResourceBinding<CloudAppConfig, CloudAppAttrs> = {
  wireType: "azurerm_spring_cloud_app",
  fields: {
    addonJson: "addon_json",
    httpsOnly: "https_only",
    id: "id",
    isPublic: "is_public",
    name: "name",
    publicEndpointEnabled: "public_endpoint_enabled",
    resourceGroupName: "resource_group_name",
    serviceName: "service_name",
    tlsEnabled: "tls_enabled",
    customPersistentDisk: {
      wireName: "custom_persistent_disk",
      kind: "list",
      fields: CloudApp_CustomPersistentDiskFields,
    },
    identity: {
      wireName: "identity",
      kind: "list",
      fields: CloudApp_IdentityFields,
    },
    ingressSettings: {
      wireName: "ingress_settings",
      kind: "list",
      fields: CloudApp_IngressSettingsFields,
    },
    persistentDisk: {
      wireName: "persistent_disk",
      kind: "list",
      fields: CloudApp_PersistentDiskFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CloudApp_TimeoutsFields,
    },
  },
};
