// Code generated by `ubx sdk gen` from azurerm_spring_cloud_java_deployment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudJavaDeployment_Quota {
  cpu: string;
  memory: string;
}

export interface CloudJavaDeployment_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const CloudJavaDeployment_QuotaFields: FieldMap = {
  cpu: "cpu",
  memory: "memory",
};

const CloudJavaDeployment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface CloudJavaDeploymentConfig {
  environmentVariables?: Record<string, string> | Computed<Record<string, string>>;
  id?: string | Computed<string>;
  instanceCount?: number | Computed<number>;
  jvmOptions?: string | Computed<string>;
  name: string | Computed<string>;
  runtimeVersion?: string | Computed<string>;
  springCloudAppId: string | Computed<string>;
  quota?: CloudJavaDeployment_Quota[] | Computed<CloudJavaDeployment_Quota[]>;
  timeouts?: CloudJavaDeployment_Timeouts | Computed<CloudJavaDeployment_Timeouts>;
}

export interface CloudJavaDeploymentAttrs {
  environmentVariables: Record<string, string>;
  id: string;
  instanceCount: number;
  jvmOptions: string;
  name: string;
  runtimeVersion: string;
  springCloudAppId: string;
  quota: CloudJavaDeployment_Quota[];
  timeouts: CloudJavaDeployment_Timeouts;
}

export const CloudJavaDeployment: ResourceBinding<CloudJavaDeploymentConfig, CloudJavaDeploymentAttrs> = {
  wireType: "azurerm_spring_cloud_java_deployment",
  fields: {
    environmentVariables: "environment_variables",
    id: "id",
    instanceCount: "instance_count",
    jvmOptions: "jvm_options",
    name: "name",
    runtimeVersion: "runtime_version",
    springCloudAppId: "spring_cloud_app_id",
    quota: {
      wireName: "quota",
      kind: "list",
      fields: CloudJavaDeployment_QuotaFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CloudJavaDeployment_TimeoutsFields,
    },
  },
};
