// Code generated by `ubx sdk gen` from azurerm_spring_cloud_api_portal. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudApiPortal_Sso {
  clientId: string;
  clientSecret: string;
  issuerUri: string;
  scope: string[];
}

export interface CloudApiPortal_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const CloudApiPortal_SsoFields: FieldMap = {
  clientId: "client_id",
  clientSecret: "client_secret",
  issuerUri: "issuer_uri",
  scope: "scope",
};

const CloudApiPortal_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface CloudApiPortalConfig {
  apiTryOutEnabled?: boolean | Computed<boolean>;
  gatewayIds?: string[] | Computed<string[]>;
  httpsOnlyEnabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  instanceCount?: number | Computed<number>;
  name: string | Computed<string>;
  publicNetworkAccessEnabled?: boolean | Computed<boolean>;
  springCloudServiceId: string | Computed<string>;
  sso?: CloudApiPortal_Sso[] | Computed<CloudApiPortal_Sso[]>;
  timeouts?: CloudApiPortal_Timeouts | Computed<CloudApiPortal_Timeouts>;
}

export interface CloudApiPortalAttrs {
  apiTryOutEnabled: boolean;
  gatewayIds: string[];
  httpsOnlyEnabled: boolean;
  id: string;
  instanceCount: number;
  name: string;
  publicNetworkAccessEnabled: boolean;
  springCloudServiceId: string;
  url: string;
  sso: CloudApiPortal_Sso[];
  timeouts: CloudApiPortal_Timeouts;
}

export const CloudApiPortal: ResourceBinding<CloudApiPortalConfig, CloudApiPortalAttrs> = {
  wireType: "azurerm_spring_cloud_api_portal",
  fields: {
    apiTryOutEnabled: "api_try_out_enabled",
    gatewayIds: "gateway_ids",
    httpsOnlyEnabled: "https_only_enabled",
    id: "id",
    instanceCount: "instance_count",
    name: "name",
    publicNetworkAccessEnabled: "public_network_access_enabled",
    springCloudServiceId: "spring_cloud_service_id",
    sso: {
      wireName: "sso",
      kind: "list",
      fields: CloudApiPortal_SsoFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CloudApiPortal_TimeoutsFields,
    },
  },
};
