// Code generated by `ubx sdk gen` from azurerm_spring_cloud_build_deployment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudBuildDeployment_Quota {
  cpu: string;
  memory: string;
}

export interface CloudBuildDeployment_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const CloudBuildDeployment_QuotaFields: FieldMap = {
  cpu: "cpu",
  memory: "memory",
};

const CloudBuildDeployment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface CloudBuildDeploymentConfig {
  addonJson?: string | Computed<string>;
  applicationPerformanceMonitoringIds?: string[] | Computed<string[]>;
  buildResultId: string | Computed<string>;
  environmentVariables?: Record<string, string> | Computed<Record<string, string>>;
  id?: string | Computed<string>;
  instanceCount?: number | Computed<number>;
  name: string | Computed<string>;
  springCloudAppId: string | Computed<string>;
  quota?: CloudBuildDeployment_Quota[] | Computed<CloudBuildDeployment_Quota[]>;
  timeouts?: CloudBuildDeployment_Timeouts | Computed<CloudBuildDeployment_Timeouts>;
}

export interface CloudBuildDeploymentAttrs {
  addonJson: string;
  applicationPerformanceMonitoringIds: string[];
  buildResultId: string;
  environmentVariables: Record<string, string>;
  id: string;
  instanceCount: number;
  name: string;
  springCloudAppId: string;
  quota: CloudBuildDeployment_Quota[];
  timeouts: CloudBuildDeployment_Timeouts;
}

export const CloudBuildDeployment: ResourceBinding<CloudBuildDeploymentConfig, CloudBuildDeploymentAttrs> = {
  wireType: "azurerm_spring_cloud_build_deployment",
  fields: {
    addonJson: "addon_json",
    applicationPerformanceMonitoringIds: "application_performance_monitoring_ids",
    buildResultId: "build_result_id",
    environmentVariables: "environment_variables",
    id: "id",
    instanceCount: "instance_count",
    name: "name",
    springCloudAppId: "spring_cloud_app_id",
    quota: {
      wireName: "quota",
      kind: "list",
      fields: CloudBuildDeployment_QuotaFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CloudBuildDeployment_TimeoutsFields,
    },
  },
};
