// Code generated by `ubx sdk gen` from azurerm_spring_cloud_certificate. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudCertificate_Timeouts {
  create: string;
  delete: string;
  read: string;
}

const CloudCertificate_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
};

export interface CloudCertificateConfig {
  certificateContent?: string | Computed<string>;
  excludePrivateKey?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  keyVaultCertificateId?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  serviceName: string | Computed<string>;
  timeouts?: CloudCertificate_Timeouts | Computed<CloudCertificate_Timeouts>;
}

export interface CloudCertificateAttrs {
  certificateContent: string;
  excludePrivateKey: boolean;
  id: string;
  keyVaultCertificateId: string;
  name: string;
  resourceGroupName: string;
  serviceName: string;
  thumbprint: string;
  timeouts: CloudCertificate_Timeouts;
}

export const CloudCertificate: ResourceBinding<CloudCertificateConfig, CloudCertificateAttrs> = {
  wireType: "azurerm_spring_cloud_certificate",
  fields: {
    certificateContent: "certificate_content",
    excludePrivateKey: "exclude_private_key",
    id: "id",
    keyVaultCertificateId: "key_vault_certificate_id",
    name: "name",
    resourceGroupName: "resource_group_name",
    serviceName: "service_name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CloudCertificate_TimeoutsFields,
    },
  },
};
