// Code generated by `ubx sdk gen` from azurerm_monitor_alert_processing_rule_action_group. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AlertProcessingRuleActionGroup_Condition_AlertContext {
  operator: string;
  values: string[];
}

export interface AlertProcessingRuleActionGroup_Condition {
  alertContext: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  alertRuleId: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  alertRuleName: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  description: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  monitorCondition: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  monitorService: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  severity: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  signalType: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  targetResource: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  targetResourceGroup: AlertProcessingRuleActionGroup_Condition_AlertContext[];
  targetResourceType: AlertProcessingRuleActionGroup_Condition_AlertContext[];
}

export interface AlertProcessingRuleActionGroup_Schedule_Recurrence_Daily {
  endTime: string;
  startTime: string;
}

export interface AlertProcessingRuleActionGroup_Schedule_Recurrence_Monthly {
  daysOfMonth: number[];
  endTime: string;
  startTime: string;
}

export interface AlertProcessingRuleActionGroup_Schedule_Recurrence_Weekly {
  daysOfWeek: string[];
  endTime: string;
  startTime: string;
}

export interface AlertProcessingRuleActionGroup_Schedule_Recurrence {
  daily: AlertProcessingRuleActionGroup_Schedule_Recurrence_Daily[];
  monthly: AlertProcessingRuleActionGroup_Schedule_Recurrence_Monthly[];
  weekly: AlertProcessingRuleActionGroup_Schedule_Recurrence_Weekly[];
}

export interface AlertProcessingRuleActionGroup_Schedule {
  effectiveFrom: string;
  effectiveUntil: string;
  timeZone: string;
  recurrence: AlertProcessingRuleActionGroup_Schedule_Recurrence[];
}

export interface AlertProcessingRuleActionGroup_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AlertProcessingRuleActionGroup_Condition_AlertContextFields: FieldMap = {
  operator: "operator",
  values: "values",
};

const AlertProcessingRuleActionGroup_ConditionFields: FieldMap = {
  alertContext: {
    wireName: "alert_context",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  alertRuleId: {
    wireName: "alert_rule_id",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  alertRuleName: {
    wireName: "alert_rule_name",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  description: {
    wireName: "description",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  monitorCondition: {
    wireName: "monitor_condition",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  monitorService: {
    wireName: "monitor_service",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  severity: {
    wireName: "severity",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  signalType: {
    wireName: "signal_type",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  targetResource: {
    wireName: "target_resource",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  targetResourceGroup: {
    wireName: "target_resource_group",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
  targetResourceType: {
    wireName: "target_resource_type",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Condition_AlertContextFields,
  },
};

const AlertProcessingRuleActionGroup_Schedule_Recurrence_DailyFields: FieldMap = {
  endTime: "end_time",
  startTime: "start_time",
};

const AlertProcessingRuleActionGroup_Schedule_Recurrence_MonthlyFields: FieldMap = {
  daysOfMonth: "days_of_month",
  endTime: "end_time",
  startTime: "start_time",
};

const AlertProcessingRuleActionGroup_Schedule_Recurrence_WeeklyFields: FieldMap = {
  daysOfWeek: "days_of_week",
  endTime: "end_time",
  startTime: "start_time",
};

const AlertProcessingRuleActionGroup_Schedule_RecurrenceFields: FieldMap = {
  daily: {
    wireName: "daily",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Schedule_Recurrence_DailyFields,
  },
  monthly: {
    wireName: "monthly",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Schedule_Recurrence_MonthlyFields,
  },
  weekly: {
    wireName: "weekly",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Schedule_Recurrence_WeeklyFields,
  },
};

const AlertProcessingRuleActionGroup_ScheduleFields: FieldMap = {
  effectiveFrom: "effective_from",
  effectiveUntil: "effective_until",
  timeZone: "time_zone",
  recurrence: {
    wireName: "recurrence",
    kind: "list",
    fields: AlertProcessingRuleActionGroup_Schedule_RecurrenceFields,
  },
};

const AlertProcessingRuleActionGroup_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AlertProcessingRuleActionGroupConfig {
  addActionGroupIds: string[] | Computed<string[]>;
  description?: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  scopes: string[] | Computed<string[]>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  condition?: AlertProcessingRuleActionGroup_Condition[] | Computed<AlertProcessingRuleActionGroup_Condition[]>;
  schedule?: AlertProcessingRuleActionGroup_Schedule[] | Computed<AlertProcessingRuleActionGroup_Schedule[]>;
  timeouts?: AlertProcessingRuleActionGroup_Timeouts | Computed<AlertProcessingRuleActionGroup_Timeouts>;
}

export interface AlertProcessingRuleActionGroupAttrs {
  addActionGroupIds: string[];
  description: string;
  enabled: boolean;
  id: string;
  name: string;
  resourceGroupName: string;
  scopes: string[];
  tags: Record<string, string>;
  condition: AlertProcessingRuleActionGroup_Condition[];
  schedule: AlertProcessingRuleActionGroup_Schedule[];
  timeouts: AlertProcessingRuleActionGroup_Timeouts;
}

export const AlertProcessingRuleActionGroup: ResourceBinding<AlertProcessingRuleActionGroupConfig, AlertProcessingRuleActionGroupAttrs> = {
  wireType: "azurerm_monitor_alert_processing_rule_action_group",
  fields: {
    addActionGroupIds: "add_action_group_ids",
    description: "description",
    enabled: "enabled",
    id: "id",
    name: "name",
    resourceGroupName: "resource_group_name",
    scopes: "scopes",
    tags: "tags",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: AlertProcessingRuleActionGroup_ConditionFields,
    },
    schedule: {
      wireName: "schedule",
      kind: "list",
      fields: AlertProcessingRuleActionGroup_ScheduleFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AlertProcessingRuleActionGroup_TimeoutsFields,
    },
  },
};
