// Code generated by `ubx sdk gen` from azurerm_monitor_autoscale_setting. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AutoscaleSetting_Notification_Email {
  customEmails: string[];
  sendToSubscriptionAdministrator: boolean;
  sendToSubscriptionCoAdministrator: boolean;
}

export interface AutoscaleSetting_Notification_Webhook {
  properties: Record<string, string>;
  serviceUri: string;
}

export interface AutoscaleSetting_Notification {
  email: AutoscaleSetting_Notification_Email[];
  webhook: AutoscaleSetting_Notification_Webhook[];
}

export interface AutoscaleSetting_Predictive {
  lookAheadTime: string;
  scaleMode: string;
}

export interface AutoscaleSetting_Profile_Capacity {
  default: number;
  maximum: number;
  minimum: number;
}

export interface AutoscaleSetting_Profile_FixedDate {
  end: string;
  start: string;
  timezone: string;
}

export interface AutoscaleSetting_Profile_Recurrence {
  days: string[];
  hours: number[];
  minutes: number[];
  timezone: string;
}

export interface AutoscaleSetting_Profile_Rule_MetricTrigger_Dimensions {
  name: string;
  operator: string;
  values: string[];
}

export interface AutoscaleSetting_Profile_Rule_MetricTrigger {
  divideByInstanceCount: boolean;
  metricName: string;
  metricNamespace: string;
  metricResourceId: string;
  operator: string;
  statistic: string;
  threshold: number;
  timeAggregation: string;
  timeGrain: string;
  timeWindow: string;
  dimensions: AutoscaleSetting_Profile_Rule_MetricTrigger_Dimensions[];
}

export interface AutoscaleSetting_Profile_Rule_ScaleAction {
  cooldown: string;
  direction: string;
  type: string;
  value: number;
}

export interface AutoscaleSetting_Profile_Rule {
  metricTrigger: AutoscaleSetting_Profile_Rule_MetricTrigger[];
  scaleAction: AutoscaleSetting_Profile_Rule_ScaleAction[];
}

export interface AutoscaleSetting_Profile {
  name: string;
  capacity: AutoscaleSetting_Profile_Capacity[];
  fixedDate: AutoscaleSetting_Profile_FixedDate[];
  recurrence: AutoscaleSetting_Profile_Recurrence[];
  rule: AutoscaleSetting_Profile_Rule[];
}

export interface AutoscaleSetting_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const AutoscaleSetting_Notification_EmailFields: FieldMap = {
  customEmails: "custom_emails",
  sendToSubscriptionAdministrator: "send_to_subscription_administrator",
  sendToSubscriptionCoAdministrator: "send_to_subscription_co_administrator",
};

const AutoscaleSetting_Notification_WebhookFields: FieldMap = {
  properties: "properties",
  serviceUri: "service_uri",
};

const AutoscaleSetting_NotificationFields: FieldMap = {
  email: {
    wireName: "email",
    kind: "list",
    fields: AutoscaleSetting_Notification_EmailFields,
  },
  webhook: {
    wireName: "webhook",
    kind: "list",
    fields: AutoscaleSetting_Notification_WebhookFields,
  },
};

const AutoscaleSetting_PredictiveFields: FieldMap = {
  lookAheadTime: "look_ahead_time",
  scaleMode: "scale_mode",
};

const AutoscaleSetting_Profile_CapacityFields: FieldMap = {
  default: "default",
  maximum: "maximum",
  minimum: "minimum",
};

const AutoscaleSetting_Profile_FixedDateFields: FieldMap = {
  end: "end",
  start: "start",
  timezone: "timezone",
};

const AutoscaleSetting_Profile_RecurrenceFields: FieldMap = {
  days: "days",
  hours: "hours",
  minutes: "minutes",
  timezone: "timezone",
};

const AutoscaleSetting_Profile_Rule_MetricTrigger_DimensionsFields: FieldMap = {
  name: "name",
  operator: "operator",
  values: "values",
};

const AutoscaleSetting_Profile_Rule_MetricTriggerFields: FieldMap = {
  divideByInstanceCount: "divide_by_instance_count",
  metricName: "metric_name",
  metricNamespace: "metric_namespace",
  metricResourceId: "metric_resource_id",
  operator: "operator",
  statistic: "statistic",
  threshold: "threshold",
  timeAggregation: "time_aggregation",
  timeGrain: "time_grain",
  timeWindow: "time_window",
  dimensions: {
    wireName: "dimensions",
    kind: "list",
    fields: AutoscaleSetting_Profile_Rule_MetricTrigger_DimensionsFields,
  },
};

const AutoscaleSetting_Profile_Rule_ScaleActionFields: FieldMap = {
  cooldown: "cooldown",
  direction: "direction",
  type: "type",
  value: "value",
};

const AutoscaleSetting_Profile_RuleFields: FieldMap = {
  metricTrigger: {
    wireName: "metric_trigger",
    kind: "list",
    fields: AutoscaleSetting_Profile_Rule_MetricTriggerFields,
  },
  scaleAction: {
    wireName: "scale_action",
    kind: "list",
    fields: AutoscaleSetting_Profile_Rule_ScaleActionFields,
  },
};

const AutoscaleSetting_ProfileFields: FieldMap = {
  name: "name",
  capacity: {
    wireName: "capacity",
    kind: "list",
    fields: AutoscaleSetting_Profile_CapacityFields,
  },
  fixedDate: {
    wireName: "fixed_date",
    kind: "list",
    fields: AutoscaleSetting_Profile_FixedDateFields,
  },
  recurrence: {
    wireName: "recurrence",
    kind: "list",
    fields: AutoscaleSetting_Profile_RecurrenceFields,
  },
  rule: {
    wireName: "rule",
    kind: "list",
    fields: AutoscaleSetting_Profile_RuleFields,
  },
};

const AutoscaleSetting_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface AutoscaleSettingConfig {
  enabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  targetResourceId: string | Computed<string>;
  notification?: AutoscaleSetting_Notification[] | Computed<AutoscaleSetting_Notification[]>;
  predictive?: AutoscaleSetting_Predictive[] | Computed<AutoscaleSetting_Predictive[]>;
  profile?: AutoscaleSetting_Profile[] | Computed<AutoscaleSetting_Profile[]>;
  timeouts?: AutoscaleSetting_Timeouts | Computed<AutoscaleSetting_Timeouts>;
}

export interface AutoscaleSettingAttrs {
  enabled: boolean;
  id: string;
  location: string;
  name: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  targetResourceId: string;
  notification: AutoscaleSetting_Notification[];
  predictive: AutoscaleSetting_Predictive[];
  profile: AutoscaleSetting_Profile[];
  timeouts: AutoscaleSetting_Timeouts;
}

export const AutoscaleSetting: ResourceBinding<AutoscaleSettingConfig, AutoscaleSettingAttrs> = {
  wireType: "azurerm_monitor_autoscale_setting",
  fields: {
    enabled: "enabled",
    id: "id",
    location: "location",
    name: "name",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    targetResourceId: "target_resource_id",
    notification: {
      wireName: "notification",
      kind: "list",
      fields: AutoscaleSetting_NotificationFields,
    },
    predictive: {
      wireName: "predictive",
      kind: "list",
      fields: AutoscaleSetting_PredictiveFields,
    },
    profile: {
      wireName: "profile",
      kind: "list",
      fields: AutoscaleSetting_ProfileFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AutoscaleSetting_TimeoutsFields,
    },
  },
};
