// Code generated by `ubx sdk gen` from azurerm_monitor_data_collection_endpoint. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataCollectionEndpoint_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const DataCollectionEndpoint_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface DataCollectionEndpointConfig {
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  kind?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  publicNetworkAccessEnabled?: boolean | Computed<boolean>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: DataCollectionEndpoint_Timeouts | Computed<DataCollectionEndpoint_Timeouts>;
}

export interface DataCollectionEndpointAttrs {
  configurationAccessEndpoint: string;
  description: string;
  id: string;
  immutableId: string;
  kind: string;
  location: string;
  logsIngestionEndpoint: string;
  metricsIngestionEndpoint: string;
  name: string;
  publicNetworkAccessEnabled: boolean;
  resourceGroupName: string;
  tags: Record<string, string>;
  timeouts: DataCollectionEndpoint_Timeouts;
}

export const DataCollectionEndpoint: ResourceBinding<DataCollectionEndpointConfig, DataCollectionEndpointAttrs> = {
  wireType: "azurerm_monitor_data_collection_endpoint",
  fields: {
    description: "description",
    id: "id",
    kind: "kind",
    location: "location",
    name: "name",
    publicNetworkAccessEnabled: "public_network_access_enabled",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DataCollectionEndpoint_TimeoutsFields,
    },
  },
};
