// Code generated by `ubx sdk gen` from azurerm_monitor_diagnostic_setting. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DiagnosticSetting_EnabledLog {
  category: string;
  categoryGroup: string;
}

export interface DiagnosticSetting_EnabledMetric {
  category: string;
}

export interface DiagnosticSetting_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const DiagnosticSetting_EnabledLogFields: FieldMap = {
  category: "category",
  categoryGroup: "category_group",
};

const DiagnosticSetting_EnabledMetricFields: FieldMap = {
  category: "category",
};

const DiagnosticSetting_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface DiagnosticSettingConfig {
  eventhubAuthorizationRuleId?: string | Computed<string>;
  eventhubName?: string | Computed<string>;
  id?: string | Computed<string>;
  logAnalyticsDestinationType?: string | Computed<string>;
  logAnalyticsWorkspaceId?: string | Computed<string>;
  name: string | Computed<string>;
  partnerSolutionId?: string | Computed<string>;
  storageAccountId?: string | Computed<string>;
  targetResourceId: string | Computed<string>;
  enabledLog?: DiagnosticSetting_EnabledLog[] | Computed<DiagnosticSetting_EnabledLog[]>;
  enabledMetric?: DiagnosticSetting_EnabledMetric[] | Computed<DiagnosticSetting_EnabledMetric[]>;
  timeouts?: DiagnosticSetting_Timeouts | Computed<DiagnosticSetting_Timeouts>;
}

export interface DiagnosticSettingAttrs {
  eventhubAuthorizationRuleId: string;
  eventhubName: string;
  id: string;
  logAnalyticsDestinationType: string;
  logAnalyticsWorkspaceId: string;
  name: string;
  partnerSolutionId: string;
  storageAccountId: string;
  targetResourceId: string;
  enabledLog: DiagnosticSetting_EnabledLog[];
  enabledMetric: DiagnosticSetting_EnabledMetric[];
  timeouts: DiagnosticSetting_Timeouts;
}

export const DiagnosticSetting: ResourceBinding<DiagnosticSettingConfig, DiagnosticSettingAttrs> = {
  wireType: "azurerm_monitor_diagnostic_setting",
  fields: {
    eventhubAuthorizationRuleId: "eventhub_authorization_rule_id",
    eventhubName: "eventhub_name",
    id: "id",
    logAnalyticsDestinationType: "log_analytics_destination_type",
    logAnalyticsWorkspaceId: "log_analytics_workspace_id",
    name: "name",
    partnerSolutionId: "partner_solution_id",
    storageAccountId: "storage_account_id",
    targetResourceId: "target_resource_id",
    enabledLog: {
      wireName: "enabled_log",
      kind: "set",
      fields: DiagnosticSetting_EnabledLogFields,
    },
    enabledMetric: {
      wireName: "enabled_metric",
      kind: "set",
      fields: DiagnosticSetting_EnabledMetricFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DiagnosticSetting_TimeoutsFields,
    },
  },
};
