// Code generated by `ubx sdk gen` from azurerm_monitor_workspace. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Workspace_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Workspace_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface WorkspaceConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  publicNetworkAccessEnabled?: boolean | Computed<boolean>;
  resourceGroupName: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: Workspace_Timeouts | Computed<Workspace_Timeouts>;
}

export interface WorkspaceAttrs {
  defaultDataCollectionEndpointId: string;
  defaultDataCollectionRuleId: string;
  id: string;
  location: string;
  name: string;
  publicNetworkAccessEnabled: boolean;
  queryEndpoint: string;
  resourceGroupName: string;
  tags: Record<string, string>;
  timeouts: Workspace_Timeouts;
}

export const Workspace: ResourceBinding<WorkspaceConfig, WorkspaceAttrs> = {
  wireType: "azurerm_monitor_workspace",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    publicNetworkAccessEnabled: "public_network_access_enabled",
    resourceGroupName: "resource_group_name",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Workspace_TimeoutsFields,
    },
  },
};
